use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use arc_swap::ArcSwap;

use crate::ResolveReason;

mod pb {
    pub use crate::proto::confidence::flags::resolver::v1::telemetry_data::{
        BucketSpan, ResolveLatency, ResolveRate, StateAge,
    };
    pub use crate::proto::confidence::flags::resolver::v1::TelemetryData;
}

/// Trait for types that have histogram configuration metadata
pub trait HistogramConfig {
    const MIN_VALUE: u32;
    const MAX_VALUE: u32;
    const BUCKET_COUNT: usize;
    const UNIT: &'static str;
}

include!(concat!(env!("OUT_DIR"), "/telemetry_config.rs"));

// REASON_COUNT is generated by build.rs from the ResolveReason proto enum.

/// Lock-free exponential histogram for positive integer observations.
///
/// Bucket boundaries are at `ratio^k` where the ratio is derived from
/// `min_value`, `max_value` and `max_buckets`. The range [min_value, max_value]
/// is covered by `max_buckets` exponential buckets, plus one underflow bucket
/// for values < min_value and one overflow bucket for values > max_value.
pub struct Histogram {
    ln_ratio: f64,
    min_exponent: i32,
    sum: AtomicU64,
    count: AtomicU64,
    /// Layout: [underflow] [bucket 0 .. bucket max_buckets-3] [overflow]
    /// Total length: max_buckets
    buckets: Box<[AtomicU64]>,
}

impl Histogram {
    /// Create a histogram for a type that implements HistogramConfig.
    pub fn for_type<T: HistogramConfig>() -> Self {
        Self::new(T::MIN_VALUE, T::MAX_VALUE, T::BUCKET_COUNT)
    }

    /// Create a new histogram covering [min_value, max_value] with at most
    /// `max_buckets` buckets total, including one underflow and one overflow bucket.
    ///
    /// The ratio is derived as `(max_value / min_value)^(1 / (max_buckets - 3))`.
    pub fn new(min_value: u32, max_value: u32, max_buckets: usize) -> Self {
        assert!(max_buckets >= 3, "max_buckets must be at least 3");
        assert!(min_value > 0, "min_value must be > 0");
        let closed_buckets = max_buckets.saturating_sub(2); // exclude underflow + overflow
        let ln_min = (min_value as f64).ln();
        let ln_max = (max_value as f64).ln();
        let denominator = closed_buckets.saturating_sub(1).max(1) as f64;
        let ln_ratio = (ln_max - ln_min) / denominator;
        let min_exponent = (ln_min / ln_ratio).floor() as i32;
        let buckets: Vec<AtomicU64> = (0..max_buckets).map(|_| AtomicU64::new(0)).collect();
        Histogram {
            ln_ratio,
            min_exponent,
            sum: AtomicU64::new(0),
            count: AtomicU64::new(0),
            buckets: buckets.into_boxed_slice(),
        }
    }

    /// Record an observation.
    pub fn observe(&self, value: u32) {
        self.sum.fetch_add(value as u64, Ordering::Relaxed);
        self.count.fetch_add(1, Ordering::Relaxed);

        let idx = if value == 0 {
            0 // underflow
        } else {
            let k = (value as f64).ln() / self.ln_ratio;
            let k = k.floor() as i32;
            let k = k.saturating_sub(self.min_exponent);
            let last = self.buckets.len().saturating_sub(1);
            (k as usize).saturating_add(1).clamp(1, last)
        };
        if let Some(bucket) = self.buckets.get(idx) {
            bucket.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Snapshot the histogram counters into plain u64 values.
    fn snapshot(&self) -> HistogramSnapshot {
        HistogramSnapshot {
            sum: self.sum.load(Ordering::Relaxed),
            count: self.count.load(Ordering::Relaxed),
            buckets: self
                .buckets
                .iter()
                .map(|b| b.load(Ordering::Relaxed))
                .collect(),
        }
    }

    /// Build BucketSpans from a slice of bucket counts (used for proto encoding).
    fn bucket_spans(buckets: &[u32], min_exponent: i32) -> Vec<pb::BucketSpan> {
        let mut spans: Vec<pb::BucketSpan> = Vec::new();
        let mut current_span: Option<(i32, Vec<u32>)> = None;

        for (i, &v) in buckets.iter().enumerate() {
            let exponent = min_exponent.saturating_add(i as i32).saturating_sub(1);
            if v > 0 {
                match &mut current_span {
                    Some((_, counts)) => counts.push(v),
                    None => current_span = Some((exponent, vec![v])),
                }
            } else if let Some((offset, counts)) = current_span.take() {
                spans.push(pb::BucketSpan { offset, counts });
            }
        }
        if let Some((offset, counts)) = current_span {
            spans.push(pb::BucketSpan { offset, counts });
        }

        spans
    }
}

struct HistogramSnapshot {
    sum: u64,
    count: u64,
    buckets: Vec<u64>,
}

/// Plain snapshot of cumulative telemetry counters.
///
/// Used for delta computation between flushes and as the future intermediate
/// representation for Prometheus text format serialization.
#[derive(Clone, Default)]
pub struct TelemetrySnapshot {
    pub latency_sum: u64,
    pub latency_count: u64,
    pub latency_buckets: Vec<u64>,
    pub resolve_rates: Vec<u64>,
}

/// Concurrent telemetry collector.
///
/// All methods are safe to call from multiple threads without locking.
/// Call [`Telemetry::snapshot`] to read the current cumulative state, or
/// [`Telemetry::delta_snapshot`] to atomically produce a delta since the last flush.
pub struct Telemetry {
    resolve_latency: Histogram,

    /// Resolve rate counters, one per reason variant.
    resolve_rates: Box<[AtomicU64]>,

    /// Millisecond epoch of the last state update.
    last_state_update: AtomicU64,

    /// Provider called at snapshot time to read current memory usage in bytes.
    memory_provider: Box<dyn Fn() -> u64 + Send + Sync>,
}

impl Telemetry {
    pub fn new() -> Self {
        Self::with_memory_provider(|| 0)
    }

    pub fn with_memory_provider(memory_provider: impl Fn() -> u64 + Send + Sync + 'static) -> Self {
        let resolve_rates: Vec<AtomicU64> = (0..REASON_COUNT).map(|_| AtomicU64::new(0)).collect();
        Telemetry {
            resolve_latency: Histogram::for_type::<pb::ResolveLatency>(),
            resolve_rates: resolve_rates.into_boxed_slice(),
            last_state_update: AtomicU64::new(0),
            memory_provider: Box::new(memory_provider),
        }
    }

    /// Record a resolve latency observation in microseconds.
    pub fn record_latency_us(&self, micros: u32) {
        self.resolve_latency.observe(micros);
    }

    /// Increment the resolve rate counter for the given reason.
    pub fn mark_resolve(&self, reason: ResolveReason) {
        if let Some(counter) = self.resolve_rates.get(reason as usize) {
            counter.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Update the last known state timestamp (millisecond epoch).
    pub fn set_last_state_update(&self, epoch_ms: u64) {
        self.last_state_update.store(epoch_ms, Ordering::Relaxed);
    }

    /// Snapshot the current cumulative telemetry state.
    ///
    /// All values are cumulative (monotonically increasing). Returns a
    /// [`TelemetrySnapshot`] with raw u64 counters. Not perfectly atomic across
    /// all fields, but each individual counter load is atomic — acceptable for metrics.
    pub fn snapshot(&self) -> TelemetrySnapshot {
        let hist = self.resolve_latency.snapshot();
        TelemetrySnapshot {
            latency_sum: hist.sum,
            latency_count: hist.count,
            latency_buckets: hist.buckets,
            resolve_rates: self
                .resolve_rates
                .iter()
                .map(|c| c.load(Ordering::Relaxed))
                .collect(),
        }
    }

    /// Produce a [`TelemetryData`] proto containing deltas since the last flush.
    ///
    /// Atomically swaps `last` with the current snapshot and computes deltas
    /// using wrapping subtraction. Counter fields are cast to u32 for the proto.
    /// Gauge fields (`memory_bytes`, `state_age`) are passed through as latest values.
    ///
    /// Lock-free — safe for both single-threaded WASM and multi-threaded native use.
    pub fn delta_snapshot(&self, last: &ArcSwap<TelemetrySnapshot>) -> pb::TelemetryData {
        let current = self.snapshot();
        let previous = last.swap(Arc::new(current.clone()));

        // Delta histogram
        let delta_sum = current.latency_sum.wrapping_sub(previous.latency_sum) as u32;
        let delta_count = current.latency_count.wrapping_sub(previous.latency_count) as u32;

        let resolve_latency = if delta_count > 0 {
            let delta_buckets: Vec<u32> = current
                .latency_buckets
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    let p = previous.latency_buckets.get(i).copied().unwrap_or(0);
                    c.wrapping_sub(p) as u32
                })
                .collect();

            let spans = Histogram::bucket_spans(&delta_buckets, self.resolve_latency.min_exponent);

            Some(pb::ResolveLatency {
                sum: delta_sum,
                count: delta_count,
                buckets: spans,
                ln_ratio: self.resolve_latency.ln_ratio,
            })
        } else {
            None
        };

        // Delta resolve rates
        let resolve_rate: Vec<pb::ResolveRate> = current
            .resolve_rates
            .iter()
            .enumerate()
            .filter_map(|(i, c)| {
                let p = previous.resolve_rates.get(i).copied().unwrap_or(0);
                let delta = c.wrapping_sub(p) as u32;
                if delta > 0 {
                    Some(pb::ResolveRate {
                        count: delta,
                        reason: i as i32,
                    })
                } else {
                    None
                }
            })
            .collect();

        // Gauge fields: latest values as-is
        let last_update = self.last_state_update.load(Ordering::Relaxed);
        let state_age = if last_update > 0 {
            Some(pb::StateAge {
                last_state_update: last_update,
            })
        } else {
            None
        };

        pb::TelemetryData {
            sdk: None,
            resolve_latency,
            resolve_rate,
            state_age,
            memory_bytes: (self.memory_provider)(),
        }
    }
}

impl Default for Telemetry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn histogram_empty() {
        let hist = Histogram::new(1, 1000, 10);
        let snap = hist.snapshot();
        assert_eq!(snap.count, 0);
        assert_eq!(snap.sum, 0);
    }

    #[test]
    fn histogram_basic_observation() {
        let hist = Histogram::new(1, 1000, 10);
        hist.observe(100);
        hist.observe(200);
        hist.observe(300);

        let snap = hist.snapshot();
        assert_eq!(snap.count, 3);
        assert_eq!(snap.sum, 600);
    }

    #[test]
    fn histogram_snapshot_does_not_reset() {
        let hist = Histogram::new(1, 1000, 10);
        hist.observe(100);
        hist.observe(200);

        let snap1 = hist.snapshot();
        assert_eq!(snap1.count, 2);
        assert_eq!(snap1.sum, 300);

        // Second snapshot should show same values
        let snap2 = hist.snapshot();
        assert_eq!(snap2.count, 2);
        assert_eq!(snap2.sum, 300);

        // Add more observations
        hist.observe(50);
        let snap3 = hist.snapshot();
        assert_eq!(snap3.count, 3);
        assert_eq!(snap3.sum, 350);
    }

    #[test]
    fn histogram_underflow_bucket() {
        let hist = Histogram::new(100, 1000, 10);
        hist.observe(0); // underflow
        hist.observe(1); // underflow (< min_value)
        hist.observe(50); // underflow

        let snap = hist.snapshot();
        assert_eq!(snap.count, 3);
        let total: u64 = snap.buckets.iter().sum();
        assert_eq!(total, 3);
    }

    #[test]
    fn histogram_overflow_bucket() {
        let hist = Histogram::new(1, 100, 10);
        hist.observe(200); // overflow
        hist.observe(500); // overflow
        hist.observe(1000); // overflow

        let snap = hist.snapshot();
        assert_eq!(snap.count, 3);
        let total: u64 = snap.buckets.iter().sum();
        assert_eq!(total, 3);
    }

    #[test]
    fn histogram_bucket_spans() {
        let hist = Histogram::new(1, 1000, 20);

        // Create a pattern with gaps
        hist.observe(10);
        hist.observe(11);
        hist.observe(12);
        // gap
        hist.observe(100);
        hist.observe(101);

        let snap = hist.snapshot();
        let total: u64 = snap.buckets.iter().sum();
        assert_eq!(total, 5);

        // Build spans and verify gaps create multiple spans
        let delta_buckets: Vec<u32> = snap.buckets.iter().map(|&b| b as u32).collect();
        let spans = Histogram::bucket_spans(&delta_buckets, hist.min_exponent);
        assert!(spans.len() > 1, "should have gaps between spans");
        let span_total: u32 = spans.iter().flat_map(|s| &s.counts).sum();
        assert_eq!(span_total, 5);
    }

    #[test]
    fn telemetry_new_is_empty() {
        let tel = Telemetry::new();
        let snap = tel.snapshot();

        assert_eq!(snap.latency_count, 0);
        assert_eq!(snap.latency_sum, 0);
        assert!(snap.resolve_rates.iter().all(|&r| r == 0));
    }

    #[test]
    fn telemetry_record_latency() {
        let tel = Telemetry::new();
        tel.record_latency_us(1000);
        tel.record_latency_us(2000);
        tel.record_latency_us(3000);

        let snap = tel.snapshot();
        assert_eq!(snap.latency_count, 3);
        assert_eq!(snap.latency_sum, 6000);
    }

    #[test]
    fn telemetry_mark_resolve() {
        let tel = Telemetry::new();
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let snap = tel.snapshot();
        assert_eq!(snap.resolve_rates[ResolveReason::Match as usize], 2);
        assert_eq!(
            snap.resolve_rates[ResolveReason::NoTreatmentMatch as usize],
            1
        );
    }

    #[test]
    fn telemetry_snapshot_does_not_reset() {
        let tel = Telemetry::new();

        tel.record_latency_us(100);
        tel.mark_resolve(ResolveReason::Match);

        let snap1 = tel.snapshot();
        assert_eq!(snap1.latency_count, 1);
        assert_eq!(snap1.resolve_rates[ResolveReason::Match as usize], 1);

        // Second snapshot should show same values
        let snap2 = tel.snapshot();
        assert_eq!(snap2.latency_count, 1);
        assert_eq!(snap2.resolve_rates[ResolveReason::Match as usize], 1);

        // Add more data
        tel.record_latency_us(200);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let snap3 = tel.snapshot();
        assert_eq!(snap3.latency_count, 2);
        assert_eq!(snap3.resolve_rates[ResolveReason::Match as usize], 1);
        assert_eq!(
            snap3.resolve_rates[ResolveReason::NoTreatmentMatch as usize],
            1
        );
    }

    #[test]
    fn telemetry_concurrent_updates() {
        use std::thread;

        let tel = Arc::new(Telemetry::new());
        let mut handles = vec![];

        for i in 0..10 {
            let tel_clone = Arc::clone(&tel);
            let handle = thread::spawn(move || {
                for _ in 0..100 {
                    tel_clone.record_latency_us(i * 10);
                    tel_clone.mark_resolve(ResolveReason::Match);
                }
            });
            handles.push(handle);
        }

        for handle in handles {
            handle.join().unwrap();
        }

        let snap = tel.snapshot();
        assert_eq!(snap.latency_count, 1000);
        assert_eq!(snap.resolve_rates[ResolveReason::Match as usize], 1000);
    }

    #[test]
    fn delta_snapshot_basic() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        // First flush: delta should equal full snapshot
        tel.record_latency_us(100);
        tel.mark_resolve(ResolveReason::Match);

        let delta1 = tel.delta_snapshot(&last);
        assert_eq!(delta1.resolve_latency.as_ref().unwrap().count, 1);
        assert_eq!(delta1.resolve_latency.as_ref().unwrap().sum, 100);
        assert_eq!(delta1.resolve_rate.len(), 1);
        assert_eq!(delta1.resolve_rate[0].count, 1);
        assert_eq!(delta1.resolve_rate[0].reason, ResolveReason::Match as i32);

        // Second flush: delta should only show new observations
        tel.record_latency_us(200);
        tel.record_latency_us(300);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let delta2 = tel.delta_snapshot(&last);
        assert_eq!(delta2.resolve_latency.as_ref().unwrap().count, 2);
        assert_eq!(delta2.resolve_latency.as_ref().unwrap().sum, 500);

        let match_rate = delta2
            .resolve_rate
            .iter()
            .find(|r| r.reason == ResolveReason::Match as i32)
            .unwrap();
        assert_eq!(match_rate.count, 1); // delta, not cumulative 2

        let no_match_rate = delta2
            .resolve_rate
            .iter()
            .find(|r| r.reason == ResolveReason::NoTreatmentMatch as i32)
            .unwrap();
        assert_eq!(no_match_rate.count, 1);
    }

    #[test]
    fn delta_snapshot_no_activity() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        tel.record_latency_us(100);
        let _ = tel.delta_snapshot(&last);

        // No new activity
        let delta = tel.delta_snapshot(&last);
        assert!(delta.resolve_latency.is_none());
        assert!(delta.resolve_rate.is_empty());
    }

    #[test]
    fn delta_snapshot_gauges_always_present() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        tel.set_last_state_update(1000);
        let _ = tel.delta_snapshot(&last);

        // Gauge values should appear even if no counter changes
        let delta = tel.delta_snapshot(&last);
        assert!(delta.resolve_latency.is_none()); // no counter activity
        assert_eq!(delta.state_age.unwrap().last_state_update, 1000);
    }
}
