use core::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use arc_swap::ArcSwap;

use crate::ResolveReason;

mod pb {
    pub use crate::proto::confidence::flags::resolver::v1::telemetry_data::{
        BucketSpan, ResolveLatency, ResolveRate, StateAge,
    };
    pub use crate::proto::confidence::flags::resolver::v1::TelemetryData;
}

include!(concat!(env!("OUT_DIR"), "/telemetry_config.rs"));

// REASON_COUNT is generated by build.rs from the ResolveReason proto enum.

/// VictoriaMetrics-compatible bucket ratio: 10^(1/18), i.e. 18 buckets per
/// decimal order of magnitude (~13.6% width per bucket).
const LN_RATIO: f64 = core::f64::consts::LN_10 / 18.0;

/// Number of buckets needed to cover the full u32 range: ceil(ln(2^32) / LN_RATIO) + 1.
/// With LN_RATIO ≈ 0.128 this is 174 buckets (~1.4KB), so we always allocate for
/// the entire u32 space — no clamping needed on the client side.
const BUCKET_COUNT: usize = 174;

/// Lock-free exponential histogram for positive integer observations.
///
/// Bucket boundaries are at `exp(exponent * LN_RATIO)`. The bucket array
/// covers the full u32 range so every observation maps to a real bucket.
pub struct Histogram {
    sum: AtomicU64,
    count: AtomicU64,
    buckets: [AtomicU64; BUCKET_COUNT],
}

impl Histogram {
    fn new() -> Self {
        // SAFETY: AtomicU64 is valid when zero-initialized.
        // std's array::from_fn would work but generates poor code for 174 elements.
        let buckets = unsafe { core::mem::zeroed() };
        Histogram {
            sum: AtomicU64::new(0),
            count: AtomicU64::new(0),
            buckets,
        }
    }

    /// Record an observation.
    fn observe(&self, value: u32) {
        self.sum.fetch_add(value as u64, Ordering::Relaxed);
        self.count.fetch_add(1, Ordering::Relaxed);

        let idx = if value == 0 {
            0
        } else {
            let k = ((value as f64).ln() / LN_RATIO).floor() as usize;
            k.min(self.buckets.len().saturating_sub(1))
        };
        if let Some(bucket) = self.buckets.get(idx) {
            bucket.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Snapshot the histogram counters into plain u64 values.
    fn snapshot(&self) -> HistogramSnapshot {
        HistogramSnapshot {
            sum: self.sum.load(Ordering::Relaxed),
            count: self.count.load(Ordering::Relaxed),
            buckets: self
                .buckets
                .iter()
                .map(|b| b.load(Ordering::Relaxed))
                .collect(),
        }
    }

    /// Build BucketSpans from a slice of bucket counts (used for proto encoding).
    fn bucket_spans(buckets: &[u32]) -> Vec<pb::BucketSpan> {
        let mut spans: Vec<pb::BucketSpan> = Vec::new();
        let mut current_span: Option<(i32, Vec<u32>)> = None;

        for (i, &v) in buckets.iter().enumerate() {
            let exponent = i as i32;
            if v > 0 {
                match &mut current_span {
                    Some((_, counts)) => counts.push(v),
                    None => current_span = Some((exponent, vec![v])),
                }
            } else if let Some((offset, counts)) = current_span.take() {
                spans.push(pb::BucketSpan { offset, counts });
            }
        }
        if let Some((offset, counts)) = current_span {
            spans.push(pb::BucketSpan { offset, counts });
        }

        spans
    }
}

/// Plain snapshot of cumulative telemetry counters.
///
/// Used for delta computation between flushes and as the future intermediate
/// representation for Prometheus text format serialization.
#[derive(Clone, Default)]
pub struct TelemetrySnapshot {
    pub latency: HistogramSnapshot,
    pub resolve_rates: Vec<u64>,
    pub memory_bytes: u64,
}

#[derive(Clone, Default)]
pub struct HistogramSnapshot {
    pub sum: u64,
    pub count: u64,
    pub buckets: Vec<u64>,
}

impl TelemetrySnapshot {
    /// Format the snapshot as Prometheus exposition text.
    ///
    /// All values are cumulative counters, matching what Prometheus expects.
    /// The histogram uses cumulative `le` buckets derived from the exponential
    /// bucket boundaries.
    ///
    /// `instance` is included as an `instance="..."` label on every metric,
    /// allowing outputs from multiple WASM instances to be concatenated into
    /// a single scrape endpoint.
    pub fn to_prometheus(&self, instance: &str) -> String {
        let mut out = String::new();
        // fmt::Write for String is infallible; ignore the Ok.
        let _ = self.write_prometheus(&mut out, instance);
        out
    }

    fn write_prometheus(&self, w: &mut dyn fmt::Write, instance: &str) -> fmt::Result {
        self.write_histogram(w, instance)?;
        self.write_resolve_rates(w, instance)?;
        self.write_memory(w, instance)
    }

    fn write_histogram(&self, w: &mut dyn fmt::Write, instance: &str) -> fmt::Result {
        if self.latency.count == 0 {
            return Ok(());
        }

        writeln!(
            w,
            "# TYPE confidence_resolve_latency_microseconds histogram"
        )?;

        let mut cumulative: u64 = 0;
        for (i, &count) in self.latency.buckets.iter().enumerate() {
            cumulative = cumulative.wrapping_add(count);
            if cumulative == 0 {
                continue;
            }
            let upper = ((i as f64 + 1.0) * LN_RATIO).exp();
            writeln!(
                w,
                "confidence_resolve_latency_microseconds_bucket{{instance=\"{instance}\",le=\"{upper:.6e}\"}} {cumulative}"
            )?;
        }
        writeln!(
            w,
            "confidence_resolve_latency_microseconds_bucket{{instance=\"{instance}\",le=\"+Inf\"}} {}",
            self.latency.count
        )?;
        writeln!(
            w,
            "confidence_resolve_latency_microseconds_sum{{instance=\"{instance}\"}} {}",
            self.latency.sum
        )?;
        writeln!(
            w,
            "confidence_resolve_latency_microseconds_count{{instance=\"{instance}\"}} {}",
            self.latency.count
        )?;

        Ok(())
    }

    fn write_resolve_rates(&self, w: &mut dyn fmt::Write, instance: &str) -> fmt::Result {
        let has_any = self.resolve_rates.iter().any(|&c| c > 0);
        if !has_any {
            return Ok(());
        }

        writeln!(w, "# TYPE confidence_resolves_total counter")?;
        for (i, &count) in self.resolve_rates.iter().enumerate() {
            if count == 0 {
                continue;
            }
            let label = ResolveReason::try_from(i as i32)
                .map(|r| r.as_str_name())
                .unwrap_or("UNKNOWN");
            writeln!(
                w,
                "confidence_resolves_total{{instance=\"{instance}\",reason=\"{label}\"}} {count}"
            )?;
        }

        Ok(())
    }

    fn write_memory(&self, w: &mut dyn fmt::Write, instance: &str) -> fmt::Result {
        if self.memory_bytes == 0 {
            return Ok(());
        }
        writeln!(w, "# TYPE confidence_memory_bytes gauge")?;
        writeln!(
            w,
            "confidence_memory_bytes{{instance=\"{instance}\"}} {}",
            self.memory_bytes
        )
    }
}

/// Concurrent telemetry collector.
///
/// All methods are safe to call from multiple threads without locking.
/// Call [`Telemetry::snapshot`] to read the current cumulative state, or
/// [`Telemetry::delta_snapshot`] to atomically produce a delta since the last flush.
pub struct Telemetry {
    resolve_latency: Histogram,

    /// Resolve rate counters, one per reason variant.
    resolve_rates: Box<[AtomicU64]>,

    /// Millisecond epoch of the last state update.
    last_state_update: AtomicU64,

    /// Provider called at snapshot time to read current memory usage in bytes.
    memory_provider: Box<dyn Fn() -> u64 + Send + Sync>,
}

impl Telemetry {
    pub fn new() -> Self {
        Self::with_memory_provider(|| 0)
    }

    pub fn with_memory_provider(memory_provider: impl Fn() -> u64 + Send + Sync + 'static) -> Self {
        let resolve_rates: Vec<AtomicU64> = (0..REASON_COUNT).map(|_| AtomicU64::new(0)).collect();
        Telemetry {
            resolve_latency: Histogram::new(),
            resolve_rates: resolve_rates.into_boxed_slice(),
            last_state_update: AtomicU64::new(0),
            memory_provider: Box::new(memory_provider),
        }
    }

    /// Record a resolve latency observation in microseconds.
    pub fn record_latency_us(&self, micros: u32) {
        self.resolve_latency.observe(micros);
    }

    /// Increment the resolve rate counter for the given reason.
    pub fn mark_resolve(&self, reason: ResolveReason) {
        if let Some(counter) = self.resolve_rates.get(reason as usize) {
            counter.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Update the last known state timestamp (millisecond epoch).
    pub fn set_last_state_update(&self, epoch_ms: u64) {
        self.last_state_update.store(epoch_ms, Ordering::Relaxed);
    }

    /// Snapshot the current cumulative telemetry state.
    ///
    /// All values are cumulative (monotonically increasing). Returns a
    /// [`TelemetrySnapshot`] with raw u64 counters. Not perfectly atomic across
    /// all fields, but each individual counter load is atomic — acceptable for metrics.
    pub fn snapshot(&self) -> TelemetrySnapshot {
        TelemetrySnapshot {
            latency: self.resolve_latency.snapshot(),
            resolve_rates: self
                .resolve_rates
                .iter()
                .map(|c| c.load(Ordering::Relaxed))
                .collect(),
            memory_bytes: (self.memory_provider)(),
        }
    }

    /// Produce a [`TelemetryData`] proto containing deltas since the last flush.
    ///
    /// Atomically swaps `last` with the current snapshot and computes deltas
    /// using wrapping subtraction. Counter fields are cast to u32 for the proto.
    /// Gauge fields (`memory_bytes`, `state_age`) are passed through as latest values.
    ///
    /// Lock-free — safe for both single-threaded WASM and multi-threaded native use.
    pub fn delta_snapshot(&self, last: &ArcSwap<TelemetrySnapshot>) -> pb::TelemetryData {
        let current = self.snapshot();
        let previous = last.swap(Arc::new(current.clone()));

        // Delta histogram
        let delta_sum = current.latency.sum.wrapping_sub(previous.latency.sum) as u32;
        let delta_count = current.latency.count.wrapping_sub(previous.latency.count) as u32;

        let resolve_latency = if delta_count > 0 {
            let delta_buckets: Vec<u32> = current
                .latency
                .buckets
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    let p = previous.latency.buckets.get(i).copied().unwrap_or(0);
                    c.wrapping_sub(p) as u32
                })
                .collect();

            let spans = Histogram::bucket_spans(&delta_buckets);

            Some(pb::ResolveLatency {
                sum: delta_sum,
                count: delta_count,
                buckets: spans,
                ln_ratio: LN_RATIO,
            })
        } else {
            None
        };

        // Delta resolve rates
        let resolve_rate: Vec<pb::ResolveRate> = current
            .resolve_rates
            .iter()
            .enumerate()
            .filter_map(|(i, c)| {
                let p = previous.resolve_rates.get(i).copied().unwrap_or(0);
                let delta = c.wrapping_sub(p) as u32;
                if delta > 0 {
                    Some(pb::ResolveRate {
                        count: delta,
                        reason: i as i32,
                    })
                } else {
                    None
                }
            })
            .collect();

        // Gauge fields: latest values as-is
        let last_update = self.last_state_update.load(Ordering::Relaxed);
        let state_age = if last_update > 0 {
            Some(pb::StateAge {
                last_state_update: last_update,
            })
        } else {
            None
        };

        pb::TelemetryData {
            sdk: None,
            resolve_latency,
            resolve_rate,
            state_age,
            memory_bytes: (self.memory_provider)(),
            resolver_version: crate::version::VERSION.to_string(),
        }
    }
}

impl Default for Telemetry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn histogram_empty() {
        let hist = Histogram::new();
        let snap = hist.snapshot();
        assert_eq!(snap.count, 0);
        assert_eq!(snap.sum, 0);
    }

    #[test]
    fn histogram_basic_observation() {
        let hist = Histogram::new();
        hist.observe(100);
        hist.observe(200);
        hist.observe(300);

        let snap = hist.snapshot();
        assert_eq!(snap.count, 3);
        assert_eq!(snap.sum, 600);
    }

    #[test]
    fn histogram_snapshot_does_not_reset() {
        let hist = Histogram::new();
        hist.observe(100);
        hist.observe(200);

        let snap1 = hist.snapshot();
        assert_eq!(snap1.count, 2);
        assert_eq!(snap1.sum, 300);

        // Second snapshot should show same values
        let snap2 = hist.snapshot();
        assert_eq!(snap2.count, 2);
        assert_eq!(snap2.sum, 300);

        // Add more observations
        hist.observe(50);
        let snap3 = hist.snapshot();
        assert_eq!(snap3.count, 3);
        assert_eq!(snap3.sum, 350);
    }

    #[test]
    fn histogram_zero_lands_in_first_bucket() {
        let hist = Histogram::new();
        hist.observe(0);
        hist.observe(0);

        let snap = hist.snapshot();
        assert_eq!(snap.count, 2);
        assert_eq!(snap.buckets[0], 2);
    }

    #[test]
    fn histogram_covers_full_u32_range() {
        let hist = Histogram::new();
        hist.observe(1);
        hist.observe(1_000_000);
        hist.observe(u32::MAX);

        let snap = hist.snapshot();
        assert_eq!(snap.count, 3);
        let total: u64 = snap.buckets.iter().sum();
        assert_eq!(total, 3);
        // All three should land in different buckets
        let nonzero: Vec<_> = snap.buckets.iter().filter(|&&b| b > 0).collect();
        assert_eq!(nonzero.len(), 3);
    }

    #[test]
    fn histogram_bucket_spans() {
        let hist = Histogram::new();

        // Create a pattern with gaps
        hist.observe(10);
        hist.observe(11);
        hist.observe(12);
        // gap
        hist.observe(100);
        hist.observe(101);

        let snap = hist.snapshot();
        let total: u64 = snap.buckets.iter().sum();
        assert_eq!(total, 5);

        // Build spans and verify gaps create multiple spans
        let delta_buckets: Vec<u32> = snap.buckets.iter().map(|&b| b as u32).collect();
        let spans = Histogram::bucket_spans(&delta_buckets);
        assert!(spans.len() > 1, "should have gaps between spans");
        let span_total: u32 = spans.iter().flat_map(|s| &s.counts).sum();
        assert_eq!(span_total, 5);
    }

    #[test]
    fn telemetry_new_is_empty() {
        let tel = Telemetry::new();
        let snap = tel.snapshot();

        assert_eq!(snap.latency.count, 0);
        assert_eq!(snap.latency.sum, 0);
        assert!(snap.resolve_rates.iter().all(|&r| r == 0));
    }

    #[test]
    fn telemetry_record_latency() {
        let tel = Telemetry::new();
        tel.record_latency_us(1000);
        tel.record_latency_us(2000);
        tel.record_latency_us(3000);

        let snap = tel.snapshot();
        assert_eq!(snap.latency.count, 3);
        assert_eq!(snap.latency.sum, 6000);
    }

    #[test]
    fn telemetry_mark_resolve() {
        let tel = Telemetry::new();
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let snap = tel.snapshot();
        assert_eq!(snap.resolve_rates[ResolveReason::Match as usize], 2);
        assert_eq!(
            snap.resolve_rates[ResolveReason::NoTreatmentMatch as usize],
            1
        );
    }

    #[test]
    fn telemetry_snapshot_does_not_reset() {
        let tel = Telemetry::new();

        tel.record_latency_us(100);
        tel.mark_resolve(ResolveReason::Match);

        let snap1 = tel.snapshot();
        assert_eq!(snap1.latency.count, 1);
        assert_eq!(snap1.resolve_rates[ResolveReason::Match as usize], 1);

        // Second snapshot should show same values
        let snap2 = tel.snapshot();
        assert_eq!(snap2.latency.count, 1);
        assert_eq!(snap2.resolve_rates[ResolveReason::Match as usize], 1);

        // Add more data
        tel.record_latency_us(200);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let snap3 = tel.snapshot();
        assert_eq!(snap3.latency.count, 2);
        assert_eq!(snap3.resolve_rates[ResolveReason::Match as usize], 1);
        assert_eq!(
            snap3.resolve_rates[ResolveReason::NoTreatmentMatch as usize],
            1
        );
    }

    #[test]
    fn telemetry_concurrent_updates() {
        use std::thread;

        let tel = Arc::new(Telemetry::new());
        let mut handles = vec![];

        for i in 0..10 {
            let tel_clone = Arc::clone(&tel);
            let handle = thread::spawn(move || {
                for _ in 0..100 {
                    tel_clone.record_latency_us(i * 10);
                    tel_clone.mark_resolve(ResolveReason::Match);
                }
            });
            handles.push(handle);
        }

        for handle in handles {
            handle.join().unwrap();
        }

        let snap = tel.snapshot();
        assert_eq!(snap.latency.count, 1000);
        assert_eq!(snap.resolve_rates[ResolveReason::Match as usize], 1000);
    }

    #[test]
    fn delta_snapshot_basic() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        // First flush: delta should equal full snapshot
        tel.record_latency_us(100);
        tel.mark_resolve(ResolveReason::Match);

        let delta1 = tel.delta_snapshot(&last);
        assert_eq!(delta1.resolve_latency.as_ref().unwrap().count, 1);
        assert_eq!(delta1.resolve_latency.as_ref().unwrap().sum, 100);
        assert_eq!(delta1.resolve_rate.len(), 1);
        assert_eq!(delta1.resolve_rate[0].count, 1);
        assert_eq!(delta1.resolve_rate[0].reason, ResolveReason::Match as i32);

        // Second flush: delta should only show new observations
        tel.record_latency_us(200);
        tel.record_latency_us(300);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::NoTreatmentMatch);

        let delta2 = tel.delta_snapshot(&last);
        assert_eq!(delta2.resolve_latency.as_ref().unwrap().count, 2);
        assert_eq!(delta2.resolve_latency.as_ref().unwrap().sum, 500);

        let match_rate = delta2
            .resolve_rate
            .iter()
            .find(|r| r.reason == ResolveReason::Match as i32)
            .unwrap();
        assert_eq!(match_rate.count, 1); // delta, not cumulative 2

        let no_match_rate = delta2
            .resolve_rate
            .iter()
            .find(|r| r.reason == ResolveReason::NoTreatmentMatch as i32)
            .unwrap();
        assert_eq!(no_match_rate.count, 1);
    }

    #[test]
    fn delta_snapshot_no_activity() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        tel.record_latency_us(100);
        let _ = tel.delta_snapshot(&last);

        // No new activity
        let delta = tel.delta_snapshot(&last);
        assert!(delta.resolve_latency.is_none());
        assert!(delta.resolve_rate.is_empty());
    }

    #[test]
    fn delta_snapshot_gauges_always_present() {
        let tel = Telemetry::new();
        let last = ArcSwap::from_pointee(TelemetrySnapshot::default());

        tel.set_last_state_update(1000);
        let _ = tel.delta_snapshot(&last);

        // Gauge values should appear even if no counter changes
        let delta = tel.delta_snapshot(&last);
        assert!(delta.resolve_latency.is_none()); // no counter activity
        assert_eq!(delta.state_age.unwrap().last_state_update, 1000);
    }

    #[test]
    fn prometheus_empty_snapshot() {
        let snap = TelemetrySnapshot::default();
        assert_eq!(snap.to_prometheus("w0"), "");
    }

    #[test]
    fn prometheus_histogram_and_counters() {
        let tel = Telemetry::new();
        tel.record_latency_us(100);
        tel.record_latency_us(500);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::Match);
        tel.mark_resolve(ResolveReason::NoSegmentMatch);

        let prom = tel.snapshot().to_prometheus("w0");

        // Histogram header
        assert!(prom.contains("# TYPE confidence_resolve_latency_microseconds histogram"));
        // Must have +Inf bucket with instance label
        assert!(prom.contains(
            r#"confidence_resolve_latency_microseconds_bucket{instance="w0",le="+Inf"} 2"#
        ));
        // Sum and count with instance label
        assert!(prom.contains(r#"confidence_resolve_latency_microseconds_sum{instance="w0"} 600"#));
        assert!(prom.contains(r#"confidence_resolve_latency_microseconds_count{instance="w0"} 2"#));

        // Counters with instance label
        assert!(prom.contains("# TYPE confidence_resolves_total counter"));
        assert!(prom.contains(
            r#"confidence_resolves_total{instance="w0",reason="RESOLVE_REASON_MATCH"} 2"#
        ));
        assert!(prom.contains(
            r#"confidence_resolves_total{instance="w0",reason="RESOLVE_REASON_NO_SEGMENT_MATCH"} 1"#
        ));
        // Zero-count reasons should be omitted
        assert!(!prom.contains("FLAG_ARCHIVED"));
    }

    #[test]
    fn prometheus_cumulative_buckets() {
        let tel = Telemetry::new();
        // Two observations in different buckets
        tel.record_latency_us(10);
        tel.record_latency_us(10_000);

        let prom = tel.snapshot().to_prometheus("w0");

        // Parse all le buckets and verify they are monotonically non-decreasing
        let bucket_counts: Vec<u64> = prom
            .lines()
            .filter(|l| l.contains("le=\"") && !l.contains("+Inf"))
            .map(|l| l.rsplit_once(' ').unwrap().1.parse::<u64>().unwrap())
            .collect();

        for pair in bucket_counts.windows(2) {
            assert!(
                pair[1] >= pair[0],
                "Prometheus buckets must be cumulative, got {} then {}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn prometheus_distinct_instances_concatenate() {
        let tel = Telemetry::new();
        tel.record_latency_us(100);
        tel.mark_resolve(ResolveReason::Match);

        let snap = tel.snapshot();
        let mut combined = snap.to_prometheus("w0");
        combined.push_str(&snap.to_prometheus("w1"));

        // Both instances present
        assert!(combined.contains(r#"instance="w0""#));
        assert!(combined.contains(r#"instance="w1""#));
    }
}
