# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: confidence/events/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'confidence/events/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import types_pb2 as confidence_dot_events_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onfidence/events/v1/api.proto\x12\x14\x63onfidence.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a confidence/events/v1/types.proto\"\xb1\x01\n\x14PublishEventsRequest\x12\x15\n\rclient_secret\x18\x01 \x01(\t\x12+\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x1b.confidence.events.v1.Event\x12-\n\tsend_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x03sdk\x18\x04 \x01(\x0b\x32\x19.confidence.events.v1.Sdk\"I\n\x15PublishEventsResponse\x12\x30\n\x06\x65rrors\x18\x01 \x03(\x0b\x32 .confidence.events.v1.EventError2y\n\rEventsService\x12h\n\rPublishEvents\x12*.confidence.events.v1.PublishEventsRequest\x1a+.confidence.events.v1.PublishEventsResponseB\x93\x01\n$com.spotify.confidence.sdk.events.v1B\x08\x41piProtoP\x01Z_github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'confidence.events.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.spotify.confidence.sdk.events.v1B\010ApiProtoP\001Z_github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/events'
  _globals['_PUBLISHEVENTSREQUEST']._serialized_start=124
  _globals['_PUBLISHEVENTSREQUEST']._serialized_end=301
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_start=303
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_end=376
  _globals['_EVENTSSERVICE']._serialized_start=378
  _globals['_EVENTSSERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
