name = "confidence-telemetry-test"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-28"

[observability]
enabled = true

[[queues.consumers]]
queue = "telemetry-test-flag-logs"
max_batch_size = 100
max_batch_timeout = 10

[[queues.producers]]
queue = "telemetry-test-flag-logs"
binding = "flag_logs_queue"

[[queues.consumers]]
queue = "telemetry-test-events"
max_batch_size = 100
max_batch_timeout = 10

[[queues.producers]]
queue = "telemetry-test-events"
binding = "events_queue"

[[kv_namespaces]]
binding = "CONFIDENCE_METRICS_KV"
id = "05a77023635a4dbaa4744a20d6419a53"

[vars]
CONFIDENCE_CLIENT_SECRET = "mkjJruAATQWjeY7foFIWfVAcBWnci2YF"
ENABLE_APPLY_DEDUP = "true"
