// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v5.29.3
// source: test-only.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = '';

export interface WriteFlagLogsRequest {
  flagAssigned: Uint8Array[];
  telemetryData: Uint8Array;
  clientResolveInfo: Uint8Array[];
  flagResolveInfo: Uint8Array[];
}

function createBaseWriteFlagLogsRequest(): WriteFlagLogsRequest {
  return { flagAssigned: [], telemetryData: new Uint8Array(0), clientResolveInfo: [], flagResolveInfo: [] };
}

export const WriteFlagLogsRequest: MessageFns<WriteFlagLogsRequest> = {
  encode(message: WriteFlagLogsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.flagAssigned) {
      writer.uint32(10).bytes(v!);
    }
    if (message.telemetryData.length !== 0) {
      writer.uint32(18).bytes(message.telemetryData);
    }
    for (const v of message.clientResolveInfo) {
      writer.uint32(26).bytes(v!);
    }
    for (const v of message.flagResolveInfo) {
      writer.uint32(34).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WriteFlagLogsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWriteFlagLogsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flagAssigned.push(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.telemetryData = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clientResolveInfo.push(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.flagResolveInfo.push(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WriteFlagLogsRequest {
    return {
      flagAssigned: globalThis.Array.isArray(object?.flagAssigned)
        ? object.flagAssigned.map((e: any) => bytesFromBase64(e))
        : globalThis.Array.isArray(object?.flag_assigned)
        ? object.flag_assigned.map((e: any) => bytesFromBase64(e))
        : [],
      telemetryData: isSet(object.telemetryData)
        ? bytesFromBase64(object.telemetryData)
        : isSet(object.telemetry_data)
        ? bytesFromBase64(object.telemetry_data)
        : new Uint8Array(0),
      clientResolveInfo: globalThis.Array.isArray(object?.clientResolveInfo)
        ? object.clientResolveInfo.map((e: any) => bytesFromBase64(e))
        : globalThis.Array.isArray(object?.client_resolve_info)
        ? object.client_resolve_info.map((e: any) => bytesFromBase64(e))
        : [],
      flagResolveInfo: globalThis.Array.isArray(object?.flagResolveInfo)
        ? object.flagResolveInfo.map((e: any) => bytesFromBase64(e))
        : globalThis.Array.isArray(object?.flag_resolve_info)
        ? object.flag_resolve_info.map((e: any) => bytesFromBase64(e))
        : [],
    };
  },

  toJSON(message: WriteFlagLogsRequest): unknown {
    const obj: any = {};
    if (message.flagAssigned?.length) {
      obj.flagAssigned = message.flagAssigned.map(e => base64FromBytes(e));
    }
    if (message.telemetryData.length !== 0) {
      obj.telemetryData = base64FromBytes(message.telemetryData);
    }
    if (message.clientResolveInfo?.length) {
      obj.clientResolveInfo = message.clientResolveInfo.map(e => base64FromBytes(e));
    }
    if (message.flagResolveInfo?.length) {
      obj.flagResolveInfo = message.flagResolveInfo.map(e => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WriteFlagLogsRequest>, I>>(base?: I): WriteFlagLogsRequest {
    return WriteFlagLogsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WriteFlagLogsRequest>, I>>(object: I): WriteFlagLogsRequest {
    const message = createBaseWriteFlagLogsRequest();
    message.flagAssigned = object.flagAssigned?.map(e => e) || [];
    message.telemetryData = object.telemetryData ?? new Uint8Array(0);
    message.clientResolveInfo = object.clientResolveInfo?.map(e => e) || [];
    message.flagResolveInfo = object.flagResolveInfo?.map(e => e) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString('base64');
  } else {
    const bin: string[] = [];
    arr.forEach(byte => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(''));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
