// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/flags/resolver/v1/internal_api.proto

// IMPORTANT: Package name must match backend expectation for gRPC service discovery
// The full gRPC service name is: confidence.flags.resolver.v1.InternalFlagLoggerService

package resolverinternal

import (
	resolver "github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/resolver"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagAssigned_DefaultAssignment_DefaultAssignmentReason int32

const (
	FlagAssigned_DefaultAssignment_DEFAULT_ASSIGNMENT_REASON_UNSPECIFIED FlagAssigned_DefaultAssignment_DefaultAssignmentReason = 0
	FlagAssigned_DefaultAssignment_NO_SEGMENT_MATCH                      FlagAssigned_DefaultAssignment_DefaultAssignmentReason = 1
	// Deprecated: Marked as deprecated in confidence/flags/resolver/v1/internal_api.proto.
	FlagAssigned_DefaultAssignment_NO_TREATMENT_MATCH FlagAssigned_DefaultAssignment_DefaultAssignmentReason = 2
	FlagAssigned_DefaultAssignment_FLAG_ARCHIVED      FlagAssigned_DefaultAssignment_DefaultAssignmentReason = 3
)

// Enum value maps for FlagAssigned_DefaultAssignment_DefaultAssignmentReason.
var (
	FlagAssigned_DefaultAssignment_DefaultAssignmentReason_name = map[int32]string{
		0: "DEFAULT_ASSIGNMENT_REASON_UNSPECIFIED",
		1: "NO_SEGMENT_MATCH",
		2: "NO_TREATMENT_MATCH",
		3: "FLAG_ARCHIVED",
	}
	FlagAssigned_DefaultAssignment_DefaultAssignmentReason_value = map[string]int32{
		"DEFAULT_ASSIGNMENT_REASON_UNSPECIFIED": 0,
		"NO_SEGMENT_MATCH":                      1,
		"NO_TREATMENT_MATCH":                    2,
		"FLAG_ARCHIVED":                         3,
	}
)

func (x FlagAssigned_DefaultAssignment_DefaultAssignmentReason) Enum() *FlagAssigned_DefaultAssignment_DefaultAssignmentReason {
	p := new(FlagAssigned_DefaultAssignment_DefaultAssignmentReason)
	*p = x
	return p
}

func (x FlagAssigned_DefaultAssignment_DefaultAssignmentReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagAssigned_DefaultAssignment_DefaultAssignmentReason) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_resolver_v1_internal_api_proto_enumTypes[0].Descriptor()
}

func (FlagAssigned_DefaultAssignment_DefaultAssignmentReason) Type() protoreflect.EnumType {
	return &file_confidence_flags_resolver_v1_internal_api_proto_enumTypes[0]
}

func (x FlagAssigned_DefaultAssignment_DefaultAssignmentReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagAssigned_DefaultAssignment_DefaultAssignmentReason.Descriptor instead.
func (FlagAssigned_DefaultAssignment_DefaultAssignmentReason) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{5, 2, 0}
}

// The service that allows to report flag assigned and other client-side flag
// operations, useful when the resolve engine runs on the customer's premises
type WriteFlagLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FlagAssigned      []*FlagAssigned        `protobuf:"bytes,1,rep,name=flag_assigned,json=flagAssigned,proto3" json:"flag_assigned,omitempty"`
	TelemetryData     *TelemetryData         `protobuf:"bytes,2,opt,name=telemetry_data,json=telemetryData,proto3" json:"telemetry_data,omitempty"`
	ClientResolveInfo []*ClientResolveInfo   `protobuf:"bytes,3,rep,name=client_resolve_info,json=clientResolveInfo,proto3" json:"client_resolve_info,omitempty"`
	FlagResolveInfo   []*FlagResolveInfo     `protobuf:"bytes,4,rep,name=flag_resolve_info,json=flagResolveInfo,proto3" json:"flag_resolve_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WriteFlagLogsRequest) Reset() {
	*x = WriteFlagLogsRequest{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFlagLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFlagLogsRequest) ProtoMessage() {}

func (x *WriteFlagLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFlagLogsRequest.ProtoReflect.Descriptor instead.
func (*WriteFlagLogsRequest) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFlagLogsRequest) GetFlagAssigned() []*FlagAssigned {
	if x != nil {
		return x.FlagAssigned
	}
	return nil
}

func (x *WriteFlagLogsRequest) GetTelemetryData() *TelemetryData {
	if x != nil {
		return x.TelemetryData
	}
	return nil
}

func (x *WriteFlagLogsRequest) GetClientResolveInfo() []*ClientResolveInfo {
	if x != nil {
		return x.ClientResolveInfo
	}
	return nil
}

func (x *WriteFlagLogsRequest) GetFlagResolveInfo() []*FlagResolveInfo {
	if x != nil {
		return x.FlagResolveInfo
	}
	return nil
}

type WriteFlagLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFlagLogsResponse) Reset() {
	*x = WriteFlagLogsResponse{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFlagLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFlagLogsResponse) ProtoMessage() {}

func (x *WriteFlagLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFlagLogsResponse.ProtoReflect.Descriptor instead.
func (*WriteFlagLogsResponse) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{1}
}

// Request wrapper for sending flag logs to the Cloudflare ingestor.
type IngestFlagLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Batch         *WriteFlagLogsRequest  `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestFlagLogsRequest) Reset() {
	*x = IngestFlagLogsRequest{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestFlagLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestFlagLogsRequest) ProtoMessage() {}

func (x *IngestFlagLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestFlagLogsRequest.ProtoReflect.Descriptor instead.
func (*IngestFlagLogsRequest) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{2}
}

func (x *IngestFlagLogsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *IngestFlagLogsRequest) GetBatch() *WriteFlagLogsRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

// Collection of telemetry metrics. Counter and histogram fields contain deltas
// since the last flush. Gauge fields are latest point-in-time values.
type TelemetryData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about the SDK/provider
	Sdk *resolver.Sdk `protobuf:"bytes,2,opt,name=sdk,proto3" json:"sdk,omitempty"`
	// WASM-produced fields. Must be present so decode→encode round-trips
	// in host SDKs preserve them (ts-proto/protobuf-js drop unknown fields).
	ResolveLatency *TelemetryData_ResolveLatency `protobuf:"bytes,4,opt,name=resolve_latency,json=resolveLatency,proto3" json:"resolve_latency,omitempty"`
	ResolveRate    []*TelemetryData_ResolveRate  `protobuf:"bytes,5,rep,name=resolve_rate,json=resolveRate,proto3" json:"resolve_rate,omitempty"`
	StateAge       *TelemetryData_StateAge       `protobuf:"bytes,6,opt,name=state_age,json=stateAge,proto3" json:"state_age,omitempty"`
	MemoryBytes    uint64                        `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Version of the embedded resolver (e.g. "0.14.0").
	// This must be preserved when providers decode and re-encode telemetry.
	ResolverVersion  string                             `protobuf:"bytes,8,opt,name=resolver_version,json=resolverVersion,proto3" json:"resolver_version,omitempty"`
	ProviderInitRate []*TelemetryData_ProviderInitRate  `protobuf:"bytes,9,rep,name=provider_init_rate,json=providerInitRate,proto3" json:"provider_init_rate,omitempty"`
	ApplyDedup       *TelemetryData_ApplyDedupTelemetry `protobuf:"bytes,10,opt,name=apply_dedup,json=applyDedup,proto3" json:"apply_dedup,omitempty"`
	Flush            *TelemetryData_FlushTelemetry      `protobuf:"bytes,11,opt,name=flush,proto3" json:"flush,omitempty"`
	Events           *TelemetryData_EventsTelemetry     `protobuf:"bytes,12,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryData) GetSdk() *resolver.Sdk {
	if x != nil {
		return x.Sdk
	}
	return nil
}

func (x *TelemetryData) GetResolveLatency() *TelemetryData_ResolveLatency {
	if x != nil {
		return x.ResolveLatency
	}
	return nil
}

func (x *TelemetryData) GetResolveRate() []*TelemetryData_ResolveRate {
	if x != nil {
		return x.ResolveRate
	}
	return nil
}

func (x *TelemetryData) GetStateAge() *TelemetryData_StateAge {
	if x != nil {
		return x.StateAge
	}
	return nil
}

func (x *TelemetryData) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *TelemetryData) GetResolverVersion() string {
	if x != nil {
		return x.ResolverVersion
	}
	return ""
}

func (x *TelemetryData) GetProviderInitRate() []*TelemetryData_ProviderInitRate {
	if x != nil {
		return x.ProviderInitRate
	}
	return nil
}

func (x *TelemetryData) GetApplyDedup() *TelemetryData_ApplyDedupTelemetry {
	if x != nil {
		return x.ApplyDedup
	}
	return nil
}

func (x *TelemetryData) GetFlush() *TelemetryData_FlushTelemetry {
	if x != nil {
		return x.Flush
	}
	return nil
}

func (x *TelemetryData) GetEvents() *TelemetryData_EventsTelemetry {
	if x != nil {
		return x.Events
	}
	return nil
}

type ClientInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Client           string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	ClientCredential string                 `protobuf:"bytes,2,opt,name=client_credential,json=clientCredential,proto3" json:"client_credential,omitempty"`
	// Information about the SDK used to interact with the API.
	Sdk           *resolver.Sdk `protobuf:"bytes,3,opt,name=sdk,proto3" json:"sdk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ClientInfo) GetClientCredential() string {
	if x != nil {
		return x.ClientCredential
	}
	return ""
}

func (x *ClientInfo) GetSdk() *resolver.Sdk {
	if x != nil {
		return x.Sdk
	}
	return nil
}

type FlagAssigned struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ResolveId     string                      `protobuf:"bytes,10,opt,name=resolve_id,json=resolveId,proto3" json:"resolve_id,omitempty"`
	ClientInfo    *ClientInfo                 `protobuf:"bytes,3,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Flags         []*FlagAssigned_AppliedFlag `protobuf:"bytes,15,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagAssigned) Reset() {
	*x = FlagAssigned{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAssigned) ProtoMessage() {}

func (x *FlagAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAssigned.ProtoReflect.Descriptor instead.
func (*FlagAssigned) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{5}
}

func (x *FlagAssigned) GetResolveId() string {
	if x != nil {
		return x.ResolveId
	}
	return ""
}

func (x *FlagAssigned) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *FlagAssigned) GetFlags() []*FlagAssigned_AppliedFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FallthroughAssignment struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Rule                 string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	AssignmentId         string                 `protobuf:"bytes,2,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	TargetingKey         string                 `protobuf:"bytes,3,opt,name=targeting_key,json=targetingKey,proto3" json:"targeting_key,omitempty"`
	TargetingKeySelector string                 `protobuf:"bytes,4,opt,name=targeting_key_selector,json=targetingKeySelector,proto3" json:"targeting_key_selector,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FallthroughAssignment) Reset() {
	*x = FallthroughAssignment{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallthroughAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallthroughAssignment) ProtoMessage() {}

func (x *FallthroughAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallthroughAssignment.ProtoReflect.Descriptor instead.
func (*FallthroughAssignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{6}
}

func (x *FallthroughAssignment) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *FallthroughAssignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *FallthroughAssignment) GetTargetingKey() string {
	if x != nil {
		return x.TargetingKey
	}
	return ""
}

func (x *FallthroughAssignment) GetTargetingKeySelector() string {
	if x != nil {
		return x.TargetingKeySelector
	}
	return ""
}

type ClientResolveInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource reference to a client.
	Client string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	// Resource reference to a credential.
	ClientCredential string `protobuf:"bytes,2,opt,name=client_credential,json=clientCredential,proto3" json:"client_credential,omitempty"`
	// The different evaluation context schema of the client that have been seen recently.
	Schema        []*ClientResolveInfo_EvaluationContextSchemaInstance `protobuf:"bytes,3,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResolveInfo) Reset() {
	*x = ClientResolveInfo{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResolveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResolveInfo) ProtoMessage() {}

func (x *ClientResolveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResolveInfo.ProtoReflect.Descriptor instead.
func (*ClientResolveInfo) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{7}
}

func (x *ClientResolveInfo) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ClientResolveInfo) GetClientCredential() string {
	if x != nil {
		return x.ClientCredential
	}
	return ""
}

func (x *ClientResolveInfo) GetSchema() []*ClientResolveInfo_EvaluationContextSchemaInstance {
	if x != nil {
		return x.Schema
	}
	return nil
}

type FlagResolveInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The flag the info is about
	Flag string `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	// Information about how variants were resolved.
	VariantResolveInfo []*FlagResolveInfo_VariantResolveInfo `protobuf:"bytes,2,rep,name=variant_resolve_info,json=variantResolveInfo,proto3" json:"variant_resolve_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FlagResolveInfo) Reset() {
	*x = FlagResolveInfo{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagResolveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagResolveInfo) ProtoMessage() {}

func (x *FlagResolveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagResolveInfo.ProtoReflect.Descriptor instead.
func (*FlagResolveInfo) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{8}
}

func (x *FlagResolveInfo) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *FlagResolveInfo) GetVariantResolveInfo() []*FlagResolveInfo_VariantResolveInfo {
	if x != nil {
		return x.VariantResolveInfo
	}
	return nil
}

type WriteOperationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StoreVariantOp []*VariantData         `protobuf:"bytes,1,rep,name=store_variant_op,json=storeVariantOp,proto3" json:"store_variant_op,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteOperationsRequest) Reset() {
	*x = WriteOperationsRequest{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperationsRequest) ProtoMessage() {}

func (x *WriteOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperationsRequest.ProtoReflect.Descriptor instead.
func (*WriteOperationsRequest) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{9}
}

func (x *WriteOperationsRequest) GetStoreVariantOp() []*VariantData {
	if x != nil {
		return x.StoreVariantOp
	}
	return nil
}

type WriteOperationsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperationsResult) Reset() {
	*x = WriteOperationsResult{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperationsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperationsResult) ProtoMessage() {}

func (x *WriteOperationsResult) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperationsResult.ProtoReflect.Descriptor instead.
func (*WriteOperationsResult) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{10}
}

type VariantReadOp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	Rule            string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VariantReadOp) Reset() {
	*x = VariantReadOp{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantReadOp) ProtoMessage() {}

func (x *VariantReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantReadOp.ProtoReflect.Descriptor instead.
func (*VariantReadOp) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{11}
}

func (x *VariantReadOp) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *VariantReadOp) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

func (x *VariantReadOp) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type InclusionReadOp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InclusionReadOp) Reset() {
	*x = InclusionReadOp{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionReadOp) ProtoMessage() {}

func (x *InclusionReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionReadOp.ProtoReflect.Descriptor instead.
func (*InclusionReadOp) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{12}
}

func (x *InclusionReadOp) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *InclusionReadOp) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

type ReadOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*ReadOp_VariantReadOp
	//	*ReadOp_InclusionReadOp
	Op            isReadOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOp) Reset() {
	*x = ReadOp{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOp) ProtoMessage() {}

func (x *ReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOp.ProtoReflect.Descriptor instead.
func (*ReadOp) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{13}
}

func (x *ReadOp) GetOp() isReadOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ReadOp) GetVariantReadOp() *VariantReadOp {
	if x != nil {
		if x, ok := x.Op.(*ReadOp_VariantReadOp); ok {
			return x.VariantReadOp
		}
	}
	return nil
}

func (x *ReadOp) GetInclusionReadOp() *InclusionReadOp {
	if x != nil {
		if x, ok := x.Op.(*ReadOp_InclusionReadOp); ok {
			return x.InclusionReadOp
		}
	}
	return nil
}

type isReadOp_Op interface {
	isReadOp_Op()
}

type ReadOp_VariantReadOp struct {
	VariantReadOp *VariantReadOp `protobuf:"bytes,1,opt,name=variant_read_op,json=variantReadOp,proto3,oneof"`
}

type ReadOp_InclusionReadOp struct {
	InclusionReadOp *InclusionReadOp `protobuf:"bytes,2,opt,name=inclusion_read_op,json=inclusionReadOp,proto3,oneof"`
}

func (*ReadOp_VariantReadOp) isReadOp_Op() {}

func (*ReadOp_InclusionReadOp) isReadOp_Op() {}

type ReadOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*ReadOp              `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOperationsRequest) Reset() {
	*x = ReadOperationsRequest{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOperationsRequest) ProtoMessage() {}

func (x *ReadOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOperationsRequest.ProtoReflect.Descriptor instead.
func (*ReadOperationsRequest) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{14}
}

func (x *ReadOperationsRequest) GetOps() []*ReadOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type VariantData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	Rule            string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Variant         string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VariantData) Reset() {
	*x = VariantData{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantData) ProtoMessage() {}

func (x *VariantData) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantData.ProtoReflect.Descriptor instead.
func (*VariantData) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{15}
}

func (x *VariantData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *VariantData) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

func (x *VariantData) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *VariantData) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type InclusionData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	IsIncluded      bool                   `protobuf:"varint,3,opt,name=is_included,json=isIncluded,proto3" json:"is_included,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InclusionData) Reset() {
	*x = InclusionData{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionData) ProtoMessage() {}

func (x *InclusionData) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionData.ProtoReflect.Descriptor instead.
func (*InclusionData) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{16}
}

func (x *InclusionData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *InclusionData) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

func (x *InclusionData) GetIsIncluded() bool {
	if x != nil {
		return x.IsIncluded
	}
	return false
}

type ReadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReadResult_VariantResult
	//	*ReadResult_InclusionResult
	Result        isReadResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{17}
}

func (x *ReadResult) GetResult() isReadResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReadResult) GetVariantResult() *VariantData {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_VariantResult); ok {
			return x.VariantResult
		}
	}
	return nil
}

func (x *ReadResult) GetInclusionResult() *InclusionData {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_InclusionResult); ok {
			return x.InclusionResult
		}
	}
	return nil
}

type isReadResult_Result interface {
	isReadResult_Result()
}

type ReadResult_VariantResult struct {
	VariantResult *VariantData `protobuf:"bytes,1,opt,name=variant_result,json=variantResult,proto3,oneof"`
}

type ReadResult_InclusionResult struct {
	InclusionResult *InclusionData `protobuf:"bytes,2,opt,name=inclusion_result,json=inclusionResult,proto3,oneof"`
}

func (*ReadResult_VariantResult) isReadResult_Result() {}

func (*ReadResult_InclusionResult) isReadResult_Result() {}

type ReadOperationsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ReadResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOperationsResult) Reset() {
	*x = ReadOperationsResult{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOperationsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOperationsResult) ProtoMessage() {}

func (x *ReadOperationsResult) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOperationsResult.ProtoReflect.Descriptor instead.
func (*ReadOperationsResult) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{18}
}

func (x *ReadOperationsResult) GetResults() []*ReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TelemetryData_FlushTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     uint32                 `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        uint32                 `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData_FlushTelemetry) Reset() {
	*x = TelemetryData_FlushTelemetry{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_FlushTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_FlushTelemetry) ProtoMessage() {}

func (x *TelemetryData_FlushTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_FlushTelemetry.ProtoReflect.Descriptor instead.
func (*TelemetryData_FlushTelemetry) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TelemetryData_FlushTelemetry) GetSucceeded() uint32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *TelemetryData_FlushTelemetry) GetFailed() uint32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type TelemetryData_EventsTelemetry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Published        uint32                 `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	BatchesSucceeded uint32                 `protobuf:"varint,2,opt,name=batches_succeeded,json=batchesSucceeded,proto3" json:"batches_succeeded,omitempty"`
	BatchesFailed    uint32                 `protobuf:"varint,3,opt,name=batches_failed,json=batchesFailed,proto3" json:"batches_failed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryData_EventsTelemetry) Reset() {
	*x = TelemetryData_EventsTelemetry{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_EventsTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_EventsTelemetry) ProtoMessage() {}

func (x *TelemetryData_EventsTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_EventsTelemetry.ProtoReflect.Descriptor instead.
func (*TelemetryData_EventsTelemetry) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *TelemetryData_EventsTelemetry) GetPublished() uint32 {
	if x != nil {
		return x.Published
	}
	return 0
}

func (x *TelemetryData_EventsTelemetry) GetBatchesSucceeded() uint32 {
	if x != nil {
		return x.BatchesSucceeded
	}
	return 0
}

func (x *TelemetryData_EventsTelemetry) GetBatchesFailed() uint32 {
	if x != nil {
		return x.BatchesFailed
	}
	return 0
}

type TelemetryData_ResolveLatency struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Sum           uint32                      `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Count         uint32                      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Buckets       []*TelemetryData_BucketSpan `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
	LnRatio       float64                     `protobuf:"fixed64,4,opt,name=ln_ratio,json=lnRatio,proto3" json:"ln_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData_ResolveLatency) Reset() {
	*x = TelemetryData_ResolveLatency{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_ResolveLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_ResolveLatency) ProtoMessage() {}

func (x *TelemetryData_ResolveLatency) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_ResolveLatency.ProtoReflect.Descriptor instead.
func (*TelemetryData_ResolveLatency) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 2}
}

func (x *TelemetryData_ResolveLatency) GetSum() uint32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *TelemetryData_ResolveLatency) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TelemetryData_ResolveLatency) GetBuckets() []*TelemetryData_BucketSpan {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *TelemetryData_ResolveLatency) GetLnRatio() float64 {
	if x != nil {
		return x.LnRatio
	}
	return 0
}

type TelemetryData_ResolveRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Reason        uint32                 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData_ResolveRate) Reset() {
	*x = TelemetryData_ResolveRate{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_ResolveRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_ResolveRate) ProtoMessage() {}

func (x *TelemetryData_ResolveRate) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_ResolveRate.ProtoReflect.Descriptor instead.
func (*TelemetryData_ResolveRate) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 3}
}

func (x *TelemetryData_ResolveRate) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TelemetryData_ResolveRate) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type TelemetryData_StateAge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastStateUpdate uint64                 `protobuf:"varint,1,opt,name=last_state_update,json=lastStateUpdate,proto3" json:"last_state_update,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryData_StateAge) Reset() {
	*x = TelemetryData_StateAge{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_StateAge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_StateAge) ProtoMessage() {}

func (x *TelemetryData_StateAge) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_StateAge.ProtoReflect.Descriptor instead.
func (*TelemetryData_StateAge) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 4}
}

func (x *TelemetryData_StateAge) GetLastStateUpdate() uint64 {
	if x != nil {
		return x.LastStateUpdate
	}
	return 0
}

type TelemetryData_BucketSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Counts        []uint32               `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData_BucketSpan) Reset() {
	*x = TelemetryData_BucketSpan{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_BucketSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_BucketSpan) ProtoMessage() {}

func (x *TelemetryData_BucketSpan) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_BucketSpan.ProtoReflect.Descriptor instead.
func (*TelemetryData_BucketSpan) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 5}
}

func (x *TelemetryData_BucketSpan) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TelemetryData_BucketSpan) GetCounts() []uint32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type TelemetryData_ApplyDedupTelemetry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppliesTotal     uint32                 `protobuf:"varint,1,opt,name=applies_total,json=appliesTotal,proto3" json:"applies_total,omitempty"`
	AppliesDeduped   uint32                 `protobuf:"varint,2,opt,name=applies_deduped,json=appliesDeduped,proto3" json:"applies_deduped,omitempty"`
	AppliesNotCached uint32                 `protobuf:"varint,3,opt,name=applies_not_cached,json=appliesNotCached,proto3" json:"applies_not_cached,omitempty"`
	Sweeps           uint32                 `protobuf:"varint,4,opt,name=sweeps,proto3" json:"sweeps,omitempty"`
	MapSize          uint32                 `protobuf:"varint,5,opt,name=map_size,json=mapSize,proto3" json:"map_size,omitempty"`
	MapCapacity      uint32                 `protobuf:"varint,6,opt,name=map_capacity,json=mapCapacity,proto3" json:"map_capacity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryData_ApplyDedupTelemetry) Reset() {
	*x = TelemetryData_ApplyDedupTelemetry{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_ApplyDedupTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_ApplyDedupTelemetry) ProtoMessage() {}

func (x *TelemetryData_ApplyDedupTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_ApplyDedupTelemetry.ProtoReflect.Descriptor instead.
func (*TelemetryData_ApplyDedupTelemetry) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 6}
}

func (x *TelemetryData_ApplyDedupTelemetry) GetAppliesTotal() uint32 {
	if x != nil {
		return x.AppliesTotal
	}
	return 0
}

func (x *TelemetryData_ApplyDedupTelemetry) GetAppliesDeduped() uint32 {
	if x != nil {
		return x.AppliesDeduped
	}
	return 0
}

func (x *TelemetryData_ApplyDedupTelemetry) GetAppliesNotCached() uint32 {
	if x != nil {
		return x.AppliesNotCached
	}
	return 0
}

func (x *TelemetryData_ApplyDedupTelemetry) GetSweeps() uint32 {
	if x != nil {
		return x.Sweeps
	}
	return 0
}

func (x *TelemetryData_ApplyDedupTelemetry) GetMapSize() uint32 {
	if x != nil {
		return x.MapSize
	}
	return 0
}

func (x *TelemetryData_ApplyDedupTelemetry) GetMapCapacity() uint32 {
	if x != nil {
		return x.MapCapacity
	}
	return 0
}

type TelemetryData_ProviderInitRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData_ProviderInitRate) Reset() {
	*x = TelemetryData_ProviderInitRate{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData_ProviderInitRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData_ProviderInitRate) ProtoMessage() {}

func (x *TelemetryData_ProviderInitRate) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData_ProviderInitRate.ProtoReflect.Descriptor instead.
func (*TelemetryData_ProviderInitRate) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{3, 7}
}

func (x *TelemetryData_ProviderInitRate) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TelemetryData_ProviderInitRate) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type FlagAssigned_AppliedFlag struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Flag                 string                 `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	TargetingKey         string                 `protobuf:"bytes,2,opt,name=targeting_key,json=targetingKey,proto3" json:"targeting_key,omitempty"`
	TargetingKeySelector string                 `protobuf:"bytes,3,opt,name=targeting_key_selector,json=targetingKeySelector,proto3" json:"targeting_key_selector,omitempty"`
	// Types that are valid to be assigned to Assignment:
	//
	//	*FlagAssigned_AppliedFlag_AssignmentInfo
	//	*FlagAssigned_AppliedFlag_DefaultAssignment
	Assignment             isFlagAssigned_AppliedFlag_Assignment `protobuf_oneof:"assignment"`
	AssignmentId           string                                `protobuf:"bytes,6,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Rule                   string                                `protobuf:"bytes,7,opt,name=rule,proto3" json:"rule,omitempty"`
	FallthroughAssignments []*FallthroughAssignment              `protobuf:"bytes,8,rep,name=fallthrough_assignments,json=fallthroughAssignments,proto3" json:"fallthrough_assignments,omitempty"`
	ApplyTime              *timestamppb.Timestamp                `protobuf:"bytes,9,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FlagAssigned_AppliedFlag) Reset() {
	*x = FlagAssigned_AppliedFlag{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAssigned_AppliedFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAssigned_AppliedFlag) ProtoMessage() {}

func (x *FlagAssigned_AppliedFlag) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAssigned_AppliedFlag.ProtoReflect.Descriptor instead.
func (*FlagAssigned_AppliedFlag) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *FlagAssigned_AppliedFlag) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *FlagAssigned_AppliedFlag) GetTargetingKey() string {
	if x != nil {
		return x.TargetingKey
	}
	return ""
}

func (x *FlagAssigned_AppliedFlag) GetTargetingKeySelector() string {
	if x != nil {
		return x.TargetingKeySelector
	}
	return ""
}

func (x *FlagAssigned_AppliedFlag) GetAssignment() isFlagAssigned_AppliedFlag_Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *FlagAssigned_AppliedFlag) GetAssignmentInfo() *FlagAssigned_AssignmentInfo {
	if x != nil {
		if x, ok := x.Assignment.(*FlagAssigned_AppliedFlag_AssignmentInfo); ok {
			return x.AssignmentInfo
		}
	}
	return nil
}

func (x *FlagAssigned_AppliedFlag) GetDefaultAssignment() *FlagAssigned_DefaultAssignment {
	if x != nil {
		if x, ok := x.Assignment.(*FlagAssigned_AppliedFlag_DefaultAssignment); ok {
			return x.DefaultAssignment
		}
	}
	return nil
}

func (x *FlagAssigned_AppliedFlag) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *FlagAssigned_AppliedFlag) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *FlagAssigned_AppliedFlag) GetFallthroughAssignments() []*FallthroughAssignment {
	if x != nil {
		return x.FallthroughAssignments
	}
	return nil
}

func (x *FlagAssigned_AppliedFlag) GetApplyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ApplyTime
	}
	return nil
}

type isFlagAssigned_AppliedFlag_Assignment interface {
	isFlagAssigned_AppliedFlag_Assignment()
}

type FlagAssigned_AppliedFlag_AssignmentInfo struct {
	AssignmentInfo *FlagAssigned_AssignmentInfo `protobuf:"bytes,4,opt,name=assignment_info,json=assignmentInfo,proto3,oneof"`
}

type FlagAssigned_AppliedFlag_DefaultAssignment struct {
	DefaultAssignment *FlagAssigned_DefaultAssignment `protobuf:"bytes,5,opt,name=default_assignment,json=defaultAssignment,proto3,oneof"`
}

func (*FlagAssigned_AppliedFlag_AssignmentInfo) isFlagAssigned_AppliedFlag_Assignment() {}

func (*FlagAssigned_AppliedFlag_DefaultAssignment) isFlagAssigned_AppliedFlag_Assignment() {}

type FlagAssigned_AssignmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       string                 `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagAssigned_AssignmentInfo) Reset() {
	*x = FlagAssigned_AssignmentInfo{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAssigned_AssignmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAssigned_AssignmentInfo) ProtoMessage() {}

func (x *FlagAssigned_AssignmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAssigned_AssignmentInfo.ProtoReflect.Descriptor instead.
func (*FlagAssigned_AssignmentInfo) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *FlagAssigned_AssignmentInfo) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *FlagAssigned_AssignmentInfo) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type FlagAssigned_DefaultAssignment struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Reason        FlagAssigned_DefaultAssignment_DefaultAssignmentReason `protobuf:"varint,1,opt,name=reason,proto3,enum=confidence.flags.resolver.v1.FlagAssigned_DefaultAssignment_DefaultAssignmentReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagAssigned_DefaultAssignment) Reset() {
	*x = FlagAssigned_DefaultAssignment{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAssigned_DefaultAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAssigned_DefaultAssignment) ProtoMessage() {}

func (x *FlagAssigned_DefaultAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAssigned_DefaultAssignment.ProtoReflect.Descriptor instead.
func (*FlagAssigned_DefaultAssignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{5, 2}
}

func (x *FlagAssigned_DefaultAssignment) GetReason() FlagAssigned_DefaultAssignment_DefaultAssignmentReason {
	if x != nil {
		return x.Reason
	}
	return FlagAssigned_DefaultAssignment_DEFAULT_ASSIGNMENT_REASON_UNSPECIFIED
}

// An instance of a schema that was seen
type ClientResolveInfo_EvaluationContextSchemaInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema of each field in the evaluation context.
	Schema        map[string]int32 `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResolveInfo_EvaluationContextSchemaInstance) Reset() {
	*x = ClientResolveInfo_EvaluationContextSchemaInstance{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResolveInfo_EvaluationContextSchemaInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResolveInfo_EvaluationContextSchemaInstance) ProtoMessage() {}

func (x *ClientResolveInfo_EvaluationContextSchemaInstance) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResolveInfo_EvaluationContextSchemaInstance.ProtoReflect.Descriptor instead.
func (*ClientResolveInfo_EvaluationContextSchemaInstance) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ClientResolveInfo_EvaluationContextSchemaInstance) GetSchema() map[string]int32 {
	if x != nil {
		return x.Schema
	}
	return nil
}

// Information about how a variant was resolved.
type FlagResolveInfo_VariantResolveInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If there was a variant assigned, otherwise not set
	Variant string `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	// Number of times the variant was resolved in this period
	Count         int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagResolveInfo_VariantResolveInfo) Reset() {
	*x = FlagResolveInfo_VariantResolveInfo{}
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagResolveInfo_VariantResolveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagResolveInfo_VariantResolveInfo) ProtoMessage() {}

func (x *FlagResolveInfo_VariantResolveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagResolveInfo_VariantResolveInfo.ProtoReflect.Descriptor instead.
func (*FlagResolveInfo_VariantResolveInfo) Descriptor() ([]byte, []int) {
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *FlagResolveInfo_VariantResolveInfo) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *FlagResolveInfo_VariantResolveInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_confidence_flags_resolver_v1_internal_api_proto protoreflect.FileDescriptor

const file_confidence_flags_resolver_v1_internal_api_proto_rawDesc = "" +
	"\n" +
	"/confidence/flags/resolver/v1/internal_api.proto\x12\x1cconfidence.flags.resolver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(confidence/flags/resolver/v1/types.proto\"\xf7\x02\n" +
	"\x14WriteFlagLogsRequest\x12O\n" +
	"\rflag_assigned\x18\x01 \x03(\v2*.confidence.flags.resolver.v1.FlagAssignedR\fflagAssigned\x12R\n" +
	"\x0etelemetry_data\x18\x02 \x01(\v2+.confidence.flags.resolver.v1.TelemetryDataR\rtelemetryData\x12_\n" +
	"\x13client_resolve_info\x18\x03 \x03(\v2/.confidence.flags.resolver.v1.ClientResolveInfoR\x11clientResolveInfo\x12Y\n" +
	"\x11flag_resolve_info\x18\x04 \x03(\v2-.confidence.flags.resolver.v1.FlagResolveInfoR\x0fflagResolveInfo\"\x17\n" +
	"\x15WriteFlagLogsResponse\"\x80\x01\n" +
	"\x15IngestFlagLogsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12H\n" +
	"\x05batch\x18\x02 \x01(\v22.confidence.flags.resolver.v1.WriteFlagLogsRequestR\x05batch\"\xfc\r\n" +
	"\rTelemetryData\x123\n" +
	"\x03sdk\x18\x02 \x01(\v2!.confidence.flags.resolver.v1.SdkR\x03sdk\x12c\n" +
	"\x0fresolve_latency\x18\x04 \x01(\v2:.confidence.flags.resolver.v1.TelemetryData.ResolveLatencyR\x0eresolveLatency\x12Z\n" +
	"\fresolve_rate\x18\x05 \x03(\v27.confidence.flags.resolver.v1.TelemetryData.ResolveRateR\vresolveRate\x12Q\n" +
	"\tstate_age\x18\x06 \x01(\v24.confidence.flags.resolver.v1.TelemetryData.StateAgeR\bstateAge\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x04R\vmemoryBytes\x12)\n" +
	"\x10resolver_version\x18\b \x01(\tR\x0fresolverVersion\x12j\n" +
	"\x12provider_init_rate\x18\t \x03(\v2<.confidence.flags.resolver.v1.TelemetryData.ProviderInitRateR\x10providerInitRate\x12`\n" +
	"\vapply_dedup\x18\n" +
	" \x01(\v2?.confidence.flags.resolver.v1.TelemetryData.ApplyDedupTelemetryR\n" +
	"applyDedup\x12P\n" +
	"\x05flush\x18\v \x01(\v2:.confidence.flags.resolver.v1.TelemetryData.FlushTelemetryR\x05flush\x12S\n" +
	"\x06events\x18\f \x01(\v2;.confidence.flags.resolver.v1.TelemetryData.EventsTelemetryR\x06events\x1aF\n" +
	"\x0eFlushTelemetry\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\rR\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\rR\x06failed\x1a\x83\x01\n" +
	"\x0fEventsTelemetry\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\rR\tpublished\x12+\n" +
	"\x11batches_succeeded\x18\x02 \x01(\rR\x10batchesSucceeded\x12%\n" +
	"\x0ebatches_failed\x18\x03 \x01(\rR\rbatchesFailed\x1a\xa5\x01\n" +
	"\x0eResolveLatency\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\rR\x03sum\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12P\n" +
	"\abuckets\x18\x03 \x03(\v26.confidence.flags.resolver.v1.TelemetryData.BucketSpanR\abuckets\x12\x19\n" +
	"\bln_ratio\x18\x04 \x01(\x01R\alnRatio\x1a;\n" +
	"\vResolveRate\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\rR\x06reason\x1a6\n" +
	"\bStateAge\x12*\n" +
	"\x11last_state_update\x18\x01 \x01(\x04R\x0flastStateUpdate\x1a<\n" +
	"\n" +
	"BucketSpan\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\rR\x06counts\x1a\xe7\x01\n" +
	"\x13ApplyDedupTelemetry\x12#\n" +
	"\rapplies_total\x18\x01 \x01(\rR\fappliesTotal\x12'\n" +
	"\x0fapplies_deduped\x18\x02 \x01(\rR\x0eappliesDeduped\x12,\n" +
	"\x12applies_not_cached\x18\x03 \x01(\rR\x10appliesNotCached\x12\x16\n" +
	"\x06sweeps\x18\x04 \x01(\rR\x06sweeps\x12\x19\n" +
	"\bmap_size\x18\x05 \x01(\rR\amapSize\x12!\n" +
	"\fmap_capacity\x18\x06 \x01(\rR\vmapCapacity\x1a\xcb\x01\n" +
	"\x10ProviderInitRate\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12`\n" +
	"\x06labels\x18\x03 \x03(\v2H.confidence.flags.resolver.v1.TelemetryData.ProviderInitRate.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03\"\x86\x01\n" +
	"\n" +
	"ClientInfo\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12+\n" +
	"\x11client_credential\x18\x02 \x01(\tR\x10clientCredential\x123\n" +
	"\x03sdk\x18\x03 \x01(\v2!.confidence.flags.resolver.v1.SdkR\x03sdk\"\xe0\b\n" +
	"\fFlagAssigned\x12\x1d\n" +
	"\n" +
	"resolve_id\x18\n" +
	" \x01(\tR\tresolveId\x12I\n" +
	"\vclient_info\x18\x03 \x01(\v2(.confidence.flags.resolver.v1.ClientInfoR\n" +
	"clientInfo\x12L\n" +
	"\x05flags\x18\x0f \x03(\v26.confidence.flags.resolver.v1.FlagAssigned.AppliedFlagR\x05flags\x1a\xc1\x04\n" +
	"\vAppliedFlag\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\tR\x04flag\x12#\n" +
	"\rtargeting_key\x18\x02 \x01(\tR\ftargetingKey\x124\n" +
	"\x16targeting_key_selector\x18\x03 \x01(\tR\x14targetingKeySelector\x12d\n" +
	"\x0fassignment_info\x18\x04 \x01(\v29.confidence.flags.resolver.v1.FlagAssigned.AssignmentInfoH\x00R\x0eassignmentInfo\x12m\n" +
	"\x12default_assignment\x18\x05 \x01(\v2<.confidence.flags.resolver.v1.FlagAssigned.DefaultAssignmentH\x00R\x11defaultAssignment\x12#\n" +
	"\rassignment_id\x18\x06 \x01(\tR\fassignmentId\x12\x12\n" +
	"\x04rule\x18\a \x01(\tR\x04rule\x12l\n" +
	"\x17fallthrough_assignments\x18\b \x03(\v23.confidence.flags.resolver.v1.FallthroughAssignmentR\x16fallthroughAssignments\x129\n" +
	"\n" +
	"apply_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tapplyTimeB\f\n" +
	"\n" +
	"assignment\x1aD\n" +
	"\x0eAssignmentInfo\x12\x18\n" +
	"\asegment\x18\x01 \x01(\tR\asegment\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\x1a\x8d\x02\n" +
	"\x11DefaultAssignment\x12l\n" +
	"\x06reason\x18\x01 \x01(\x0e2T.confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment.DefaultAssignmentReasonR\x06reason\"\x89\x01\n" +
	"\x17DefaultAssignmentReason\x12)\n" +
	"%DEFAULT_ASSIGNMENT_REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NO_SEGMENT_MATCH\x10\x01\x12\x1a\n" +
	"\x12NO_TREATMENT_MATCH\x10\x02\x1a\x02\b\x01\x12\x11\n" +
	"\rFLAG_ARCHIVED\x10\x03\"\xab\x01\n" +
	"\x15FallthroughAssignment\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12#\n" +
	"\rassignment_id\x18\x02 \x01(\tR\fassignmentId\x12#\n" +
	"\rtargeting_key\x18\x03 \x01(\tR\ftargetingKey\x124\n" +
	"\x16targeting_key_selector\x18\x04 \x01(\tR\x14targetingKeySelector\"\x95\x03\n" +
	"\x11ClientResolveInfo\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12+\n" +
	"\x11client_credential\x18\x02 \x01(\tR\x10clientCredential\x12g\n" +
	"\x06schema\x18\x03 \x03(\v2O.confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstanceR\x06schema\x1a\xd1\x01\n" +
	"\x1fEvaluationContextSchemaInstance\x12s\n" +
	"\x06schema\x18\x01 \x03(\v2[.confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance.SchemaEntryR\x06schema\x1a9\n" +
	"\vSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xdf\x01\n" +
	"\x0fFlagResolveInfo\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\tR\x04flag\x12r\n" +
	"\x14variant_resolve_info\x18\x02 \x03(\v2@.confidence.flags.resolver.v1.FlagResolveInfo.VariantResolveInfoR\x12variantResolveInfo\x1aD\n" +
	"\x12VariantResolveInfo\x12\x18\n" +
	"\avariant\x18\x01 \x01(\tR\avariant\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"m\n" +
	"\x16WriteOperationsRequest\x12S\n" +
	"\x10store_variant_op\x18\x01 \x03(\v2).confidence.flags.resolver.v1.VariantDataR\x0estoreVariantOp\"\x17\n" +
	"\x15WriteOperationsResult\"a\n" +
	"\rVariantReadOp\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\"O\n" +
	"\x0fInclusionReadOp\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\"\xc2\x01\n" +
	"\x06ReadOp\x12U\n" +
	"\x0fvariant_read_op\x18\x01 \x01(\v2+.confidence.flags.resolver.v1.VariantReadOpH\x00R\rvariantReadOp\x12[\n" +
	"\x11inclusion_read_op\x18\x02 \x01(\v2-.confidence.flags.resolver.v1.InclusionReadOpH\x00R\x0finclusionReadOpB\x04\n" +
	"\x02op\"O\n" +
	"\x15ReadOperationsRequest\x126\n" +
	"\x03ops\x18\x03 \x03(\v2$.confidence.flags.resolver.v1.ReadOpR\x03ops\"y\n" +
	"\vVariantData\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\"n\n" +
	"\rInclusionData\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\x12\x1f\n" +
	"\vis_included\x18\x03 \x01(\bR\n" +
	"isIncluded\"\xc4\x01\n" +
	"\n" +
	"ReadResult\x12R\n" +
	"\x0evariant_result\x18\x01 \x01(\v2).confidence.flags.resolver.v1.VariantDataH\x00R\rvariantResult\x12X\n" +
	"\x10inclusion_result\x18\x02 \x01(\v2+.confidence.flags.resolver.v1.InclusionDataH\x00R\x0finclusionResultB\b\n" +
	"\x06result\"Z\n" +
	"\x14ReadOperationsResult\x12B\n" +
	"\aresults\x18\x01 \x03(\v2(.confidence.flags.resolver.v1.ReadResultR\aresults2\xb2\x03\n" +
	"\x19InternalFlagLoggerService\x12~\n" +
	"\x13ClientWriteFlagLogs\x122.confidence.flags.resolver.v1.WriteFlagLogsRequest\x1a3.confidence.flags.resolver.v1.WriteFlagLogsResponse\x12\x8a\x01\n" +
	"\x1bWriteMaterializedOperations\x124.confidence.flags.resolver.v1.WriteOperationsRequest\x1a3.confidence.flags.resolver.v1.WriteOperationsResult\"\x00\x12\x87\x01\n" +
	"\x1aReadMaterializedOperations\x123.confidence.flags.resolver.v1.ReadOperationsRequest\x1a2.confidence.flags.resolver.v1.ReadOperationsResult\"\x00B\xad\x01\n" +
	",com.spotify.confidence.sdk.flags.resolver.v1B\x10InternalApiProtoP\x01Zigithub.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/resolverinternalb\x06proto3"

var (
	file_confidence_flags_resolver_v1_internal_api_proto_rawDescOnce sync.Once
	file_confidence_flags_resolver_v1_internal_api_proto_rawDescData []byte
)

func file_confidence_flags_resolver_v1_internal_api_proto_rawDescGZIP() []byte {
	file_confidence_flags_resolver_v1_internal_api_proto_rawDescOnce.Do(func() {
		file_confidence_flags_resolver_v1_internal_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_flags_resolver_v1_internal_api_proto_rawDesc), len(file_confidence_flags_resolver_v1_internal_api_proto_rawDesc)))
	})
	return file_confidence_flags_resolver_v1_internal_api_proto_rawDescData
}

var file_confidence_flags_resolver_v1_internal_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_confidence_flags_resolver_v1_internal_api_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_confidence_flags_resolver_v1_internal_api_proto_goTypes = []any{
	(FlagAssigned_DefaultAssignment_DefaultAssignmentReason)(0), // 0: confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment.DefaultAssignmentReason
	(*WriteFlagLogsRequest)(nil),                                // 1: confidence.flags.resolver.v1.WriteFlagLogsRequest
	(*WriteFlagLogsResponse)(nil),                               // 2: confidence.flags.resolver.v1.WriteFlagLogsResponse
	(*IngestFlagLogsRequest)(nil),                               // 3: confidence.flags.resolver.v1.IngestFlagLogsRequest
	(*TelemetryData)(nil),                                       // 4: confidence.flags.resolver.v1.TelemetryData
	(*ClientInfo)(nil),                                          // 5: confidence.flags.resolver.v1.ClientInfo
	(*FlagAssigned)(nil),                                        // 6: confidence.flags.resolver.v1.FlagAssigned
	(*FallthroughAssignment)(nil),                               // 7: confidence.flags.resolver.v1.FallthroughAssignment
	(*ClientResolveInfo)(nil),                                   // 8: confidence.flags.resolver.v1.ClientResolveInfo
	(*FlagResolveInfo)(nil),                                     // 9: confidence.flags.resolver.v1.FlagResolveInfo
	(*WriteOperationsRequest)(nil),                              // 10: confidence.flags.resolver.v1.WriteOperationsRequest
	(*WriteOperationsResult)(nil),                               // 11: confidence.flags.resolver.v1.WriteOperationsResult
	(*VariantReadOp)(nil),                                       // 12: confidence.flags.resolver.v1.VariantReadOp
	(*InclusionReadOp)(nil),                                     // 13: confidence.flags.resolver.v1.InclusionReadOp
	(*ReadOp)(nil),                                              // 14: confidence.flags.resolver.v1.ReadOp
	(*ReadOperationsRequest)(nil),                               // 15: confidence.flags.resolver.v1.ReadOperationsRequest
	(*VariantData)(nil),                                         // 16: confidence.flags.resolver.v1.VariantData
	(*InclusionData)(nil),                                       // 17: confidence.flags.resolver.v1.InclusionData
	(*ReadResult)(nil),                                          // 18: confidence.flags.resolver.v1.ReadResult
	(*ReadOperationsResult)(nil),                                // 19: confidence.flags.resolver.v1.ReadOperationsResult
	(*TelemetryData_FlushTelemetry)(nil),                        // 20: confidence.flags.resolver.v1.TelemetryData.FlushTelemetry
	(*TelemetryData_EventsTelemetry)(nil),                       // 21: confidence.flags.resolver.v1.TelemetryData.EventsTelemetry
	(*TelemetryData_ResolveLatency)(nil),                        // 22: confidence.flags.resolver.v1.TelemetryData.ResolveLatency
	(*TelemetryData_ResolveRate)(nil),                           // 23: confidence.flags.resolver.v1.TelemetryData.ResolveRate
	(*TelemetryData_StateAge)(nil),                              // 24: confidence.flags.resolver.v1.TelemetryData.StateAge
	(*TelemetryData_BucketSpan)(nil),                            // 25: confidence.flags.resolver.v1.TelemetryData.BucketSpan
	(*TelemetryData_ApplyDedupTelemetry)(nil),                   // 26: confidence.flags.resolver.v1.TelemetryData.ApplyDedupTelemetry
	(*TelemetryData_ProviderInitRate)(nil),                      // 27: confidence.flags.resolver.v1.TelemetryData.ProviderInitRate
	nil,                                                         // 28: confidence.flags.resolver.v1.TelemetryData.ProviderInitRate.LabelsEntry
	(*FlagAssigned_AppliedFlag)(nil),                            // 29: confidence.flags.resolver.v1.FlagAssigned.AppliedFlag
	(*FlagAssigned_AssignmentInfo)(nil),                         // 30: confidence.flags.resolver.v1.FlagAssigned.AssignmentInfo
	(*FlagAssigned_DefaultAssignment)(nil),                      // 31: confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment
	(*ClientResolveInfo_EvaluationContextSchemaInstance)(nil),   // 32: confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance
	nil, // 33: confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance.SchemaEntry
	(*FlagResolveInfo_VariantResolveInfo)(nil), // 34: confidence.flags.resolver.v1.FlagResolveInfo.VariantResolveInfo
	(*resolver.Sdk)(nil),                       // 35: confidence.flags.resolver.v1.Sdk
	(*timestamppb.Timestamp)(nil),              // 36: google.protobuf.Timestamp
}
var file_confidence_flags_resolver_v1_internal_api_proto_depIdxs = []int32{
	6,  // 0: confidence.flags.resolver.v1.WriteFlagLogsRequest.flag_assigned:type_name -> confidence.flags.resolver.v1.FlagAssigned
	4,  // 1: confidence.flags.resolver.v1.WriteFlagLogsRequest.telemetry_data:type_name -> confidence.flags.resolver.v1.TelemetryData
	8,  // 2: confidence.flags.resolver.v1.WriteFlagLogsRequest.client_resolve_info:type_name -> confidence.flags.resolver.v1.ClientResolveInfo
	9,  // 3: confidence.flags.resolver.v1.WriteFlagLogsRequest.flag_resolve_info:type_name -> confidence.flags.resolver.v1.FlagResolveInfo
	1,  // 4: confidence.flags.resolver.v1.IngestFlagLogsRequest.batch:type_name -> confidence.flags.resolver.v1.WriteFlagLogsRequest
	35, // 5: confidence.flags.resolver.v1.TelemetryData.sdk:type_name -> confidence.flags.resolver.v1.Sdk
	22, // 6: confidence.flags.resolver.v1.TelemetryData.resolve_latency:type_name -> confidence.flags.resolver.v1.TelemetryData.ResolveLatency
	23, // 7: confidence.flags.resolver.v1.TelemetryData.resolve_rate:type_name -> confidence.flags.resolver.v1.TelemetryData.ResolveRate
	24, // 8: confidence.flags.resolver.v1.TelemetryData.state_age:type_name -> confidence.flags.resolver.v1.TelemetryData.StateAge
	27, // 9: confidence.flags.resolver.v1.TelemetryData.provider_init_rate:type_name -> confidence.flags.resolver.v1.TelemetryData.ProviderInitRate
	26, // 10: confidence.flags.resolver.v1.TelemetryData.apply_dedup:type_name -> confidence.flags.resolver.v1.TelemetryData.ApplyDedupTelemetry
	20, // 11: confidence.flags.resolver.v1.TelemetryData.flush:type_name -> confidence.flags.resolver.v1.TelemetryData.FlushTelemetry
	21, // 12: confidence.flags.resolver.v1.TelemetryData.events:type_name -> confidence.flags.resolver.v1.TelemetryData.EventsTelemetry
	35, // 13: confidence.flags.resolver.v1.ClientInfo.sdk:type_name -> confidence.flags.resolver.v1.Sdk
	5,  // 14: confidence.flags.resolver.v1.FlagAssigned.client_info:type_name -> confidence.flags.resolver.v1.ClientInfo
	29, // 15: confidence.flags.resolver.v1.FlagAssigned.flags:type_name -> confidence.flags.resolver.v1.FlagAssigned.AppliedFlag
	32, // 16: confidence.flags.resolver.v1.ClientResolveInfo.schema:type_name -> confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance
	34, // 17: confidence.flags.resolver.v1.FlagResolveInfo.variant_resolve_info:type_name -> confidence.flags.resolver.v1.FlagResolveInfo.VariantResolveInfo
	16, // 18: confidence.flags.resolver.v1.WriteOperationsRequest.store_variant_op:type_name -> confidence.flags.resolver.v1.VariantData
	12, // 19: confidence.flags.resolver.v1.ReadOp.variant_read_op:type_name -> confidence.flags.resolver.v1.VariantReadOp
	13, // 20: confidence.flags.resolver.v1.ReadOp.inclusion_read_op:type_name -> confidence.flags.resolver.v1.InclusionReadOp
	14, // 21: confidence.flags.resolver.v1.ReadOperationsRequest.ops:type_name -> confidence.flags.resolver.v1.ReadOp
	16, // 22: confidence.flags.resolver.v1.ReadResult.variant_result:type_name -> confidence.flags.resolver.v1.VariantData
	17, // 23: confidence.flags.resolver.v1.ReadResult.inclusion_result:type_name -> confidence.flags.resolver.v1.InclusionData
	18, // 24: confidence.flags.resolver.v1.ReadOperationsResult.results:type_name -> confidence.flags.resolver.v1.ReadResult
	25, // 25: confidence.flags.resolver.v1.TelemetryData.ResolveLatency.buckets:type_name -> confidence.flags.resolver.v1.TelemetryData.BucketSpan
	28, // 26: confidence.flags.resolver.v1.TelemetryData.ProviderInitRate.labels:type_name -> confidence.flags.resolver.v1.TelemetryData.ProviderInitRate.LabelsEntry
	30, // 27: confidence.flags.resolver.v1.FlagAssigned.AppliedFlag.assignment_info:type_name -> confidence.flags.resolver.v1.FlagAssigned.AssignmentInfo
	31, // 28: confidence.flags.resolver.v1.FlagAssigned.AppliedFlag.default_assignment:type_name -> confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment
	7,  // 29: confidence.flags.resolver.v1.FlagAssigned.AppliedFlag.fallthrough_assignments:type_name -> confidence.flags.resolver.v1.FallthroughAssignment
	36, // 30: confidence.flags.resolver.v1.FlagAssigned.AppliedFlag.apply_time:type_name -> google.protobuf.Timestamp
	0,  // 31: confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment.reason:type_name -> confidence.flags.resolver.v1.FlagAssigned.DefaultAssignment.DefaultAssignmentReason
	33, // 32: confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance.schema:type_name -> confidence.flags.resolver.v1.ClientResolveInfo.EvaluationContextSchemaInstance.SchemaEntry
	1,  // 33: confidence.flags.resolver.v1.InternalFlagLoggerService.ClientWriteFlagLogs:input_type -> confidence.flags.resolver.v1.WriteFlagLogsRequest
	10, // 34: confidence.flags.resolver.v1.InternalFlagLoggerService.WriteMaterializedOperations:input_type -> confidence.flags.resolver.v1.WriteOperationsRequest
	15, // 35: confidence.flags.resolver.v1.InternalFlagLoggerService.ReadMaterializedOperations:input_type -> confidence.flags.resolver.v1.ReadOperationsRequest
	2,  // 36: confidence.flags.resolver.v1.InternalFlagLoggerService.ClientWriteFlagLogs:output_type -> confidence.flags.resolver.v1.WriteFlagLogsResponse
	11, // 37: confidence.flags.resolver.v1.InternalFlagLoggerService.WriteMaterializedOperations:output_type -> confidence.flags.resolver.v1.WriteOperationsResult
	19, // 38: confidence.flags.resolver.v1.InternalFlagLoggerService.ReadMaterializedOperations:output_type -> confidence.flags.resolver.v1.ReadOperationsResult
	36, // [36:39] is the sub-list for method output_type
	33, // [33:36] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_confidence_flags_resolver_v1_internal_api_proto_init() }
func file_confidence_flags_resolver_v1_internal_api_proto_init() {
	if File_confidence_flags_resolver_v1_internal_api_proto != nil {
		return
	}
	file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[13].OneofWrappers = []any{
		(*ReadOp_VariantReadOp)(nil),
		(*ReadOp_InclusionReadOp)(nil),
	}
	file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[17].OneofWrappers = []any{
		(*ReadResult_VariantResult)(nil),
		(*ReadResult_InclusionResult)(nil),
	}
	file_confidence_flags_resolver_v1_internal_api_proto_msgTypes[28].OneofWrappers = []any{
		(*FlagAssigned_AppliedFlag_AssignmentInfo)(nil),
		(*FlagAssigned_AppliedFlag_DefaultAssignment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_flags_resolver_v1_internal_api_proto_rawDesc), len(file_confidence_flags_resolver_v1_internal_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confidence_flags_resolver_v1_internal_api_proto_goTypes,
		DependencyIndexes: file_confidence_flags_resolver_v1_internal_api_proto_depIdxs,
		EnumInfos:         file_confidence_flags_resolver_v1_internal_api_proto_enumTypes,
		MessageInfos:      file_confidence_flags_resolver_v1_internal_api_proto_msgTypes,
	}.Build()
	File_confidence_flags_resolver_v1_internal_api_proto = out.File
	file_confidence_flags_resolver_v1_internal_api_proto_goTypes = nil
	file_confidence_flags_resolver_v1_internal_api_proto_depIdxs = nil
}
