// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/flags/admin/v1/resolver.proto

package admin

import (
	types "github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An account region
type ResolverState_Region int32

const (
	// Region is not set
	ResolverState_REGION_UNSPECIFIED ResolverState_Region = 0
	// EU region
	ResolverState_REGION_EU ResolverState_Region = 1
	// US region
	ResolverState_REGION_US ResolverState_Region = 2
)

// Enum value maps for ResolverState_Region.
var (
	ResolverState_Region_name = map[int32]string{
		0: "REGION_UNSPECIFIED",
		1: "REGION_EU",
		2: "REGION_US",
	}
	ResolverState_Region_value = map[string]int32{
		"REGION_UNSPECIFIED": 0,
		"REGION_EU":          1,
		"REGION_US":          2,
	}
)

func (x ResolverState_Region) Enum() *ResolverState_Region {
	p := new(ResolverState_Region)
	*p = x
	return p
}

func (x ResolverState_Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolverState_Region) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_admin_v1_resolver_proto_enumTypes[0].Descriptor()
}

func (ResolverState_Region) Type() protoreflect.EnumType {
	return &file_confidence_flags_admin_v1_resolver_proto_enumTypes[0]
}

func (x ResolverState_Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolverState_Region.Descriptor instead.
func (ResolverState_Region) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{0, 0}
}

// State of the flag.
type Flag_State int32

const (
	// Unspecified state.
	Flag_STATE_UNSPECIFIED Flag_State = 0
	// The flag is active and can be resolved.
	Flag_ACTIVE Flag_State = 1
	// The flag is no longer active.
	Flag_ARCHIVED Flag_State = 2
)

// Enum value maps for Flag_State.
var (
	Flag_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "ARCHIVED",
	}
	Flag_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"ACTIVE":            1,
		"ARCHIVED":          2,
	}
)

func (x Flag_State) Enum() *Flag_State {
	p := new(Flag_State)
	*p = x
	return p
}

func (x Flag_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flag_State) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_admin_v1_resolver_proto_enumTypes[1].Descriptor()
}

func (Flag_State) Type() protoreflect.EnumType {
	return &file_confidence_flags_admin_v1_resolver_proto_enumTypes[1]
}

func (x Flag_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flag_State.Descriptor instead.
func (Flag_State) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 0}
}

type Condition_Comparison_Operator int32

const (
	Condition_Comparison_OPERATOR_UNSPECIFIED  Condition_Comparison_Operator = 0
	Condition_Comparison_EQUALS                Condition_Comparison_Operator = 1
	Condition_Comparison_NOT_EQUALS            Condition_Comparison_Operator = 2
	Condition_Comparison_LESS_THAN             Condition_Comparison_Operator = 3
	Condition_Comparison_LESS_THAN_OR_EQUAL    Condition_Comparison_Operator = 4
	Condition_Comparison_GREATER_THAN          Condition_Comparison_Operator = 5
	Condition_Comparison_GREATER_THAN_OR_EQUAL Condition_Comparison_Operator = 6
	Condition_Comparison_CONTAINS              Condition_Comparison_Operator = 7
	Condition_Comparison_STARTS_WITH           Condition_Comparison_Operator = 8
	Condition_Comparison_ENDS_WITH             Condition_Comparison_Operator = 9
	Condition_Comparison_MATCHES               Condition_Comparison_Operator = 10
	Condition_Comparison_IN                    Condition_Comparison_Operator = 11
	Condition_Comparison_NOT_IN                Condition_Comparison_Operator = 12
	Condition_Comparison_CONTAINS_ANY          Condition_Comparison_Operator = 13
	Condition_Comparison_CONTAINS_ALL          Condition_Comparison_Operator = 14
)

// Enum value maps for Condition_Comparison_Operator.
var (
	Condition_Comparison_Operator_name = map[int32]string{
		0:  "OPERATOR_UNSPECIFIED",
		1:  "EQUALS",
		2:  "NOT_EQUALS",
		3:  "LESS_THAN",
		4:  "LESS_THAN_OR_EQUAL",
		5:  "GREATER_THAN",
		6:  "GREATER_THAN_OR_EQUAL",
		7:  "CONTAINS",
		8:  "STARTS_WITH",
		9:  "ENDS_WITH",
		10: "MATCHES",
		11: "IN",
		12: "NOT_IN",
		13: "CONTAINS_ANY",
		14: "CONTAINS_ALL",
	}
	Condition_Comparison_Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED":  0,
		"EQUALS":                1,
		"NOT_EQUALS":            2,
		"LESS_THAN":             3,
		"LESS_THAN_OR_EQUAL":    4,
		"GREATER_THAN":          5,
		"GREATER_THAN_OR_EQUAL": 6,
		"CONTAINS":              7,
		"STARTS_WITH":           8,
		"ENDS_WITH":             9,
		"MATCHES":               10,
		"IN":                    11,
		"NOT_IN":                12,
		"CONTAINS_ANY":          13,
		"CONTAINS_ALL":          14,
	}
)

func (x Condition_Comparison_Operator) Enum() *Condition_Comparison_Operator {
	p := new(Condition_Comparison_Operator)
	*p = x
	return p
}

func (x Condition_Comparison_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Condition_Comparison_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_admin_v1_resolver_proto_enumTypes[2].Descriptor()
}

func (Condition_Comparison_Operator) Type() protoreflect.EnumType {
	return &file_confidence_flags_admin_v1_resolver_proto_enumTypes[2]
}

func (x Condition_Comparison_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Condition_Comparison_Operator.Descriptor instead.
func (Condition_Comparison_Operator) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 5, 0}
}

type Condition_ContextFieldComparison_Operator int32

const (
	Condition_ContextFieldComparison_OPERATOR_UNSPECIFIED  Condition_ContextFieldComparison_Operator = 0
	Condition_ContextFieldComparison_EQUALS                Condition_ContextFieldComparison_Operator = 1
	Condition_ContextFieldComparison_NOT_EQUALS            Condition_ContextFieldComparison_Operator = 2
	Condition_ContextFieldComparison_LESS_THAN             Condition_ContextFieldComparison_Operator = 3
	Condition_ContextFieldComparison_LESS_THAN_OR_EQUAL    Condition_ContextFieldComparison_Operator = 4
	Condition_ContextFieldComparison_GREATER_THAN          Condition_ContextFieldComparison_Operator = 5
	Condition_ContextFieldComparison_GREATER_THAN_OR_EQUAL Condition_ContextFieldComparison_Operator = 6
)

// Enum value maps for Condition_ContextFieldComparison_Operator.
var (
	Condition_ContextFieldComparison_Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "EQUALS",
		2: "NOT_EQUALS",
		3: "LESS_THAN",
		4: "LESS_THAN_OR_EQUAL",
		5: "GREATER_THAN",
		6: "GREATER_THAN_OR_EQUAL",
	}
	Condition_ContextFieldComparison_Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED":  0,
		"EQUALS":                1,
		"NOT_EQUALS":            2,
		"LESS_THAN":             3,
		"LESS_THAN_OR_EQUAL":    4,
		"GREATER_THAN":          5,
		"GREATER_THAN_OR_EQUAL": 6,
	}
)

func (x Condition_ContextFieldComparison_Operator) Enum() *Condition_ContextFieldComparison_Operator {
	p := new(Condition_ContextFieldComparison_Operator)
	*p = x
	return p
}

func (x Condition_ContextFieldComparison_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Condition_ContextFieldComparison_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_flags_admin_v1_resolver_proto_enumTypes[3].Descriptor()
}

func (Condition_ContextFieldComparison_Operator) Type() protoreflect.EnumType {
	return &file_confidence_flags_admin_v1_resolver_proto_enumTypes[3]
}

func (x Condition_ContextFieldComparison_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Condition_ContextFieldComparison_Operator.Descriptor instead.
func (Condition_ContextFieldComparison_Operator) EnumDescriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 6, 0}
}

// The full state for operating a flags resolver
type ResolverState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All active flags
	Flags []*Flag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	// All allocated segments, but without the `bitset_allocation` field set. The actual bitsets will be packed and sent
	// separately.
	SegmentsNoBitsets []*Segment `protobuf:"bytes,2,rep,name=segments_no_bitsets,json=segmentsNoBitsets,proto3" json:"segments_no_bitsets,omitempty"`
	// Packed bitsets for the segments
	Bitsets []*ResolverState_PackedBitset `protobuf:"bytes,5,rep,name=bitsets,proto3" json:"bitsets,omitempty"`
	// All clients
	Clients []*Client `protobuf:"bytes,6,rep,name=clients,proto3" json:"clients,omitempty"`
	// All client credentials
	ClientCredentials []*ClientCredential `protobuf:"bytes,7,rep,name=client_credentials,json=clientCredentials,proto3" json:"client_credentials,omitempty"`
	// The region of the account
	Region        ResolverState_Region `protobuf:"varint,8,opt,name=region,proto3,enum=confidence.flags.admin.v1.ResolverState_Region" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolverState) Reset() {
	*x = ResolverState{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverState) ProtoMessage() {}

func (x *ResolverState) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverState.ProtoReflect.Descriptor instead.
func (*ResolverState) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *ResolverState) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ResolverState) GetSegmentsNoBitsets() []*Segment {
	if x != nil {
		return x.SegmentsNoBitsets
	}
	return nil
}

func (x *ResolverState) GetBitsets() []*ResolverState_PackedBitset {
	if x != nil {
		return x.Bitsets
	}
	return nil
}

func (x *ResolverState) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ResolverState) GetClientCredentials() []*ClientCredential {
	if x != nil {
		return x.ClientCredentials
	}
	return nil
}

func (x *ResolverState) GetRegion() ResolverState_Region {
	if x != nil {
		return x.Region
	}
	return ResolverState_REGION_UNSPECIFIED
}

// A flag controlling how entities are assigned variants.
type Flag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the flag.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A description for the flag.
	Description string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	// Schema for the value of each variant.
	Schema *types.FlagSchema_StructFlagSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// List of variants for this flag.
	Variants []*Flag_Variant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	// The current state of the flag.
	State Flag_State `protobuf:"varint,4,opt,name=state,proto3,enum=confidence.flags.admin.v1.Flag_State" json:"state,omitempty"`
	// List of ordered rules that determines how entities are assigned to variants.
	Rules []*Flag_Rule `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	// List of clients that this flag is enabled for.
	Clients       []string `protobuf:"bytes,12,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetSchema() *types.FlagSchema_StructFlagSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Flag) GetVariants() []*Flag_Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Flag) GetState() Flag_State {
	if x != nil {
		return x.State
	}
	return Flag_STATE_UNSPECIFIED
}

func (x *Flag) GetRules() []*Flag_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Flag) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

// A reusable slice of an entity population.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the segment.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human-friendly name for the segment.
	DisplayName string `protobuf:"bytes,12,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The targeting that this segment adheres to.
	Targeting *types.Targeting `protobuf:"bytes,2,opt,name=targeting,proto3" json:"targeting,omitempty"`
	// How much of the total population that is allocated to this segment,
	// and the coordination with other segments.
	Allocation *Segment_Allocation `protobuf:"bytes,3,opt,name=allocation,proto3" json:"allocation,omitempty"`
	// A bitset representing the buckets that are allocated for this segment.
	BitsetAllocation *Segment_BitsetAllocation `protobuf:"bytes,6,opt,name=bitset_allocation,json=bitsetAllocation,proto3" json:"bitset_allocation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{2}
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Segment) GetTargeting() *types.Targeting {
	if x != nil {
		return x.Targeting
	}
	return nil
}

func (x *Segment) GetAllocation() *Segment_Allocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

func (x *Segment) GetBitsetAllocation() *Segment_BitsetAllocation {
	if x != nil {
		return x.BitsetAllocation
	}
	return nil
}

// Targeting condition (simplified)
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*Condition_TrueCondition
	//	*Condition_FalseCondition
	//	*Condition_And_
	//	*Condition_Or_
	//	*Condition_Not_
	//	*Condition_Comparison_
	//	*Condition_ContextFieldComparison_
	Condition     isCondition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetCondition() isCondition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Condition) GetTrueCondition() *Condition_True {
	if x != nil {
		if x, ok := x.Condition.(*Condition_TrueCondition); ok {
			return x.TrueCondition
		}
	}
	return nil
}

func (x *Condition) GetFalseCondition() *Condition_False {
	if x != nil {
		if x, ok := x.Condition.(*Condition_FalseCondition); ok {
			return x.FalseCondition
		}
	}
	return nil
}

func (x *Condition) GetAnd() *Condition_And {
	if x != nil {
		if x, ok := x.Condition.(*Condition_And_); ok {
			return x.And
		}
	}
	return nil
}

func (x *Condition) GetOr() *Condition_Or {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Or_); ok {
			return x.Or
		}
	}
	return nil
}

func (x *Condition) GetNot() *Condition_Not {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Not_); ok {
			return x.Not
		}
	}
	return nil
}

func (x *Condition) GetComparison() *Condition_Comparison {
	if x != nil {
		if x, ok := x.Condition.(*Condition_Comparison_); ok {
			return x.Comparison
		}
	}
	return nil
}

func (x *Condition) GetContextFieldComparison() *Condition_ContextFieldComparison {
	if x != nil {
		if x, ok := x.Condition.(*Condition_ContextFieldComparison_); ok {
			return x.ContextFieldComparison
		}
	}
	return nil
}

type isCondition_Condition interface {
	isCondition_Condition()
}

type Condition_TrueCondition struct {
	TrueCondition *Condition_True `protobuf:"bytes,1,opt,name=true_condition,json=trueCondition,proto3,oneof"`
}

type Condition_FalseCondition struct {
	FalseCondition *Condition_False `protobuf:"bytes,2,opt,name=false_condition,json=falseCondition,proto3,oneof"`
}

type Condition_And_ struct {
	And *Condition_And `protobuf:"bytes,3,opt,name=and,proto3,oneof"`
}

type Condition_Or_ struct {
	Or *Condition_Or `protobuf:"bytes,4,opt,name=or,proto3,oneof"`
}

type Condition_Not_ struct {
	Not *Condition_Not `protobuf:"bytes,5,opt,name=not,proto3,oneof"`
}

type Condition_Comparison_ struct {
	Comparison *Condition_Comparison `protobuf:"bytes,6,opt,name=comparison,proto3,oneof"`
}

type Condition_ContextFieldComparison_ struct {
	ContextFieldComparison *Condition_ContextFieldComparison `protobuf:"bytes,7,opt,name=context_field_comparison,json=contextFieldComparison,proto3,oneof"`
}

func (*Condition_TrueCondition) isCondition_Condition() {}

func (*Condition_FalseCondition) isCondition_Condition() {}

func (*Condition_And_) isCondition_Condition() {}

func (*Condition_Or_) isCondition_Condition() {}

func (*Condition_Not_) isCondition_Condition() {}

func (*Condition_Comparison_) isCondition_Condition() {}

func (*Condition_ContextFieldComparison_) isCondition_Condition() {}

// A client that can resolve flags
type Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the client.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human friendly name of the client.
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{4}
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Credentials for a client
type ClientCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the client credential.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The credential method used by this client.
	//
	// Types that are valid to be assigned to Credential:
	//
	//	*ClientCredential_ClientSecret_
	Credential    isClientCredential_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCredential) Reset() {
	*x = ClientCredential{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredential) ProtoMessage() {}

func (x *ClientCredential) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredential.ProtoReflect.Descriptor instead.
func (*ClientCredential) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{5}
}

func (x *ClientCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientCredential) GetCredential() isClientCredential_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ClientCredential) GetClientSecret() *ClientCredential_ClientSecret {
	if x != nil {
		if x, ok := x.Credential.(*ClientCredential_ClientSecret_); ok {
			return x.ClientSecret
		}
	}
	return nil
}

type isClientCredential_Credential interface {
	isClientCredential_Credential()
}

type ClientCredential_ClientSecret_ struct {
	// A simple plaintext secret.
	ClientSecret *ClientCredential_ClientSecret `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3,oneof"`
}

func (*ClientCredential_ClientSecret_) isClientCredential_Credential() {}

// A compressed bitset for a specific segment. The bitset will be gzipped, unless it's all ones, in which case the
// `full_bitset` field will be set instead.
type ResolverState_PackedBitset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The segment which this bitset belongs to
	Segment string `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	// Types that are valid to be assigned to Bitset:
	//
	//	*ResolverState_PackedBitset_GzippedBitset
	//	*ResolverState_PackedBitset_FullBitset
	Bitset        isResolverState_PackedBitset_Bitset `protobuf_oneof:"bitset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolverState_PackedBitset) Reset() {
	*x = ResolverState_PackedBitset{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverState_PackedBitset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverState_PackedBitset) ProtoMessage() {}

func (x *ResolverState_PackedBitset) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverState_PackedBitset.ProtoReflect.Descriptor instead.
func (*ResolverState_PackedBitset) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResolverState_PackedBitset) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *ResolverState_PackedBitset) GetBitset() isResolverState_PackedBitset_Bitset {
	if x != nil {
		return x.Bitset
	}
	return nil
}

func (x *ResolverState_PackedBitset) GetGzippedBitset() []byte {
	if x != nil {
		if x, ok := x.Bitset.(*ResolverState_PackedBitset_GzippedBitset); ok {
			return x.GzippedBitset
		}
	}
	return nil
}

func (x *ResolverState_PackedBitset) GetFullBitset() bool {
	if x != nil {
		if x, ok := x.Bitset.(*ResolverState_PackedBitset_FullBitset); ok {
			return x.FullBitset
		}
	}
	return false
}

type isResolverState_PackedBitset_Bitset interface {
	isResolverState_PackedBitset_Bitset()
}

type ResolverState_PackedBitset_GzippedBitset struct {
	// A gzip compressed bitset
	GzippedBitset []byte `protobuf:"bytes,2,opt,name=gzipped_bitset,json=gzippedBitset,proto3,oneof"`
}

type ResolverState_PackedBitset_FullBitset struct {
	// Set to true if all bits in the bitset are set
	FullBitset bool `protobuf:"varint,3,opt,name=full_bitset,json=fullBitset,proto3,oneof"`
}

func (*ResolverState_PackedBitset_GzippedBitset) isResolverState_PackedBitset_Bitset() {}

func (*ResolverState_PackedBitset_FullBitset) isResolverState_PackedBitset_Bitset() {}

// A possible named value the flag can assign.
type Flag_Variant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the variant.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value that this variant represents. A possibly nested json object.
	Value         *structpb.Struct `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Variant) Reset() {
	*x = Flag_Variant{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Variant) ProtoMessage() {}

func (x *Flag_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Variant.ProtoReflect.Descriptor instead.
func (*Flag_Variant) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Flag_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag_Variant) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

// A rule that decides how a subset of the flags variants are assigned.
type Flag_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the rule.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A reference to the segment that this rule uses to specify entities
	// that are eligible.
	Segment string `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	// Specification of how an entity should be randomly assigned to values.
	AssignmentSpec *Flag_Rule_AssignmentSpec `protobuf:"bytes,12,opt,name=assignment_spec,json=assignmentSpec,proto3" json:"assignment_spec,omitempty"`
	// Selector of what key to randomize on from the evaluation context.
	// "targeting_key" is the default if not specified
	TargetingKeySelector string `protobuf:"bytes,5,opt,name=targeting_key_selector,json=targetingKeySelector,proto3" json:"targeting_key_selector,omitempty"`
	// Decides if the rule should be enabled for resolve or not.
	Enabled bool `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Specifies if materializations are written to/read from
	MaterializationSpec *Flag_Rule_MaterializationSpec `protobuf:"bytes,13,opt,name=materialization_spec,json=materializationSpec,proto3" json:"materialization_spec,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Flag_Rule) Reset() {
	*x = Flag_Rule{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule) ProtoMessage() {}

func (x *Flag_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule.ProtoReflect.Descriptor instead.
func (*Flag_Rule) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Flag_Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag_Rule) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *Flag_Rule) GetAssignmentSpec() *Flag_Rule_AssignmentSpec {
	if x != nil {
		return x.AssignmentSpec
	}
	return nil
}

func (x *Flag_Rule) GetTargetingKeySelector() string {
	if x != nil {
		return x.TargetingKeySelector
	}
	return ""
}

func (x *Flag_Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flag_Rule) GetMaterializationSpec() *Flag_Rule_MaterializationSpec {
	if x != nil {
		return x.MaterializationSpec
	}
	return nil
}

// Specifies if materializations are written to/read from
type Flag_Rule_MaterializationSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feeds assignments into materialization
	WriteMaterialization string `protobuf:"bytes,1,opt,name=write_materialization,json=writeMaterialization,proto3" json:"write_materialization,omitempty"`
	// Reads assignments from materialization
	ReadMaterialization string `protobuf:"bytes,2,opt,name=read_materialization,json=readMaterialization,proto3" json:"read_materialization,omitempty"`
	// How materialization reads should be treated
	Mode          *Flag_Rule_MaterializationSpec_MaterializationReadMode `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_MaterializationSpec) Reset() {
	*x = Flag_Rule_MaterializationSpec{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_MaterializationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_MaterializationSpec) ProtoMessage() {}

func (x *Flag_Rule_MaterializationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_MaterializationSpec.ProtoReflect.Descriptor instead.
func (*Flag_Rule_MaterializationSpec) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Flag_Rule_MaterializationSpec) GetWriteMaterialization() string {
	if x != nil {
		return x.WriteMaterialization
	}
	return ""
}

func (x *Flag_Rule_MaterializationSpec) GetReadMaterialization() string {
	if x != nil {
		return x.ReadMaterialization
	}
	return ""
}

func (x *Flag_Rule_MaterializationSpec) GetMode() *Flag_Rule_MaterializationSpec_MaterializationReadMode {
	if x != nil {
		return x.Mode
	}
	return nil
}

// Describes how an entity is randomly assigned to a variant.
type Flag_Rule_AssignmentSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total number of buckets to consider when randomizing.
	BucketCount int32 `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	// A list that divides the total buckets into assignments
	Assignments   []*Flag_Rule_Assignment `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_AssignmentSpec) Reset() {
	*x = Flag_Rule_AssignmentSpec{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_AssignmentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_AssignmentSpec) ProtoMessage() {}

func (x *Flag_Rule_AssignmentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_AssignmentSpec.ProtoReflect.Descriptor instead.
func (*Flag_Rule_AssignmentSpec) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *Flag_Rule_AssignmentSpec) GetBucketCount() int32 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *Flag_Rule_AssignmentSpec) GetAssignments() []*Flag_Rule_Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

// Maps a range of buckets to a value assignment.
type Flag_Rule_Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier of this assignment.
	AssignmentId string `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	// Determines how the client should be assigned values.
	//
	// Types that are valid to be assigned to Assignment:
	//
	//	*Flag_Rule_Assignment_Variant
	//	*Flag_Rule_Assignment_Fallthrough
	//	*Flag_Rule_Assignment_ClientDefault
	Assignment isFlag_Rule_Assignment_Assignment `protobuf_oneof:"assignment"`
	// The range of buckets that the variant occupies.
	BucketRanges  []*Flag_Rule_BucketRange `protobuf:"bytes,5,rep,name=bucket_ranges,json=bucketRanges,proto3" json:"bucket_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_Assignment) Reset() {
	*x = Flag_Rule_Assignment{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_Assignment) ProtoMessage() {}

func (x *Flag_Rule_Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_Assignment.ProtoReflect.Descriptor instead.
func (*Flag_Rule_Assignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 2}
}

func (x *Flag_Rule_Assignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Flag_Rule_Assignment) GetAssignment() isFlag_Rule_Assignment_Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *Flag_Rule_Assignment) GetVariant() *Flag_Rule_Assignment_VariantAssignment {
	if x != nil {
		if x, ok := x.Assignment.(*Flag_Rule_Assignment_Variant); ok {
			return x.Variant
		}
	}
	return nil
}

func (x *Flag_Rule_Assignment) GetFallthrough() *Flag_Rule_Assignment_FallthroughAssignment {
	if x != nil {
		if x, ok := x.Assignment.(*Flag_Rule_Assignment_Fallthrough); ok {
			return x.Fallthrough
		}
	}
	return nil
}

func (x *Flag_Rule_Assignment) GetClientDefault() *Flag_Rule_Assignment_ClientDefaultAssignment {
	if x != nil {
		if x, ok := x.Assignment.(*Flag_Rule_Assignment_ClientDefault); ok {
			return x.ClientDefault
		}
	}
	return nil
}

func (x *Flag_Rule_Assignment) GetBucketRanges() []*Flag_Rule_BucketRange {
	if x != nil {
		return x.BucketRanges
	}
	return nil
}

type isFlag_Rule_Assignment_Assignment interface {
	isFlag_Rule_Assignment_Assignment()
}

type Flag_Rule_Assignment_Variant struct {
	// Assign a value from a variant.
	Variant *Flag_Rule_Assignment_VariantAssignment `protobuf:"bytes,2,opt,name=variant,proto3,oneof"`
}

type Flag_Rule_Assignment_Fallthrough struct {
	// Assign a value from the first rule after this one that matches.
	Fallthrough *Flag_Rule_Assignment_FallthroughAssignment `protobuf:"bytes,3,opt,name=fallthrough,proto3,oneof"`
}

type Flag_Rule_Assignment_ClientDefault struct {
	// Assign the default values in the client.
	ClientDefault *Flag_Rule_Assignment_ClientDefaultAssignment `protobuf:"bytes,4,opt,name=client_default,json=clientDefault,proto3,oneof"`
}

func (*Flag_Rule_Assignment_Variant) isFlag_Rule_Assignment_Assignment() {}

func (*Flag_Rule_Assignment_Fallthrough) isFlag_Rule_Assignment_Assignment() {}

func (*Flag_Rule_Assignment_ClientDefault) isFlag_Rule_Assignment_Assignment() {}

// The range of buckets that a variant occupies.
type Flag_Rule_BucketRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The start bucket (inclusive).
	Lower int32 `protobuf:"varint,1,opt,name=lower,proto3" json:"lower,omitempty"`
	// The end bucket (exclusive).
	Upper         int32 `protobuf:"varint,2,opt,name=upper,proto3" json:"upper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_BucketRange) Reset() {
	*x = Flag_Rule_BucketRange{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_BucketRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_BucketRange) ProtoMessage() {}

func (x *Flag_Rule_BucketRange) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_BucketRange.ProtoReflect.Descriptor instead.
func (*Flag_Rule_BucketRange) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 3}
}

func (x *Flag_Rule_BucketRange) GetLower() int32 {
	if x != nil {
		return x.Lower
	}
	return 0
}

func (x *Flag_Rule_BucketRange) GetUpper() int32 {
	if x != nil {
		return x.Upper
	}
	return 0
}

// How materialization reads should be treated
type Flag_Rule_MaterializationSpec_MaterializationReadMode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the materialization must match
	MaterializationMustMatch bool `protobuf:"varint,1,opt,name=materialization_must_match,json=materializationMustMatch,proto3" json:"materialization_must_match,omitempty"`
	// Whether segment targeting can be ignored
	SegmentTargetingCanBeIgnored bool `protobuf:"varint,2,opt,name=segment_targeting_can_be_ignored,json=segmentTargetingCanBeIgnored,proto3" json:"segment_targeting_can_be_ignored,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Flag_Rule_MaterializationSpec_MaterializationReadMode) Reset() {
	*x = Flag_Rule_MaterializationSpec_MaterializationReadMode{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_MaterializationSpec_MaterializationReadMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_MaterializationSpec_MaterializationReadMode) ProtoMessage() {}

func (x *Flag_Rule_MaterializationSpec_MaterializationReadMode) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_MaterializationSpec_MaterializationReadMode.ProtoReflect.Descriptor instead.
func (*Flag_Rule_MaterializationSpec_MaterializationReadMode) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 0, 0}
}

func (x *Flag_Rule_MaterializationSpec_MaterializationReadMode) GetMaterializationMustMatch() bool {
	if x != nil {
		return x.MaterializationMustMatch
	}
	return false
}

func (x *Flag_Rule_MaterializationSpec_MaterializationReadMode) GetSegmentTargetingCanBeIgnored() bool {
	if x != nil {
		return x.SegmentTargetingCanBeIgnored
	}
	return false
}

// Assignment of a variant
type Flag_Rule_Assignment_VariantAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to a variant in the flag.
	Variant       string `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_Assignment_VariantAssignment) Reset() {
	*x = Flag_Rule_Assignment_VariantAssignment{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_Assignment_VariantAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_Assignment_VariantAssignment) ProtoMessage() {}

func (x *Flag_Rule_Assignment_VariantAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_Assignment_VariantAssignment.ProtoReflect.Descriptor instead.
func (*Flag_Rule_Assignment_VariantAssignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 2, 0}
}

func (x *Flag_Rule_Assignment_VariantAssignment) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

// No value will be assigned and passed on to the next rule
type Flag_Rule_Assignment_FallthroughAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_Assignment_FallthroughAssignment) Reset() {
	*x = Flag_Rule_Assignment_FallthroughAssignment{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_Assignment_FallthroughAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_Assignment_FallthroughAssignment) ProtoMessage() {}

func (x *Flag_Rule_Assignment_FallthroughAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_Assignment_FallthroughAssignment.ProtoReflect.Descriptor instead.
func (*Flag_Rule_Assignment_FallthroughAssignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 2, 1}
}

// No variant will be assigned and the client should return the
// configured default values.
type Flag_Rule_Assignment_ClientDefaultAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag_Rule_Assignment_ClientDefaultAssignment) Reset() {
	*x = Flag_Rule_Assignment_ClientDefaultAssignment{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag_Rule_Assignment_ClientDefaultAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag_Rule_Assignment_ClientDefaultAssignment) ProtoMessage() {}

func (x *Flag_Rule_Assignment_ClientDefaultAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag_Rule_Assignment_ClientDefaultAssignment.ProtoReflect.Descriptor instead.
func (*Flag_Rule_Assignment_ClientDefaultAssignment) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{1, 1, 2, 2}
}

// Allocation and coordination of the segment.
type Segment_Allocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fraction of entity population that is eligible for this segment.
	Proportion string `protobuf:"bytes,1,opt,name=proportion,proto3" json:"proportion,omitempty"`
	// Set of tags that can be used to coordinate this segment with others.
	ExclusivityTags []string `protobuf:"bytes,3,rep,name=exclusivity_tags,json=exclusivityTags,proto3" json:"exclusivity_tags,omitempty"`
	// List of tags that this segment is exclusive to
	ExclusiveTo   []string `protobuf:"bytes,4,rep,name=exclusive_to,json=exclusiveTo,proto3" json:"exclusive_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment_Allocation) Reset() {
	*x = Segment_Allocation{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment_Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment_Allocation) ProtoMessage() {}

func (x *Segment_Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment_Allocation.ProtoReflect.Descriptor instead.
func (*Segment_Allocation) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Segment_Allocation) GetProportion() string {
	if x != nil {
		return x.Proportion
	}
	return ""
}

func (x *Segment_Allocation) GetExclusivityTags() []string {
	if x != nil {
		return x.ExclusivityTags
	}
	return nil
}

func (x *Segment_Allocation) GetExclusiveTo() []string {
	if x != nil {
		return x.ExclusiveTo
	}
	return nil
}

// A bit set where each bit represents a fixed fraction of the entity
// population.
type Segment_BitsetAllocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Byte encoded bitset.
	Bitset        []byte `protobuf:"bytes,1,opt,name=bitset,proto3" json:"bitset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment_BitsetAllocation) Reset() {
	*x = Segment_BitsetAllocation{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment_BitsetAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment_BitsetAllocation) ProtoMessage() {}

func (x *Segment_BitsetAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment_BitsetAllocation.ProtoReflect.Descriptor instead.
func (*Segment_BitsetAllocation) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Segment_BitsetAllocation) GetBitset() []byte {
	if x != nil {
		return x.Bitset
	}
	return nil
}

type Condition_True struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_True) Reset() {
	*x = Condition_True{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_True) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_True) ProtoMessage() {}

func (x *Condition_True) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_True.ProtoReflect.Descriptor instead.
func (*Condition_True) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 0}
}

type Condition_False struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_False) Reset() {
	*x = Condition_False{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_False) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_False) ProtoMessage() {}

func (x *Condition_False) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_False.ProtoReflect.Descriptor instead.
func (*Condition_False) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 1}
}

type Condition_And struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_And) Reset() {
	*x = Condition_And{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_And) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_And) ProtoMessage() {}

func (x *Condition_And) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_And.ProtoReflect.Descriptor instead.
func (*Condition_And) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Condition_And) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Condition_Or struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*Condition           `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_Or) Reset() {
	*x = Condition_Or{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_Or) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Or) ProtoMessage() {}

func (x *Condition_Or) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Or.ProtoReflect.Descriptor instead.
func (*Condition_Or) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Condition_Or) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Condition_Not struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Condition             `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_Not) Reset() {
	*x = Condition_Not{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_Not) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Not) ProtoMessage() {}

func (x *Condition_Not) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Not.ProtoReflect.Descriptor instead.
func (*Condition_Not) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 4}
}

func (x *Condition_Not) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type Condition_Comparison struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Field         string                        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      Condition_Comparison_Operator `protobuf:"varint,2,opt,name=operator,proto3,enum=confidence.flags.admin.v1.Condition_Comparison_Operator" json:"operator,omitempty"`
	Value         *structpb.Value               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_Comparison) Reset() {
	*x = Condition_Comparison{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_Comparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Comparison) ProtoMessage() {}

func (x *Condition_Comparison) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Comparison.ProtoReflect.Descriptor instead.
func (*Condition_Comparison) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 5}
}

func (x *Condition_Comparison) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition_Comparison) GetOperator() Condition_Comparison_Operator {
	if x != nil {
		return x.Operator
	}
	return Condition_Comparison_OPERATOR_UNSPECIFIED
}

func (x *Condition_Comparison) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Condition_ContextFieldComparison struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Field         string                                    `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      Condition_ContextFieldComparison_Operator `protobuf:"varint,2,opt,name=operator,proto3,enum=confidence.flags.admin.v1.Condition_ContextFieldComparison_Operator" json:"operator,omitempty"`
	OtherField    string                                    `protobuf:"bytes,3,opt,name=other_field,json=otherField,proto3" json:"other_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_ContextFieldComparison) Reset() {
	*x = Condition_ContextFieldComparison{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_ContextFieldComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_ContextFieldComparison) ProtoMessage() {}

func (x *Condition_ContextFieldComparison) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_ContextFieldComparison.ProtoReflect.Descriptor instead.
func (*Condition_ContextFieldComparison) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{3, 6}
}

func (x *Condition_ContextFieldComparison) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition_ContextFieldComparison) GetOperator() Condition_ContextFieldComparison_Operator {
	if x != nil {
		return x.Operator
	}
	return Condition_ContextFieldComparison_OPERATOR_UNSPECIFIED
}

func (x *Condition_ContextFieldComparison) GetOtherField() string {
	if x != nil {
		return x.OtherField
	}
	return ""
}

// A client secret credential
type ClientCredential_ClientSecret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The secret value
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCredential_ClientSecret) Reset() {
	*x = ClientCredential_ClientSecret{}
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCredential_ClientSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredential_ClientSecret) ProtoMessage() {}

func (x *ClientCredential_ClientSecret) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_flags_admin_v1_resolver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredential_ClientSecret.ProtoReflect.Descriptor instead.
func (*ClientCredential_ClientSecret) Descriptor() ([]byte, []int) {
	return file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ClientCredential_ClientSecret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_confidence_flags_admin_v1_resolver_proto protoreflect.FileDescriptor

const file_confidence_flags_admin_v1_resolver_proto_rawDesc = "" +
	"\n" +
	"(confidence/flags/admin/v1/resolver.proto\x12\x19confidence.flags.admin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a%confidence/flags/types/v1/types.proto\x1a&confidence/flags/types/v1/target.proto\"\x8d\x05\n" +
	"\rResolverState\x125\n" +
	"\x05flags\x18\x01 \x03(\v2\x1f.confidence.flags.admin.v1.FlagR\x05flags\x12R\n" +
	"\x13segments_no_bitsets\x18\x02 \x03(\v2\".confidence.flags.admin.v1.SegmentR\x11segmentsNoBitsets\x12O\n" +
	"\abitsets\x18\x05 \x03(\v25.confidence.flags.admin.v1.ResolverState.PackedBitsetR\abitsets\x12;\n" +
	"\aclients\x18\x06 \x03(\v2!.confidence.flags.admin.v1.ClientR\aclients\x12Z\n" +
	"\x12client_credentials\x18\a \x03(\v2+.confidence.flags.admin.v1.ClientCredentialR\x11clientCredentials\x12G\n" +
	"\x06region\x18\b \x01(\x0e2/.confidence.flags.admin.v1.ResolverState.RegionR\x06region\x1a~\n" +
	"\fPackedBitset\x12\x18\n" +
	"\asegment\x18\x01 \x01(\tR\asegment\x12'\n" +
	"\x0egzipped_bitset\x18\x02 \x01(\fH\x00R\rgzippedBitset\x12!\n" +
	"\vfull_bitset\x18\x03 \x01(\bH\x00R\n" +
	"fullBitsetB\b\n" +
	"\x06bitset\">\n" +
	"\x06Region\x12\x16\n" +
	"\x12REGION_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREGION_EU\x10\x01\x12\r\n" +
	"\tREGION_US\x10\x02\"\xc2\x0f\n" +
	"\x04Flag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12N\n" +
	"\x06schema\x18\x02 \x01(\v26.confidence.flags.types.v1.FlagSchema.StructFlagSchemaR\x06schema\x12C\n" +
	"\bvariants\x18\x03 \x03(\v2'.confidence.flags.admin.v1.Flag.VariantR\bvariants\x12;\n" +
	"\x05state\x18\x04 \x01(\x0e2%.confidence.flags.admin.v1.Flag.StateR\x05state\x12:\n" +
	"\x05rules\x18\x05 \x03(\v2$.confidence.flags.admin.v1.Flag.RuleR\x05rules\x12\x18\n" +
	"\aclients\x18\f \x03(\tR\aclients\x1aL\n" +
	"\aVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\x1a\xd3\v\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asegment\x18\x02 \x01(\tR\asegment\x12\\\n" +
	"\x0fassignment_spec\x18\f \x01(\v23.confidence.flags.admin.v1.Flag.Rule.AssignmentSpecR\x0eassignmentSpec\x124\n" +
	"\x16targeting_key_selector\x18\x05 \x01(\tR\x14targetingKeySelector\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\x12k\n" +
	"\x14materialization_spec\x18\r \x01(\v28.confidence.flags.admin.v1.Flag.Rule.MaterializationSpecR\x13materializationSpec\x1a\x85\x03\n" +
	"\x13MaterializationSpec\x123\n" +
	"\x15write_materialization\x18\x01 \x01(\tR\x14writeMaterialization\x121\n" +
	"\x14read_materialization\x18\x02 \x01(\tR\x13readMaterialization\x12d\n" +
	"\x04mode\x18\x03 \x01(\v2P.confidence.flags.admin.v1.Flag.Rule.MaterializationSpec.MaterializationReadModeR\x04mode\x1a\x9f\x01\n" +
	"\x17MaterializationReadMode\x12<\n" +
	"\x1amaterialization_must_match\x18\x01 \x01(\bR\x18materializationMustMatch\x12F\n" +
	" segment_targeting_can_be_ignored\x18\x02 \x01(\bR\x1csegmentTargetingCanBeIgnored\x1a\x86\x01\n" +
	"\x0eAssignmentSpec\x12!\n" +
	"\fbucket_count\x18\x01 \x01(\x05R\vbucketCount\x12Q\n" +
	"\vassignments\x18\x02 \x03(\v2/.confidence.flags.admin.v1.Flag.Rule.AssignmentR\vassignments\x1a\xb5\x04\n" +
	"\n" +
	"Assignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12]\n" +
	"\avariant\x18\x02 \x01(\v2A.confidence.flags.admin.v1.Flag.Rule.Assignment.VariantAssignmentH\x00R\avariant\x12i\n" +
	"\vfallthrough\x18\x03 \x01(\v2E.confidence.flags.admin.v1.Flag.Rule.Assignment.FallthroughAssignmentH\x00R\vfallthrough\x12p\n" +
	"\x0eclient_default\x18\x04 \x01(\v2G.confidence.flags.admin.v1.Flag.Rule.Assignment.ClientDefaultAssignmentH\x00R\rclientDefault\x12U\n" +
	"\rbucket_ranges\x18\x05 \x03(\v20.confidence.flags.admin.v1.Flag.Rule.BucketRangeR\fbucketRanges\x1a-\n" +
	"\x11VariantAssignment\x12\x18\n" +
	"\avariant\x18\x01 \x01(\tR\avariant\x1a\x17\n" +
	"\x15FallthroughAssignment\x1a\x19\n" +
	"\x17ClientDefaultAssignmentB\f\n" +
	"\n" +
	"assignment\x1a9\n" +
	"\vBucketRange\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\x05R\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\x05R\x05upper\"8\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x02\"\xdd\x03\n" +
	"\aSegment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\f \x01(\tR\vdisplayName\x12B\n" +
	"\ttargeting\x18\x02 \x01(\v2$.confidence.flags.types.v1.TargetingR\ttargeting\x12M\n" +
	"\n" +
	"allocation\x18\x03 \x01(\v2-.confidence.flags.admin.v1.Segment.AllocationR\n" +
	"allocation\x12`\n" +
	"\x11bitset_allocation\x18\x06 \x01(\v23.confidence.flags.admin.v1.Segment.BitsetAllocationR\x10bitsetAllocation\x1az\n" +
	"\n" +
	"Allocation\x12\x1e\n" +
	"\n" +
	"proportion\x18\x01 \x01(\tR\n" +
	"proportion\x12)\n" +
	"\x10exclusivity_tags\x18\x03 \x03(\tR\x0fexclusivityTags\x12!\n" +
	"\fexclusive_to\x18\x04 \x03(\tR\vexclusiveTo\x1a*\n" +
	"\x10BitsetAllocation\x12\x16\n" +
	"\x06bitset\x18\x01 \x01(\fR\x06bitset\"\xb9\f\n" +
	"\tCondition\x12R\n" +
	"\x0etrue_condition\x18\x01 \x01(\v2).confidence.flags.admin.v1.Condition.TrueH\x00R\rtrueCondition\x12U\n" +
	"\x0ffalse_condition\x18\x02 \x01(\v2*.confidence.flags.admin.v1.Condition.FalseH\x00R\x0efalseCondition\x12<\n" +
	"\x03and\x18\x03 \x01(\v2(.confidence.flags.admin.v1.Condition.AndH\x00R\x03and\x129\n" +
	"\x02or\x18\x04 \x01(\v2'.confidence.flags.admin.v1.Condition.OrH\x00R\x02or\x12<\n" +
	"\x03not\x18\x05 \x01(\v2(.confidence.flags.admin.v1.Condition.NotH\x00R\x03not\x12Q\n" +
	"\n" +
	"comparison\x18\x06 \x01(\v2/.confidence.flags.admin.v1.Condition.ComparisonH\x00R\n" +
	"comparison\x12w\n" +
	"\x18context_field_comparison\x18\a \x01(\v2;.confidence.flags.admin.v1.Condition.ContextFieldComparisonH\x00R\x16contextFieldComparison\x1a\x06\n" +
	"\x04True\x1a\a\n" +
	"\x05False\x1aK\n" +
	"\x03And\x12D\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2$.confidence.flags.admin.v1.ConditionR\n" +
	"conditions\x1aJ\n" +
	"\x02Or\x12D\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2$.confidence.flags.admin.v1.ConditionR\n" +
	"conditions\x1aI\n" +
	"\x03Not\x12B\n" +
	"\tcondition\x18\x01 \x01(\v2$.confidence.flags.admin.v1.ConditionR\tcondition\x1a\xb0\x03\n" +
	"\n" +
	"Comparison\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12T\n" +
	"\boperator\x18\x02 \x01(\x0e28.confidence.flags.admin.v1.Condition.Comparison.OperatorR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\x87\x02\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06EQUALS\x10\x01\x12\x0e\n" +
	"\n" +
	"NOT_EQUALS\x10\x02\x12\r\n" +
	"\tLESS_THAN\x10\x03\x12\x16\n" +
	"\x12LESS_THAN_OR_EQUAL\x10\x04\x12\x10\n" +
	"\fGREATER_THAN\x10\x05\x12\x19\n" +
	"\x15GREATER_THAN_OR_EQUAL\x10\x06\x12\f\n" +
	"\bCONTAINS\x10\a\x12\x0f\n" +
	"\vSTARTS_WITH\x10\b\x12\r\n" +
	"\tENDS_WITH\x10\t\x12\v\n" +
	"\aMATCHES\x10\n" +
	"\x12\x06\n" +
	"\x02IN\x10\v\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\f\x12\x10\n" +
	"\fCONTAINS_ANY\x10\r\x12\x10\n" +
	"\fCONTAINS_ALL\x10\x0e\x1a\xc8\x02\n" +
	"\x16ContextFieldComparison\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12`\n" +
	"\boperator\x18\x02 \x01(\x0e2D.confidence.flags.admin.v1.Condition.ContextFieldComparison.OperatorR\boperator\x12\x1f\n" +
	"\vother_field\x18\x03 \x01(\tR\n" +
	"otherField\"\x94\x01\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06EQUALS\x10\x01\x12\x0e\n" +
	"\n" +
	"NOT_EQUALS\x10\x02\x12\r\n" +
	"\tLESS_THAN\x10\x03\x12\x16\n" +
	"\x12LESS_THAN_OR_EQUAL\x10\x04\x12\x10\n" +
	"\fGREATER_THAN\x10\x05\x12\x19\n" +
	"\x15GREATER_THAN_OR_EQUAL\x10\x06B\v\n" +
	"\tcondition\"?\n" +
	"\x06Client\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\xbd\x01\n" +
	"\x10ClientCredential\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12_\n" +
	"\rclient_secret\x18\x03 \x01(\v28.confidence.flags.admin.v1.ClientCredential.ClientSecretH\x00R\fclientSecret\x1a&\n" +
	"\fClientSecret\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secretB\f\n" +
	"\n" +
	"credentialB\x9c\x01\n" +
	")com.spotify.confidence.sdk.flags.admin.v1B\rResolverProtoP\x01Z^github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/adminb\x06proto3"

var (
	file_confidence_flags_admin_v1_resolver_proto_rawDescOnce sync.Once
	file_confidence_flags_admin_v1_resolver_proto_rawDescData []byte
)

func file_confidence_flags_admin_v1_resolver_proto_rawDescGZIP() []byte {
	file_confidence_flags_admin_v1_resolver_proto_rawDescOnce.Do(func() {
		file_confidence_flags_admin_v1_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_flags_admin_v1_resolver_proto_rawDesc), len(file_confidence_flags_admin_v1_resolver_proto_rawDesc)))
	})
	return file_confidence_flags_admin_v1_resolver_proto_rawDescData
}

var file_confidence_flags_admin_v1_resolver_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_confidence_flags_admin_v1_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_confidence_flags_admin_v1_resolver_proto_goTypes = []any{
	(ResolverState_Region)(0),                      // 0: confidence.flags.admin.v1.ResolverState.Region
	(Flag_State)(0),                                // 1: confidence.flags.admin.v1.Flag.State
	(Condition_Comparison_Operator)(0),             // 2: confidence.flags.admin.v1.Condition.Comparison.Operator
	(Condition_ContextFieldComparison_Operator)(0), // 3: confidence.flags.admin.v1.Condition.ContextFieldComparison.Operator
	(*ResolverState)(nil),                          // 4: confidence.flags.admin.v1.ResolverState
	(*Flag)(nil),                                   // 5: confidence.flags.admin.v1.Flag
	(*Segment)(nil),                                // 6: confidence.flags.admin.v1.Segment
	(*Condition)(nil),                              // 7: confidence.flags.admin.v1.Condition
	(*Client)(nil),                                 // 8: confidence.flags.admin.v1.Client
	(*ClientCredential)(nil),                       // 9: confidence.flags.admin.v1.ClientCredential
	(*ResolverState_PackedBitset)(nil),             // 10: confidence.flags.admin.v1.ResolverState.PackedBitset
	(*Flag_Variant)(nil),                           // 11: confidence.flags.admin.v1.Flag.Variant
	(*Flag_Rule)(nil),                              // 12: confidence.flags.admin.v1.Flag.Rule
	(*Flag_Rule_MaterializationSpec)(nil),          // 13: confidence.flags.admin.v1.Flag.Rule.MaterializationSpec
	(*Flag_Rule_AssignmentSpec)(nil),               // 14: confidence.flags.admin.v1.Flag.Rule.AssignmentSpec
	(*Flag_Rule_Assignment)(nil),                   // 15: confidence.flags.admin.v1.Flag.Rule.Assignment
	(*Flag_Rule_BucketRange)(nil),                  // 16: confidence.flags.admin.v1.Flag.Rule.BucketRange
	(*Flag_Rule_MaterializationSpec_MaterializationReadMode)(nil), // 17: confidence.flags.admin.v1.Flag.Rule.MaterializationSpec.MaterializationReadMode
	(*Flag_Rule_Assignment_VariantAssignment)(nil),                // 18: confidence.flags.admin.v1.Flag.Rule.Assignment.VariantAssignment
	(*Flag_Rule_Assignment_FallthroughAssignment)(nil),            // 19: confidence.flags.admin.v1.Flag.Rule.Assignment.FallthroughAssignment
	(*Flag_Rule_Assignment_ClientDefaultAssignment)(nil),          // 20: confidence.flags.admin.v1.Flag.Rule.Assignment.ClientDefaultAssignment
	(*Segment_Allocation)(nil),                                    // 21: confidence.flags.admin.v1.Segment.Allocation
	(*Segment_BitsetAllocation)(nil),                              // 22: confidence.flags.admin.v1.Segment.BitsetAllocation
	(*Condition_True)(nil),                                        // 23: confidence.flags.admin.v1.Condition.True
	(*Condition_False)(nil),                                       // 24: confidence.flags.admin.v1.Condition.False
	(*Condition_And)(nil),                                         // 25: confidence.flags.admin.v1.Condition.And
	(*Condition_Or)(nil),                                          // 26: confidence.flags.admin.v1.Condition.Or
	(*Condition_Not)(nil),                                         // 27: confidence.flags.admin.v1.Condition.Not
	(*Condition_Comparison)(nil),                                  // 28: confidence.flags.admin.v1.Condition.Comparison
	(*Condition_ContextFieldComparison)(nil),                      // 29: confidence.flags.admin.v1.Condition.ContextFieldComparison
	(*ClientCredential_ClientSecret)(nil),                         // 30: confidence.flags.admin.v1.ClientCredential.ClientSecret
	(*types.FlagSchema_StructFlagSchema)(nil),                     // 31: confidence.flags.types.v1.FlagSchema.StructFlagSchema
	(*types.Targeting)(nil),                                       // 32: confidence.flags.types.v1.Targeting
	(*structpb.Struct)(nil),                                       // 33: google.protobuf.Struct
	(*structpb.Value)(nil),                                        // 34: google.protobuf.Value
}
var file_confidence_flags_admin_v1_resolver_proto_depIdxs = []int32{
	5,  // 0: confidence.flags.admin.v1.ResolverState.flags:type_name -> confidence.flags.admin.v1.Flag
	6,  // 1: confidence.flags.admin.v1.ResolverState.segments_no_bitsets:type_name -> confidence.flags.admin.v1.Segment
	10, // 2: confidence.flags.admin.v1.ResolverState.bitsets:type_name -> confidence.flags.admin.v1.ResolverState.PackedBitset
	8,  // 3: confidence.flags.admin.v1.ResolverState.clients:type_name -> confidence.flags.admin.v1.Client
	9,  // 4: confidence.flags.admin.v1.ResolverState.client_credentials:type_name -> confidence.flags.admin.v1.ClientCredential
	0,  // 5: confidence.flags.admin.v1.ResolverState.region:type_name -> confidence.flags.admin.v1.ResolverState.Region
	31, // 6: confidence.flags.admin.v1.Flag.schema:type_name -> confidence.flags.types.v1.FlagSchema.StructFlagSchema
	11, // 7: confidence.flags.admin.v1.Flag.variants:type_name -> confidence.flags.admin.v1.Flag.Variant
	1,  // 8: confidence.flags.admin.v1.Flag.state:type_name -> confidence.flags.admin.v1.Flag.State
	12, // 9: confidence.flags.admin.v1.Flag.rules:type_name -> confidence.flags.admin.v1.Flag.Rule
	32, // 10: confidence.flags.admin.v1.Segment.targeting:type_name -> confidence.flags.types.v1.Targeting
	21, // 11: confidence.flags.admin.v1.Segment.allocation:type_name -> confidence.flags.admin.v1.Segment.Allocation
	22, // 12: confidence.flags.admin.v1.Segment.bitset_allocation:type_name -> confidence.flags.admin.v1.Segment.BitsetAllocation
	23, // 13: confidence.flags.admin.v1.Condition.true_condition:type_name -> confidence.flags.admin.v1.Condition.True
	24, // 14: confidence.flags.admin.v1.Condition.false_condition:type_name -> confidence.flags.admin.v1.Condition.False
	25, // 15: confidence.flags.admin.v1.Condition.and:type_name -> confidence.flags.admin.v1.Condition.And
	26, // 16: confidence.flags.admin.v1.Condition.or:type_name -> confidence.flags.admin.v1.Condition.Or
	27, // 17: confidence.flags.admin.v1.Condition.not:type_name -> confidence.flags.admin.v1.Condition.Not
	28, // 18: confidence.flags.admin.v1.Condition.comparison:type_name -> confidence.flags.admin.v1.Condition.Comparison
	29, // 19: confidence.flags.admin.v1.Condition.context_field_comparison:type_name -> confidence.flags.admin.v1.Condition.ContextFieldComparison
	30, // 20: confidence.flags.admin.v1.ClientCredential.client_secret:type_name -> confidence.flags.admin.v1.ClientCredential.ClientSecret
	33, // 21: confidence.flags.admin.v1.Flag.Variant.value:type_name -> google.protobuf.Struct
	14, // 22: confidence.flags.admin.v1.Flag.Rule.assignment_spec:type_name -> confidence.flags.admin.v1.Flag.Rule.AssignmentSpec
	13, // 23: confidence.flags.admin.v1.Flag.Rule.materialization_spec:type_name -> confidence.flags.admin.v1.Flag.Rule.MaterializationSpec
	17, // 24: confidence.flags.admin.v1.Flag.Rule.MaterializationSpec.mode:type_name -> confidence.flags.admin.v1.Flag.Rule.MaterializationSpec.MaterializationReadMode
	15, // 25: confidence.flags.admin.v1.Flag.Rule.AssignmentSpec.assignments:type_name -> confidence.flags.admin.v1.Flag.Rule.Assignment
	18, // 26: confidence.flags.admin.v1.Flag.Rule.Assignment.variant:type_name -> confidence.flags.admin.v1.Flag.Rule.Assignment.VariantAssignment
	19, // 27: confidence.flags.admin.v1.Flag.Rule.Assignment.fallthrough:type_name -> confidence.flags.admin.v1.Flag.Rule.Assignment.FallthroughAssignment
	20, // 28: confidence.flags.admin.v1.Flag.Rule.Assignment.client_default:type_name -> confidence.flags.admin.v1.Flag.Rule.Assignment.ClientDefaultAssignment
	16, // 29: confidence.flags.admin.v1.Flag.Rule.Assignment.bucket_ranges:type_name -> confidence.flags.admin.v1.Flag.Rule.BucketRange
	7,  // 30: confidence.flags.admin.v1.Condition.And.conditions:type_name -> confidence.flags.admin.v1.Condition
	7,  // 31: confidence.flags.admin.v1.Condition.Or.conditions:type_name -> confidence.flags.admin.v1.Condition
	7,  // 32: confidence.flags.admin.v1.Condition.Not.condition:type_name -> confidence.flags.admin.v1.Condition
	2,  // 33: confidence.flags.admin.v1.Condition.Comparison.operator:type_name -> confidence.flags.admin.v1.Condition.Comparison.Operator
	34, // 34: confidence.flags.admin.v1.Condition.Comparison.value:type_name -> google.protobuf.Value
	3,  // 35: confidence.flags.admin.v1.Condition.ContextFieldComparison.operator:type_name -> confidence.flags.admin.v1.Condition.ContextFieldComparison.Operator
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_confidence_flags_admin_v1_resolver_proto_init() }
func file_confidence_flags_admin_v1_resolver_proto_init() {
	if File_confidence_flags_admin_v1_resolver_proto != nil {
		return
	}
	file_confidence_flags_admin_v1_resolver_proto_msgTypes[3].OneofWrappers = []any{
		(*Condition_TrueCondition)(nil),
		(*Condition_FalseCondition)(nil),
		(*Condition_And_)(nil),
		(*Condition_Or_)(nil),
		(*Condition_Not_)(nil),
		(*Condition_Comparison_)(nil),
		(*Condition_ContextFieldComparison_)(nil),
	}
	file_confidence_flags_admin_v1_resolver_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientCredential_ClientSecret_)(nil),
	}
	file_confidence_flags_admin_v1_resolver_proto_msgTypes[6].OneofWrappers = []any{
		(*ResolverState_PackedBitset_GzippedBitset)(nil),
		(*ResolverState_PackedBitset_FullBitset)(nil),
	}
	file_confidence_flags_admin_v1_resolver_proto_msgTypes[11].OneofWrappers = []any{
		(*Flag_Rule_Assignment_Variant)(nil),
		(*Flag_Rule_Assignment_Fallthrough)(nil),
		(*Flag_Rule_Assignment_ClientDefault)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_flags_admin_v1_resolver_proto_rawDesc), len(file_confidence_flags_admin_v1_resolver_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_flags_admin_v1_resolver_proto_goTypes,
		DependencyIndexes: file_confidence_flags_admin_v1_resolver_proto_depIdxs,
		EnumInfos:         file_confidence_flags_admin_v1_resolver_proto_enumTypes,
		MessageInfos:      file_confidence_flags_admin_v1_resolver_proto_msgTypes,
	}.Build()
	File_confidence_flags_admin_v1_resolver_proto = out.File
	file_confidence_flags_admin_v1_resolver_proto_goTypes = nil
	file_confidence_flags_admin_v1_resolver_proto_depIdxs = nil
}
