// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/events/v1/api.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to publish events.
type PublishEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client secret used to authenticate the request, on the format [A-Za-z0-9]+.
	ClientSecret string `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// The list of events to publish.
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// The client time when the request was sent.
	SendTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	// Information about the SDK used to initiate the request.
	Sdk           *Sdk `protobuf:"bytes,4,opt,name=sdk,proto3" json:"sdk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventsRequest) Reset() {
	*x = PublishEventsRequest{}
	mi := &file_confidence_events_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventsRequest) ProtoMessage() {}

func (x *PublishEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventsRequest.ProtoReflect.Descriptor instead.
func (*PublishEventsRequest) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEventsRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *PublishEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PublishEventsRequest) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *PublishEventsRequest) GetSdk() *Sdk {
	if x != nil {
		return x.Sdk
	}
	return nil
}

// Response of the publish events call.
type PublishEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Possible errors that occurred during the publish request.
	Errors        []*EventError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventsResponse) Reset() {
	*x = PublishEventsResponse{}
	mi := &file_confidence_events_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventsResponse) ProtoMessage() {}

func (x *PublishEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventsResponse.ProtoReflect.Descriptor instead.
func (*PublishEventsResponse) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventsResponse) GetErrors() []*EventError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_confidence_events_v1_api_proto protoreflect.FileDescriptor

const file_confidence_events_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x1econfidence/events/v1/api.proto\x12\x14confidence.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a confidence/events/v1/types.proto\"\xd6\x01\n" +
	"\x14PublishEventsRequest\x12#\n" +
	"\rclient_secret\x18\x01 \x01(\tR\fclientSecret\x123\n" +
	"\x06events\x18\x02 \x03(\v2\x1b.confidence.events.v1.EventR\x06events\x127\n" +
	"\tsend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\x12+\n" +
	"\x03sdk\x18\x04 \x01(\v2\x19.confidence.events.v1.SdkR\x03sdk\"Q\n" +
	"\x15PublishEventsResponse\x128\n" +
	"\x06errors\x18\x01 \x03(\v2 .confidence.events.v1.EventErrorR\x06errors2y\n" +
	"\rEventsService\x12h\n" +
	"\rPublishEvents\x12*.confidence.events.v1.PublishEventsRequest\x1a+.confidence.events.v1.PublishEventsResponseB\x93\x01\n" +
	"$com.spotify.confidence.sdk.events.v1B\bApiProtoP\x01Z_github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/eventsb\x06proto3"

var (
	file_confidence_events_v1_api_proto_rawDescOnce sync.Once
	file_confidence_events_v1_api_proto_rawDescData []byte
)

func file_confidence_events_v1_api_proto_rawDescGZIP() []byte {
	file_confidence_events_v1_api_proto_rawDescOnce.Do(func() {
		file_confidence_events_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_events_v1_api_proto_rawDesc), len(file_confidence_events_v1_api_proto_rawDesc)))
	})
	return file_confidence_events_v1_api_proto_rawDescData
}

var file_confidence_events_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_confidence_events_v1_api_proto_goTypes = []any{
	(*PublishEventsRequest)(nil),  // 0: confidence.events.v1.PublishEventsRequest
	(*PublishEventsResponse)(nil), // 1: confidence.events.v1.PublishEventsResponse
	(*Event)(nil),                 // 2: confidence.events.v1.Event
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Sdk)(nil),                   // 4: confidence.events.v1.Sdk
	(*EventError)(nil),            // 5: confidence.events.v1.EventError
}
var file_confidence_events_v1_api_proto_depIdxs = []int32{
	2, // 0: confidence.events.v1.PublishEventsRequest.events:type_name -> confidence.events.v1.Event
	3, // 1: confidence.events.v1.PublishEventsRequest.send_time:type_name -> google.protobuf.Timestamp
	4, // 2: confidence.events.v1.PublishEventsRequest.sdk:type_name -> confidence.events.v1.Sdk
	5, // 3: confidence.events.v1.PublishEventsResponse.errors:type_name -> confidence.events.v1.EventError
	0, // 4: confidence.events.v1.EventsService.PublishEvents:input_type -> confidence.events.v1.PublishEventsRequest
	1, // 5: confidence.events.v1.EventsService.PublishEvents:output_type -> confidence.events.v1.PublishEventsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_confidence_events_v1_api_proto_init() }
func file_confidence_events_v1_api_proto_init() {
	if File_confidence_events_v1_api_proto != nil {
		return
	}
	file_confidence_events_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_events_v1_api_proto_rawDesc), len(file_confidence_events_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confidence_events_v1_api_proto_goTypes,
		DependencyIndexes: file_confidence_events_v1_api_proto_depIdxs,
		MessageInfos:      file_confidence_events_v1_api_proto_msgTypes,
	}.Build()
	File_confidence_events_v1_api_proto = out.File
	file_confidence_events_v1_api_proto_goTypes = nil
	file_confidence_events_v1_api_proto_depIdxs = nil
}
