// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: confidence/events/v1/types.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The SDK used to interact with the API.
type SdkId int32

const (
	SdkId_SDK_ID_UNSPECIFIED                SdkId = 0
	SdkId_SDK_ID_JAVA_PROVIDER              SdkId = 1
	SdkId_SDK_ID_KOTLIN_PROVIDER            SdkId = 2
	SdkId_SDK_ID_SWIFT_PROVIDER             SdkId = 3
	SdkId_SDK_ID_JS_WEB_PROVIDER            SdkId = 4
	SdkId_SDK_ID_JS_SERVER_PROVIDER         SdkId = 5
	SdkId_SDK_ID_PYTHON_PROVIDER            SdkId = 6
	SdkId_SDK_ID_GO_PROVIDER                SdkId = 7
	SdkId_SDK_ID_RUBY_PROVIDER              SdkId = 8
	SdkId_SDK_ID_RUST_PROVIDER              SdkId = 9
	SdkId_SDK_ID_JAVA_CONFIDENCE            SdkId = 10
	SdkId_SDK_ID_KOTLIN_CONFIDENCE          SdkId = 11
	SdkId_SDK_ID_SWIFT_CONFIDENCE           SdkId = 12
	SdkId_SDK_ID_JS_CONFIDENCE              SdkId = 13
	SdkId_SDK_ID_PYTHON_CONFIDENCE          SdkId = 14
	SdkId_SDK_ID_GO_CONFIDENCE              SdkId = 15
	SdkId_SDK_ID_RUST_CONFIDENCE            SdkId = 16
	SdkId_SDK_ID_FLUTTER_IOS_CONFIDENCE     SdkId = 17
	SdkId_SDK_ID_FLUTTER_ANDROID_CONFIDENCE SdkId = 18
	SdkId_SDK_ID_DOTNET_CONFIDENCE          SdkId = 19
	// Confidence OpenFeature Go Local Provider.
	SdkId_SDK_ID_GO_LOCAL_PROVIDER SdkId = 20
	// Confidence OpenFeature Java Local Provider.
	SdkId_SDK_ID_JAVA_LOCAL_PROVIDER SdkId = 21
	// Confidence OpenFeature JavaScript Local Server Provider.
	SdkId_SDK_ID_JS_LOCAL_SERVER_PROVIDER SdkId = 22
	// Confidence OpenFeature Python Local Provider.
	SdkId_SDK_ID_PYTHON_LOCAL_PROVIDER SdkId = 23
	// Confidence OpenFeature Rust Local Provider.
	SdkId_SDK_ID_RUST_LOCAL_PROVIDER SdkId = 24
	// Confidence Cloudflare Resolver.
	SdkId_SDK_ID_CLOUDFLARE_RESOLVER SdkId = 25
	// Confidence OpenFeature PHP Provider.
	SdkId_SDK_ID_PHP_PROVIDER SdkId = 26
)

// Enum value maps for SdkId.
var (
	SdkId_name = map[int32]string{
		0:  "SDK_ID_UNSPECIFIED",
		1:  "SDK_ID_JAVA_PROVIDER",
		2:  "SDK_ID_KOTLIN_PROVIDER",
		3:  "SDK_ID_SWIFT_PROVIDER",
		4:  "SDK_ID_JS_WEB_PROVIDER",
		5:  "SDK_ID_JS_SERVER_PROVIDER",
		6:  "SDK_ID_PYTHON_PROVIDER",
		7:  "SDK_ID_GO_PROVIDER",
		8:  "SDK_ID_RUBY_PROVIDER",
		9:  "SDK_ID_RUST_PROVIDER",
		10: "SDK_ID_JAVA_CONFIDENCE",
		11: "SDK_ID_KOTLIN_CONFIDENCE",
		12: "SDK_ID_SWIFT_CONFIDENCE",
		13: "SDK_ID_JS_CONFIDENCE",
		14: "SDK_ID_PYTHON_CONFIDENCE",
		15: "SDK_ID_GO_CONFIDENCE",
		16: "SDK_ID_RUST_CONFIDENCE",
		17: "SDK_ID_FLUTTER_IOS_CONFIDENCE",
		18: "SDK_ID_FLUTTER_ANDROID_CONFIDENCE",
		19: "SDK_ID_DOTNET_CONFIDENCE",
		20: "SDK_ID_GO_LOCAL_PROVIDER",
		21: "SDK_ID_JAVA_LOCAL_PROVIDER",
		22: "SDK_ID_JS_LOCAL_SERVER_PROVIDER",
		23: "SDK_ID_PYTHON_LOCAL_PROVIDER",
		24: "SDK_ID_RUST_LOCAL_PROVIDER",
		25: "SDK_ID_CLOUDFLARE_RESOLVER",
		26: "SDK_ID_PHP_PROVIDER",
	}
	SdkId_value = map[string]int32{
		"SDK_ID_UNSPECIFIED":                0,
		"SDK_ID_JAVA_PROVIDER":              1,
		"SDK_ID_KOTLIN_PROVIDER":            2,
		"SDK_ID_SWIFT_PROVIDER":             3,
		"SDK_ID_JS_WEB_PROVIDER":            4,
		"SDK_ID_JS_SERVER_PROVIDER":         5,
		"SDK_ID_PYTHON_PROVIDER":            6,
		"SDK_ID_GO_PROVIDER":                7,
		"SDK_ID_RUBY_PROVIDER":              8,
		"SDK_ID_RUST_PROVIDER":              9,
		"SDK_ID_JAVA_CONFIDENCE":            10,
		"SDK_ID_KOTLIN_CONFIDENCE":          11,
		"SDK_ID_SWIFT_CONFIDENCE":           12,
		"SDK_ID_JS_CONFIDENCE":              13,
		"SDK_ID_PYTHON_CONFIDENCE":          14,
		"SDK_ID_GO_CONFIDENCE":              15,
		"SDK_ID_RUST_CONFIDENCE":            16,
		"SDK_ID_FLUTTER_IOS_CONFIDENCE":     17,
		"SDK_ID_FLUTTER_ANDROID_CONFIDENCE": 18,
		"SDK_ID_DOTNET_CONFIDENCE":          19,
		"SDK_ID_GO_LOCAL_PROVIDER":          20,
		"SDK_ID_JAVA_LOCAL_PROVIDER":        21,
		"SDK_ID_JS_LOCAL_SERVER_PROVIDER":   22,
		"SDK_ID_PYTHON_LOCAL_PROVIDER":      23,
		"SDK_ID_RUST_LOCAL_PROVIDER":        24,
		"SDK_ID_CLOUDFLARE_RESOLVER":        25,
		"SDK_ID_PHP_PROVIDER":               26,
	}
)

func (x SdkId) Enum() *SdkId {
	p := new(SdkId)
	*p = x
	return p
}

func (x SdkId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdkId) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_events_v1_types_proto_enumTypes[0].Descriptor()
}

func (SdkId) Type() protoreflect.EnumType {
	return &file_confidence_events_v1_types_proto_enumTypes[0]
}

func (x SdkId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdkId.Descriptor instead.
func (SdkId) EnumDescriptor() ([]byte, []int) {
	return file_confidence_events_v1_types_proto_rawDescGZIP(), []int{0}
}

type EventError_Reason int32

const (
	EventError_REASON_UNSPECIFIED             EventError_Reason = 0
	EventError_EVENT_DEFINITION_NOT_FOUND     EventError_Reason = 1
	EventError_EVENT_SCHEMA_VALIDATION_FAILED EventError_Reason = 2
	EventError_EVENT_DEFINITION_INVALID_NAME  EventError_Reason = 3
)

// Enum value maps for EventError_Reason.
var (
	EventError_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "EVENT_DEFINITION_NOT_FOUND",
		2: "EVENT_SCHEMA_VALIDATION_FAILED",
		3: "EVENT_DEFINITION_INVALID_NAME",
	}
	EventError_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":             0,
		"EVENT_DEFINITION_NOT_FOUND":     1,
		"EVENT_SCHEMA_VALIDATION_FAILED": 2,
		"EVENT_DEFINITION_INVALID_NAME":  3,
	}
)

func (x EventError_Reason) Enum() *EventError_Reason {
	p := new(EventError_Reason)
	*p = x
	return p
}

func (x EventError_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventError_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_confidence_events_v1_types_proto_enumTypes[1].Descriptor()
}

func (EventError_Reason) Type() protoreflect.EnumType {
	return &file_confidence_events_v1_types_proto_enumTypes[1]
}

func (x EventError_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventError_Reason.Descriptor instead.
func (EventError_Reason) EnumDescriptor() ([]byte, []int) {
	return file_confidence_events_v1_types_proto_rawDescGZIP(), []int{1, 0}
}

// The event that you want to publish.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the definition of the event that you want to publish, on the
	// format `eventDefinitions/{event_definition_id}`.
	EventDefinition string `protobuf:"bytes,1,opt,name=event_definition,json=eventDefinition,proto3" json:"event_definition,omitempty"`
	// The json payload of the event. Empty nested records will be discarded.
	Payload *structpb.Struct `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// The client time when the event occurred.
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_confidence_events_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventDefinition() string {
	if x != nil {
		return x.EventDefinition
	}
	return ""
}

func (x *Event) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

// Description of an error that occurred during publish.
type EventError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index (zero based) of the event in the request that could not be published.
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The reason for why the event could not be ingested.
	Reason EventError_Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=confidence.events.v1.EventError_Reason" json:"reason,omitempty"`
	// An optional, human-readable error message set for certain error types.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventError) Reset() {
	*x = EventError{}
	mi := &file_confidence_events_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventError) ProtoMessage() {}

func (x *EventError) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventError.ProtoReflect.Descriptor instead.
func (*EventError) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *EventError) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventError) GetReason() EventError_Reason {
	if x != nil {
		return x.Reason
	}
	return EventError_REASON_UNSPECIFIED
}

func (x *EventError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Sdk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sdk:
	//
	//	*Sdk_Id
	//	*Sdk_CustomId
	Sdk isSdk_Sdk `protobuf_oneof:"sdk"`
	// Version of the SDK.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sdk) Reset() {
	*x = Sdk{}
	mi := &file_confidence_events_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sdk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sdk) ProtoMessage() {}

func (x *Sdk) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_events_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sdk.ProtoReflect.Descriptor instead.
func (*Sdk) Descriptor() ([]byte, []int) {
	return file_confidence_events_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Sdk) GetSdk() isSdk_Sdk {
	if x != nil {
		return x.Sdk
	}
	return nil
}

func (x *Sdk) GetId() SdkId {
	if x != nil {
		if x, ok := x.Sdk.(*Sdk_Id); ok {
			return x.Id
		}
	}
	return SdkId_SDK_ID_UNSPECIFIED
}

func (x *Sdk) GetCustomId() string {
	if x != nil {
		if x, ok := x.Sdk.(*Sdk_CustomId); ok {
			return x.CustomId
		}
	}
	return ""
}

func (x *Sdk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type isSdk_Sdk interface {
	isSdk_Sdk()
}

type Sdk_Id struct {
	// Name of a Confidence SDK.
	Id SdkId `protobuf:"varint,1,opt,name=id,proto3,enum=confidence.events.v1.SdkId,oneof"`
}

type Sdk_CustomId struct {
	// Custom name for non-Confidence SDKs.
	CustomId string `protobuf:"bytes,2,opt,name=custom_id,json=customId,proto3,oneof"`
}

func (*Sdk_Id) isSdk_Sdk() {}

func (*Sdk_CustomId) isSdk_Sdk() {}

var File_confidence_events_v1_types_proto protoreflect.FileDescriptor

const file_confidence_events_v1_types_proto_rawDesc = "" +
	"\n" +
	" confidence/events/v1/types.proto\x12\x14confidence.events.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x05Event\x12)\n" +
	"\x10event_definition\x18\x01 \x01(\tR\x0feventDefinition\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x129\n" +
	"\n" +
	"event_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\"\x87\x02\n" +
	"\n" +
	"EventError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12?\n" +
	"\x06reason\x18\x02 \x01(\x0e2'.confidence.events.v1.EventError.ReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x87\x01\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEVENT_DEFINITION_NOT_FOUND\x10\x01\x12\"\n" +
	"\x1eEVENT_SCHEMA_VALIDATION_FAILED\x10\x02\x12!\n" +
	"\x1dEVENT_DEFINITION_INVALID_NAME\x10\x03\"t\n" +
	"\x03Sdk\x12-\n" +
	"\x02id\x18\x01 \x01(\x0e2\x1b.confidence.events.v1.SdkIdH\x00R\x02id\x12\x1d\n" +
	"\tcustom_id\x18\x02 \x01(\tH\x00R\bcustomId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB\x05\n" +
	"\x03sdk*\x9e\x06\n" +
	"\x05SdkId\x12\x16\n" +
	"\x12SDK_ID_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SDK_ID_JAVA_PROVIDER\x10\x01\x12\x1a\n" +
	"\x16SDK_ID_KOTLIN_PROVIDER\x10\x02\x12\x19\n" +
	"\x15SDK_ID_SWIFT_PROVIDER\x10\x03\x12\x1a\n" +
	"\x16SDK_ID_JS_WEB_PROVIDER\x10\x04\x12\x1d\n" +
	"\x19SDK_ID_JS_SERVER_PROVIDER\x10\x05\x12\x1a\n" +
	"\x16SDK_ID_PYTHON_PROVIDER\x10\x06\x12\x16\n" +
	"\x12SDK_ID_GO_PROVIDER\x10\a\x12\x18\n" +
	"\x14SDK_ID_RUBY_PROVIDER\x10\b\x12\x18\n" +
	"\x14SDK_ID_RUST_PROVIDER\x10\t\x12\x1a\n" +
	"\x16SDK_ID_JAVA_CONFIDENCE\x10\n" +
	"\x12\x1c\n" +
	"\x18SDK_ID_KOTLIN_CONFIDENCE\x10\v\x12\x1b\n" +
	"\x17SDK_ID_SWIFT_CONFIDENCE\x10\f\x12\x18\n" +
	"\x14SDK_ID_JS_CONFIDENCE\x10\r\x12\x1c\n" +
	"\x18SDK_ID_PYTHON_CONFIDENCE\x10\x0e\x12\x18\n" +
	"\x14SDK_ID_GO_CONFIDENCE\x10\x0f\x12\x1a\n" +
	"\x16SDK_ID_RUST_CONFIDENCE\x10\x10\x12!\n" +
	"\x1dSDK_ID_FLUTTER_IOS_CONFIDENCE\x10\x11\x12%\n" +
	"!SDK_ID_FLUTTER_ANDROID_CONFIDENCE\x10\x12\x12\x1c\n" +
	"\x18SDK_ID_DOTNET_CONFIDENCE\x10\x13\x12\x1c\n" +
	"\x18SDK_ID_GO_LOCAL_PROVIDER\x10\x14\x12\x1e\n" +
	"\x1aSDK_ID_JAVA_LOCAL_PROVIDER\x10\x15\x12#\n" +
	"\x1fSDK_ID_JS_LOCAL_SERVER_PROVIDER\x10\x16\x12 \n" +
	"\x1cSDK_ID_PYTHON_LOCAL_PROVIDER\x10\x17\x12\x1e\n" +
	"\x1aSDK_ID_RUST_LOCAL_PROVIDER\x10\x18\x12\x1e\n" +
	"\x1aSDK_ID_CLOUDFLARE_RESOLVER\x10\x19\x12\x17\n" +
	"\x13SDK_ID_PHP_PROVIDER\x10\x1aB\x95\x01\n" +
	"$com.spotify.confidence.sdk.events.v1B\n" +
	"TypesProtoP\x01Z_github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/eventsb\x06proto3"

var (
	file_confidence_events_v1_types_proto_rawDescOnce sync.Once
	file_confidence_events_v1_types_proto_rawDescData []byte
)

func file_confidence_events_v1_types_proto_rawDescGZIP() []byte {
	file_confidence_events_v1_types_proto_rawDescOnce.Do(func() {
		file_confidence_events_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_events_v1_types_proto_rawDesc), len(file_confidence_events_v1_types_proto_rawDesc)))
	})
	return file_confidence_events_v1_types_proto_rawDescData
}

var file_confidence_events_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_confidence_events_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_confidence_events_v1_types_proto_goTypes = []any{
	(SdkId)(0),                    // 0: confidence.events.v1.SdkId
	(EventError_Reason)(0),        // 1: confidence.events.v1.EventError.Reason
	(*Event)(nil),                 // 2: confidence.events.v1.Event
	(*EventError)(nil),            // 3: confidence.events.v1.EventError
	(*Sdk)(nil),                   // 4: confidence.events.v1.Sdk
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_confidence_events_v1_types_proto_depIdxs = []int32{
	5, // 0: confidence.events.v1.Event.payload:type_name -> google.protobuf.Struct
	6, // 1: confidence.events.v1.Event.event_time:type_name -> google.protobuf.Timestamp
	1, // 2: confidence.events.v1.EventError.reason:type_name -> confidence.events.v1.EventError.Reason
	0, // 3: confidence.events.v1.Sdk.id:type_name -> confidence.events.v1.SdkId
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_confidence_events_v1_types_proto_init() }
func file_confidence_events_v1_types_proto_init() {
	if File_confidence_events_v1_types_proto != nil {
		return
	}
	file_confidence_events_v1_types_proto_msgTypes[2].OneofWrappers = []any{
		(*Sdk_Id)(nil),
		(*Sdk_CustomId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_events_v1_types_proto_rawDesc), len(file_confidence_events_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_events_v1_types_proto_goTypes,
		DependencyIndexes: file_confidence_events_v1_types_proto_depIdxs,
		EnumInfos:         file_confidence_events_v1_types_proto_enumTypes,
		MessageInfos:      file_confidence_events_v1_types_proto_msgTypes,
	}.Build()
	File_confidence_events_v1_types_proto = out.File
	file_confidence_events_v1_types_proto_goTypes = nil
	file_confidence_events_v1_types_proto_depIdxs = nil
}
