// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: confidence/wasm/wasm_api.proto

package wasm

import (
	resolver "github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/resolver"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ResolveProcessRequest_Resolve
	//	*ResolveProcessRequest_ResolveWithMaterializations_
	//	*ResolveProcessRequest_Resume
	Request       isResolveProcessRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProcessRequest) Reset() {
	*x = ResolveProcessRequest{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest) ProtoMessage() {}

func (x *ResolveProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveProcessRequest) GetRequest() isResolveProcessRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ResolveProcessRequest) GetResolve() *resolver.ResolveFlagsRequest {
	if x != nil {
		if x, ok := x.Request.(*ResolveProcessRequest_Resolve); ok {
			return x.Resolve
		}
	}
	return nil
}

func (x *ResolveProcessRequest) GetResolveWithMaterializations() *ResolveProcessRequest_ResolveWithMaterializations {
	if x != nil {
		if x, ok := x.Request.(*ResolveProcessRequest_ResolveWithMaterializations_); ok {
			return x.ResolveWithMaterializations
		}
	}
	return nil
}

func (x *ResolveProcessRequest) GetResume() *ResolveProcessRequest_ResumeRequest {
	if x != nil {
		if x, ok := x.Request.(*ResolveProcessRequest_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

type isResolveProcessRequest_Request interface {
	isResolveProcessRequest_Request()
}

type ResolveProcessRequest_Resolve struct {
	// Simple resolve, no materializations available
	Resolve *resolver.ResolveFlagsRequest `protobuf:"bytes,1,opt,name=resolve,proto3,oneof"`
}

type ResolveProcessRequest_ResolveWithMaterializations_ struct {
	// Resolve with pre-supplied materializations (e.g. from cookie)
	ResolveWithMaterializations *ResolveProcessRequest_ResolveWithMaterializations `protobuf:"bytes,2,opt,name=resolve_with_materializations,json=resolveWithMaterializations,proto3,oneof"`
}

type ResolveProcessRequest_Resume struct {
	// Resume a previously suspended resolve with requested materializations
	Resume *ResolveProcessRequest_ResumeRequest `protobuf:"bytes,3,opt,name=resume,proto3,oneof"`
}

func (*ResolveProcessRequest_Resolve) isResolveProcessRequest_Request() {}

func (*ResolveProcessRequest_ResolveWithMaterializations_) isResolveProcessRequest_Request() {}

func (*ResolveProcessRequest_Resume) isResolveProcessRequest_Request() {}

type ResolveProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResolveProcessResponse_Resolved_
	//	*ResolveProcessResponse_Suspended_
	Result        isResolveProcessResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProcessResponse) Reset() {
	*x = ResolveProcessResponse{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse) ProtoMessage() {}

func (x *ResolveProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveProcessResponse) GetResult() isResolveProcessResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResolveProcessResponse) GetResolved() *ResolveProcessResponse_Resolved {
	if x != nil {
		if x, ok := x.Result.(*ResolveProcessResponse_Resolved_); ok {
			return x.Resolved
		}
	}
	return nil
}

func (x *ResolveProcessResponse) GetSuspended() *ResolveProcessResponse_Suspended {
	if x != nil {
		if x, ok := x.Result.(*ResolveProcessResponse_Suspended_); ok {
			return x.Suspended
		}
	}
	return nil
}

type isResolveProcessResponse_Result interface {
	isResolveProcessResponse_Result()
}

type ResolveProcessResponse_Resolved_ struct {
	Resolved *ResolveProcessResponse_Resolved `protobuf:"bytes,1,opt,name=resolved,proto3,oneof"`
}

type ResolveProcessResponse_Suspended_ struct {
	Suspended *ResolveProcessResponse_Suspended `protobuf:"bytes,2,opt,name=suspended,proto3,oneof"`
}

func (*ResolveProcessResponse_Resolved_) isResolveProcessResponse_Result() {}

func (*ResolveProcessResponse_Suspended_) isResolveProcessResponse_Result() {}

// This message is used both as a query and a result when reading materializations.
type MaterializationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	Rule            string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Variant         string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaterializationRecord) Reset() {
	*x = MaterializationRecord{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationRecord) ProtoMessage() {}

func (x *MaterializationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationRecord.ProtoReflect.Descriptor instead.
func (*MaterializationRecord) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{2}
}

func (x *MaterializationRecord) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MaterializationRecord) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

func (x *MaterializationRecord) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *MaterializationRecord) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveProcessRequest_ResolveWithMaterializations struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	ResolveRequest   *resolver.ResolveFlagsRequest `protobuf:"bytes,1,opt,name=resolve_request,json=resolveRequest,proto3" json:"resolve_request,omitempty"`
	Materializations []*MaterializationRecord      `protobuf:"bytes,2,rep,name=materializations,proto3" json:"materializations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveProcessRequest_ResolveWithMaterializations) Reset() {
	*x = ResolveProcessRequest_ResolveWithMaterializations{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest_ResolveWithMaterializations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest_ResolveWithMaterializations) ProtoMessage() {}

func (x *ResolveProcessRequest_ResolveWithMaterializations) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest_ResolveWithMaterializations.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest_ResolveWithMaterializations) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResolveProcessRequest_ResolveWithMaterializations) GetResolveRequest() *resolver.ResolveFlagsRequest {
	if x != nil {
		return x.ResolveRequest
	}
	return nil
}

func (x *ResolveProcessRequest_ResolveWithMaterializations) GetMaterializations() []*MaterializationRecord {
	if x != nil {
		return x.Materializations
	}
	return nil
}

type ResolveProcessRequest_ResumeRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Materializations []*MaterializationRecord `protobuf:"bytes,1,rep,name=materializations,proto3" json:"materializations,omitempty"`
	State            []byte                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveProcessRequest_ResumeRequest) Reset() {
	*x = ResolveProcessRequest_ResumeRequest{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest_ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest_ResumeRequest) ProtoMessage() {}

func (x *ResolveProcessRequest_ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest_ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest_ResumeRequest) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResolveProcessRequest_ResumeRequest) GetMaterializations() []*MaterializationRecord {
	if x != nil {
		return x.Materializations
	}
	return nil
}

func (x *ResolveProcessRequest_ResumeRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type ResolveProcessResponse_Resolved struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	Response                *resolver.ResolveFlagsResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	MaterializationsToWrite []*MaterializationRecord       `protobuf:"bytes,2,rep,name=materializations_to_write,json=materializationsToWrite,proto3" json:"materializations_to_write,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolveProcessResponse_Resolved) Reset() {
	*x = ResolveProcessResponse_Resolved{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse_Resolved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse_Resolved) ProtoMessage() {}

func (x *ResolveProcessResponse_Resolved) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse_Resolved.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse_Resolved) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResolveProcessResponse_Resolved) GetResponse() *resolver.ResolveFlagsResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResolveProcessResponse_Resolved) GetMaterializationsToWrite() []*MaterializationRecord {
	if x != nil {
		return x.MaterializationsToWrite
	}
	return nil
}

type ResolveProcessResponse_Suspended struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	MaterializationsToRead []*MaterializationRecord `protobuf:"bytes,1,rep,name=materializations_to_read,json=materializationsToRead,proto3" json:"materializations_to_read,omitempty"`
	State                  []byte                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResolveProcessResponse_Suspended) Reset() {
	*x = ResolveProcessResponse_Suspended{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse_Suspended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse_Suspended) ProtoMessage() {}

func (x *ResolveProcessResponse_Suspended) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse_Suspended.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse_Suspended) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ResolveProcessResponse_Suspended) GetMaterializationsToRead() []*MaterializationRecord {
	if x != nil {
		return x.MaterializationsToRead
	}
	return nil
}

func (x *ResolveProcessResponse_Suspended) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

var File_confidence_wasm_wasm_api_proto protoreflect.FileDescriptor

const file_confidence_wasm_wasm_api_proto_rawDesc = "" +
	"\n" +
	"\x1econfidence/wasm/wasm_api.proto\x12\x1cconfidence.flags.resolver.v1\x1a&confidence/flags/resolver/v1/api.proto\"\xcc\x05\n" +
	"\x15ResolveProcessRequest\x12M\n" +
	"\aresolve\x18\x01 \x01(\v21.confidence.flags.resolver.v1.ResolveFlagsRequestH\x00R\aresolve\x12\x95\x01\n" +
	"\x1dresolve_with_materializations\x18\x02 \x01(\v2O.confidence.flags.resolver.v1.ResolveProcessRequest.ResolveWithMaterializationsH\x00R\x1bresolveWithMaterializations\x12[\n" +
	"\x06resume\x18\x03 \x01(\v2A.confidence.flags.resolver.v1.ResolveProcessRequest.ResumeRequestH\x00R\x06resume\x1a\xda\x01\n" +
	"\x1bResolveWithMaterializations\x12Z\n" +
	"\x0fresolve_request\x18\x01 \x01(\v21.confidence.flags.resolver.v1.ResolveFlagsRequestR\x0eresolveRequest\x12_\n" +
	"\x10materializations\x18\x02 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x10materializations\x1a\x86\x01\n" +
	"\rResumeRequest\x12_\n" +
	"\x10materializations\x18\x01 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x10materializations\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05stateB\t\n" +
	"\arequest\"\xc0\x04\n" +
	"\x16ResolveProcessResponse\x12[\n" +
	"\bresolved\x18\x01 \x01(\v2=.confidence.flags.resolver.v1.ResolveProcessResponse.ResolvedH\x00R\bresolved\x12^\n" +
	"\tsuspended\x18\x02 \x01(\v2>.confidence.flags.resolver.v1.ResolveProcessResponse.SuspendedH\x00R\tsuspended\x1a\xcb\x01\n" +
	"\bResolved\x12N\n" +
	"\bresponse\x18\x01 \x01(\v22.confidence.flags.resolver.v1.ResolveFlagsResponseR\bresponse\x12o\n" +
	"\x19materializations_to_write\x18\x02 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x17materializationsToWrite\x1a\x90\x01\n" +
	"\tSuspended\x12m\n" +
	"\x18materializations_to_read\x18\x01 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x16materializationsToRead\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05stateB\b\n" +
	"\x06result\"\x83\x01\n" +
	"\x15MaterializationRecord\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\"&\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x9d\x01\n" +
	",com.spotify.confidence.sdk.flags.resolver.v1B\fWasmApiProtoP\x01Z]github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/wasmb\x06proto3"

var (
	file_confidence_wasm_wasm_api_proto_rawDescOnce sync.Once
	file_confidence_wasm_wasm_api_proto_rawDescData []byte
)

func file_confidence_wasm_wasm_api_proto_rawDescGZIP() []byte {
	file_confidence_wasm_wasm_api_proto_rawDescOnce.Do(func() {
		file_confidence_wasm_wasm_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_wasm_wasm_api_proto_rawDesc), len(file_confidence_wasm_wasm_api_proto_rawDesc)))
	})
	return file_confidence_wasm_wasm_api_proto_rawDescData
}

var file_confidence_wasm_wasm_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_confidence_wasm_wasm_api_proto_goTypes = []any{
	(*ResolveProcessRequest)(nil),                             // 0: confidence.flags.resolver.v1.ResolveProcessRequest
	(*ResolveProcessResponse)(nil),                            // 1: confidence.flags.resolver.v1.ResolveProcessResponse
	(*MaterializationRecord)(nil),                             // 2: confidence.flags.resolver.v1.MaterializationRecord
	(*LogMessage)(nil),                                        // 3: confidence.flags.resolver.v1.LogMessage
	(*ResolveProcessRequest_ResolveWithMaterializations)(nil), // 4: confidence.flags.resolver.v1.ResolveProcessRequest.ResolveWithMaterializations
	(*ResolveProcessRequest_ResumeRequest)(nil),               // 5: confidence.flags.resolver.v1.ResolveProcessRequest.ResumeRequest
	(*ResolveProcessResponse_Resolved)(nil),                   // 6: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved
	(*ResolveProcessResponse_Suspended)(nil),                  // 7: confidence.flags.resolver.v1.ResolveProcessResponse.Suspended
	(*resolver.ResolveFlagsRequest)(nil),                      // 8: confidence.flags.resolver.v1.ResolveFlagsRequest
	(*resolver.ResolveFlagsResponse)(nil),                     // 9: confidence.flags.resolver.v1.ResolveFlagsResponse
}
var file_confidence_wasm_wasm_api_proto_depIdxs = []int32{
	8,  // 0: confidence.flags.resolver.v1.ResolveProcessRequest.resolve:type_name -> confidence.flags.resolver.v1.ResolveFlagsRequest
	4,  // 1: confidence.flags.resolver.v1.ResolveProcessRequest.resolve_with_materializations:type_name -> confidence.flags.resolver.v1.ResolveProcessRequest.ResolveWithMaterializations
	5,  // 2: confidence.flags.resolver.v1.ResolveProcessRequest.resume:type_name -> confidence.flags.resolver.v1.ResolveProcessRequest.ResumeRequest
	6,  // 3: confidence.flags.resolver.v1.ResolveProcessResponse.resolved:type_name -> confidence.flags.resolver.v1.ResolveProcessResponse.Resolved
	7,  // 4: confidence.flags.resolver.v1.ResolveProcessResponse.suspended:type_name -> confidence.flags.resolver.v1.ResolveProcessResponse.Suspended
	8,  // 5: confidence.flags.resolver.v1.ResolveProcessRequest.ResolveWithMaterializations.resolve_request:type_name -> confidence.flags.resolver.v1.ResolveFlagsRequest
	2,  // 6: confidence.flags.resolver.v1.ResolveProcessRequest.ResolveWithMaterializations.materializations:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	2,  // 7: confidence.flags.resolver.v1.ResolveProcessRequest.ResumeRequest.materializations:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	9,  // 8: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved.response:type_name -> confidence.flags.resolver.v1.ResolveFlagsResponse
	2,  // 9: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved.materializations_to_write:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	2,  // 10: confidence.flags.resolver.v1.ResolveProcessResponse.Suspended.materializations_to_read:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_confidence_wasm_wasm_api_proto_init() }
func file_confidence_wasm_wasm_api_proto_init() {
	if File_confidence_wasm_wasm_api_proto != nil {
		return
	}
	file_confidence_wasm_wasm_api_proto_msgTypes[0].OneofWrappers = []any{
		(*ResolveProcessRequest_Resolve)(nil),
		(*ResolveProcessRequest_ResolveWithMaterializations_)(nil),
		(*ResolveProcessRequest_Resume)(nil),
	}
	file_confidence_wasm_wasm_api_proto_msgTypes[1].OneofWrappers = []any{
		(*ResolveProcessResponse_Resolved_)(nil),
		(*ResolveProcessResponse_Suspended_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_wasm_wasm_api_proto_rawDesc), len(file_confidence_wasm_wasm_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_wasm_wasm_api_proto_goTypes,
		DependencyIndexes: file_confidence_wasm_wasm_api_proto_depIdxs,
		MessageInfos:      file_confidence_wasm_wasm_api_proto_msgTypes,
	}.Build()
	File_confidence_wasm_wasm_api_proto = out.File
	file_confidence_wasm_wasm_api_proto_goTypes = nil
	file_confidence_wasm_wasm_api_proto_depIdxs = nil
}
