// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: confidence/wasm/wasm_api.proto

package wasm

import (
	resolver "github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/resolver"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resolve:
	//
	//	*ResolveProcessRequest_DeferredMaterializations
	//	*ResolveProcessRequest_StaticMaterializations_
	//	*ResolveProcessRequest_WithoutMaterializations
	//	*ResolveProcessRequest_Resume_
	Resolve       isResolveProcessRequest_Resolve `protobuf_oneof:"resolve"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProcessRequest) Reset() {
	*x = ResolveProcessRequest{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest) ProtoMessage() {}

func (x *ResolveProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveProcessRequest) GetResolve() isResolveProcessRequest_Resolve {
	if x != nil {
		return x.Resolve
	}
	return nil
}

func (x *ResolveProcessRequest) GetDeferredMaterializations() *resolver.ResolveFlagsRequest {
	if x != nil {
		if x, ok := x.Resolve.(*ResolveProcessRequest_DeferredMaterializations); ok {
			return x.DeferredMaterializations
		}
	}
	return nil
}

func (x *ResolveProcessRequest) GetStaticMaterializations() *ResolveProcessRequest_StaticMaterializations {
	if x != nil {
		if x, ok := x.Resolve.(*ResolveProcessRequest_StaticMaterializations_); ok {
			return x.StaticMaterializations
		}
	}
	return nil
}

func (x *ResolveProcessRequest) GetWithoutMaterializations() *resolver.ResolveFlagsRequest {
	if x != nil {
		if x, ok := x.Resolve.(*ResolveProcessRequest_WithoutMaterializations); ok {
			return x.WithoutMaterializations
		}
	}
	return nil
}

func (x *ResolveProcessRequest) GetResume() *ResolveProcessRequest_Resume {
	if x != nil {
		if x, ok := x.Resolve.(*ResolveProcessRequest_Resume_); ok {
			return x.Resume
		}
	}
	return nil
}

type isResolveProcessRequest_Resolve interface {
	isResolveProcessRequest_Resolve()
}

type ResolveProcessRequest_DeferredMaterializations struct {
	// Materialization reads will "suspend" the resolve
	DeferredMaterializations *resolver.ResolveFlagsRequest `protobuf:"bytes,1,opt,name=deferred_materializations,json=deferredMaterializations,proto3,oneof"`
}

type ResolveProcessRequest_StaticMaterializations_ struct {
	// Materializations will be read from a statically provided set
	StaticMaterializations *ResolveProcessRequest_StaticMaterializations `protobuf:"bytes,2,opt,name=static_materializations,json=staticMaterializations,proto3,oneof"`
}

type ResolveProcessRequest_WithoutMaterializations struct {
	// No materialization support, reads will error the flag.
	WithoutMaterializations *resolver.ResolveFlagsRequest `protobuf:"bytes,3,opt,name=without_materializations,json=withoutMaterializations,proto3,oneof"`
}

type ResolveProcessRequest_Resume_ struct {
	// Resume a previously suspended resolve with requested materializations
	Resume *ResolveProcessRequest_Resume `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

func (*ResolveProcessRequest_DeferredMaterializations) isResolveProcessRequest_Resolve() {}

func (*ResolveProcessRequest_StaticMaterializations_) isResolveProcessRequest_Resolve() {}

func (*ResolveProcessRequest_WithoutMaterializations) isResolveProcessRequest_Resolve() {}

func (*ResolveProcessRequest_Resume_) isResolveProcessRequest_Resolve() {}

type ResolveProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResolveProcessResponse_Resolved_
	//	*ResolveProcessResponse_Suspended_
	Result        isResolveProcessResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProcessResponse) Reset() {
	*x = ResolveProcessResponse{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse) ProtoMessage() {}

func (x *ResolveProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveProcessResponse) GetResult() isResolveProcessResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResolveProcessResponse) GetResolved() *ResolveProcessResponse_Resolved {
	if x != nil {
		if x, ok := x.Result.(*ResolveProcessResponse_Resolved_); ok {
			return x.Resolved
		}
	}
	return nil
}

func (x *ResolveProcessResponse) GetSuspended() *ResolveProcessResponse_Suspended {
	if x != nil {
		if x, ok := x.Result.(*ResolveProcessResponse_Suspended_); ok {
			return x.Suspended
		}
	}
	return nil
}

type isResolveProcessResponse_Result interface {
	isResolveProcessResponse_Result()
}

type ResolveProcessResponse_Resolved_ struct {
	Resolved *ResolveProcessResponse_Resolved `protobuf:"bytes,1,opt,name=resolved,proto3,oneof"`
}

type ResolveProcessResponse_Suspended_ struct {
	Suspended *ResolveProcessResponse_Suspended `protobuf:"bytes,2,opt,name=suspended,proto3,oneof"`
}

func (*ResolveProcessResponse_Resolved_) isResolveProcessResponse_Result() {}

func (*ResolveProcessResponse_Suspended_) isResolveProcessResponse_Result() {}

// This message is used both as a query and a result when reading materializations.
type MaterializationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unit            string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Materialization string                 `protobuf:"bytes,2,opt,name=materialization,proto3" json:"materialization,omitempty"`
	Rule            string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Variant         string                 `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaterializationRecord) Reset() {
	*x = MaterializationRecord{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationRecord) ProtoMessage() {}

func (x *MaterializationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationRecord.ProtoReflect.Descriptor instead.
func (*MaterializationRecord) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{2}
}

func (x *MaterializationRecord) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MaterializationRecord) GetMaterialization() string {
	if x != nil {
		return x.Materialization
	}
	return ""
}

func (x *MaterializationRecord) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *MaterializationRecord) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveProcessRequest_StaticMaterializations struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	ResolveRequest   *resolver.ResolveFlagsRequest `protobuf:"bytes,1,opt,name=resolve_request,json=resolveRequest,proto3" json:"resolve_request,omitempty"`
	Materializations []*MaterializationRecord      `protobuf:"bytes,2,rep,name=materializations,proto3" json:"materializations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveProcessRequest_StaticMaterializations) Reset() {
	*x = ResolveProcessRequest_StaticMaterializations{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest_StaticMaterializations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest_StaticMaterializations) ProtoMessage() {}

func (x *ResolveProcessRequest_StaticMaterializations) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest_StaticMaterializations.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest_StaticMaterializations) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResolveProcessRequest_StaticMaterializations) GetResolveRequest() *resolver.ResolveFlagsRequest {
	if x != nil {
		return x.ResolveRequest
	}
	return nil
}

func (x *ResolveProcessRequest_StaticMaterializations) GetMaterializations() []*MaterializationRecord {
	if x != nil {
		return x.Materializations
	}
	return nil
}

type ResolveProcessRequest_Resume struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Materializations []*MaterializationRecord `protobuf:"bytes,1,rep,name=materializations,proto3" json:"materializations,omitempty"`
	State            []byte                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveProcessRequest_Resume) Reset() {
	*x = ResolveProcessRequest_Resume{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessRequest_Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessRequest_Resume) ProtoMessage() {}

func (x *ResolveProcessRequest_Resume) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessRequest_Resume.ProtoReflect.Descriptor instead.
func (*ResolveProcessRequest_Resume) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResolveProcessRequest_Resume) GetMaterializations() []*MaterializationRecord {
	if x != nil {
		return x.Materializations
	}
	return nil
}

func (x *ResolveProcessRequest_Resume) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type ResolveProcessResponse_Resolved struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	Response                *resolver.ResolveFlagsResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	MaterializationsToWrite []*MaterializationRecord       `protobuf:"bytes,2,rep,name=materializations_to_write,json=materializationsToWrite,proto3" json:"materializations_to_write,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolveProcessResponse_Resolved) Reset() {
	*x = ResolveProcessResponse_Resolved{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse_Resolved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse_Resolved) ProtoMessage() {}

func (x *ResolveProcessResponse_Resolved) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse_Resolved.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse_Resolved) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResolveProcessResponse_Resolved) GetResponse() *resolver.ResolveFlagsResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResolveProcessResponse_Resolved) GetMaterializationsToWrite() []*MaterializationRecord {
	if x != nil {
		return x.MaterializationsToWrite
	}
	return nil
}

type ResolveProcessResponse_Suspended struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	MaterializationsToRead []*MaterializationRecord `protobuf:"bytes,1,rep,name=materializations_to_read,json=materializationsToRead,proto3" json:"materializations_to_read,omitempty"`
	State                  []byte                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResolveProcessResponse_Suspended) Reset() {
	*x = ResolveProcessResponse_Suspended{}
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProcessResponse_Suspended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProcessResponse_Suspended) ProtoMessage() {}

func (x *ResolveProcessResponse_Suspended) ProtoReflect() protoreflect.Message {
	mi := &file_confidence_wasm_wasm_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProcessResponse_Suspended.ProtoReflect.Descriptor instead.
func (*ResolveProcessResponse_Suspended) Descriptor() ([]byte, []int) {
	return file_confidence_wasm_wasm_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ResolveProcessResponse_Suspended) GetMaterializationsToRead() []*MaterializationRecord {
	if x != nil {
		return x.MaterializationsToRead
	}
	return nil
}

func (x *ResolveProcessResponse_Suspended) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

var File_confidence_wasm_wasm_api_proto protoreflect.FileDescriptor

const file_confidence_wasm_wasm_api_proto_rawDesc = "" +
	"\n" +
	"\x1econfidence/wasm/wasm_api.proto\x12\x1cconfidence.flags.resolver.v1\x1a&confidence/flags/resolver/v1/api.proto\"\xbb\x06\n" +
	"\x15ResolveProcessRequest\x12p\n" +
	"\x19deferred_materializations\x18\x01 \x01(\v21.confidence.flags.resolver.v1.ResolveFlagsRequestH\x00R\x18deferredMaterializations\x12\x85\x01\n" +
	"\x17static_materializations\x18\x02 \x01(\v2J.confidence.flags.resolver.v1.ResolveProcessRequest.StaticMaterializationsH\x00R\x16staticMaterializations\x12n\n" +
	"\x18without_materializations\x18\x03 \x01(\v21.confidence.flags.resolver.v1.ResolveFlagsRequestH\x00R\x17withoutMaterializations\x12T\n" +
	"\x06resume\x18\x04 \x01(\v2:.confidence.flags.resolver.v1.ResolveProcessRequest.ResumeH\x00R\x06resume\x1a\xd5\x01\n" +
	"\x16StaticMaterializations\x12Z\n" +
	"\x0fresolve_request\x18\x01 \x01(\v21.confidence.flags.resolver.v1.ResolveFlagsRequestR\x0eresolveRequest\x12_\n" +
	"\x10materializations\x18\x02 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x10materializations\x1a\x7f\n" +
	"\x06Resume\x12_\n" +
	"\x10materializations\x18\x01 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x10materializations\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05stateB\t\n" +
	"\aresolve\"\xc0\x04\n" +
	"\x16ResolveProcessResponse\x12[\n" +
	"\bresolved\x18\x01 \x01(\v2=.confidence.flags.resolver.v1.ResolveProcessResponse.ResolvedH\x00R\bresolved\x12^\n" +
	"\tsuspended\x18\x02 \x01(\v2>.confidence.flags.resolver.v1.ResolveProcessResponse.SuspendedH\x00R\tsuspended\x1a\xcb\x01\n" +
	"\bResolved\x12N\n" +
	"\bresponse\x18\x01 \x01(\v22.confidence.flags.resolver.v1.ResolveFlagsResponseR\bresponse\x12o\n" +
	"\x19materializations_to_write\x18\x02 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x17materializationsToWrite\x1a\x90\x01\n" +
	"\tSuspended\x12m\n" +
	"\x18materializations_to_read\x18\x01 \x03(\v23.confidence.flags.resolver.v1.MaterializationRecordR\x16materializationsToRead\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05stateB\b\n" +
	"\x06result\"\x83\x01\n" +
	"\x15MaterializationRecord\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12(\n" +
	"\x0fmaterialization\x18\x02 \x01(\tR\x0fmaterialization\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\"&\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x9d\x01\n" +
	",com.spotify.confidence.sdk.flags.resolver.v1B\fWasmApiProtoP\x01Z]github.com/spotify/confidence-resolver/openfeature-provider/go/confidence/internal/proto/wasmb\x06proto3"

var (
	file_confidence_wasm_wasm_api_proto_rawDescOnce sync.Once
	file_confidence_wasm_wasm_api_proto_rawDescData []byte
)

func file_confidence_wasm_wasm_api_proto_rawDescGZIP() []byte {
	file_confidence_wasm_wasm_api_proto_rawDescOnce.Do(func() {
		file_confidence_wasm_wasm_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confidence_wasm_wasm_api_proto_rawDesc), len(file_confidence_wasm_wasm_api_proto_rawDesc)))
	})
	return file_confidence_wasm_wasm_api_proto_rawDescData
}

var file_confidence_wasm_wasm_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_confidence_wasm_wasm_api_proto_goTypes = []any{
	(*ResolveProcessRequest)(nil),                        // 0: confidence.flags.resolver.v1.ResolveProcessRequest
	(*ResolveProcessResponse)(nil),                       // 1: confidence.flags.resolver.v1.ResolveProcessResponse
	(*MaterializationRecord)(nil),                        // 2: confidence.flags.resolver.v1.MaterializationRecord
	(*LogMessage)(nil),                                   // 3: confidence.flags.resolver.v1.LogMessage
	(*ResolveProcessRequest_StaticMaterializations)(nil), // 4: confidence.flags.resolver.v1.ResolveProcessRequest.StaticMaterializations
	(*ResolveProcessRequest_Resume)(nil),                 // 5: confidence.flags.resolver.v1.ResolveProcessRequest.Resume
	(*ResolveProcessResponse_Resolved)(nil),              // 6: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved
	(*ResolveProcessResponse_Suspended)(nil),             // 7: confidence.flags.resolver.v1.ResolveProcessResponse.Suspended
	(*resolver.ResolveFlagsRequest)(nil),                 // 8: confidence.flags.resolver.v1.ResolveFlagsRequest
	(*resolver.ResolveFlagsResponse)(nil),                // 9: confidence.flags.resolver.v1.ResolveFlagsResponse
}
var file_confidence_wasm_wasm_api_proto_depIdxs = []int32{
	8,  // 0: confidence.flags.resolver.v1.ResolveProcessRequest.deferred_materializations:type_name -> confidence.flags.resolver.v1.ResolveFlagsRequest
	4,  // 1: confidence.flags.resolver.v1.ResolveProcessRequest.static_materializations:type_name -> confidence.flags.resolver.v1.ResolveProcessRequest.StaticMaterializations
	8,  // 2: confidence.flags.resolver.v1.ResolveProcessRequest.without_materializations:type_name -> confidence.flags.resolver.v1.ResolveFlagsRequest
	5,  // 3: confidence.flags.resolver.v1.ResolveProcessRequest.resume:type_name -> confidence.flags.resolver.v1.ResolveProcessRequest.Resume
	6,  // 4: confidence.flags.resolver.v1.ResolveProcessResponse.resolved:type_name -> confidence.flags.resolver.v1.ResolveProcessResponse.Resolved
	7,  // 5: confidence.flags.resolver.v1.ResolveProcessResponse.suspended:type_name -> confidence.flags.resolver.v1.ResolveProcessResponse.Suspended
	8,  // 6: confidence.flags.resolver.v1.ResolveProcessRequest.StaticMaterializations.resolve_request:type_name -> confidence.flags.resolver.v1.ResolveFlagsRequest
	2,  // 7: confidence.flags.resolver.v1.ResolveProcessRequest.StaticMaterializations.materializations:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	2,  // 8: confidence.flags.resolver.v1.ResolveProcessRequest.Resume.materializations:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	9,  // 9: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved.response:type_name -> confidence.flags.resolver.v1.ResolveFlagsResponse
	2,  // 10: confidence.flags.resolver.v1.ResolveProcessResponse.Resolved.materializations_to_write:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	2,  // 11: confidence.flags.resolver.v1.ResolveProcessResponse.Suspended.materializations_to_read:type_name -> confidence.flags.resolver.v1.MaterializationRecord
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_confidence_wasm_wasm_api_proto_init() }
func file_confidence_wasm_wasm_api_proto_init() {
	if File_confidence_wasm_wasm_api_proto != nil {
		return
	}
	file_confidence_wasm_wasm_api_proto_msgTypes[0].OneofWrappers = []any{
		(*ResolveProcessRequest_DeferredMaterializations)(nil),
		(*ResolveProcessRequest_StaticMaterializations_)(nil),
		(*ResolveProcessRequest_WithoutMaterializations)(nil),
		(*ResolveProcessRequest_Resume_)(nil),
	}
	file_confidence_wasm_wasm_api_proto_msgTypes[1].OneofWrappers = []any{
		(*ResolveProcessResponse_Resolved_)(nil),
		(*ResolveProcessResponse_Suspended_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confidence_wasm_wasm_api_proto_rawDesc), len(file_confidence_wasm_wasm_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confidence_wasm_wasm_api_proto_goTypes,
		DependencyIndexes: file_confidence_wasm_wasm_api_proto_depIdxs,
		MessageInfos:      file_confidence_wasm_wasm_api_proto_msgTypes,
	}.Build()
	File_confidence_wasm_wasm_api_proto = out.File
	file_confidence_wasm_wasm_api_proto_goTypes = nil
	file_confidence_wasm_wasm_api_proto_depIdxs = nil
}
